objects/ABC_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Over_balance_Countdown_days__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Over balance – Countdown days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ABC Profile</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ABC Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Portfolio__c.object
<CustomObject>
    <description>Contains details of all credit cards or payment authorization agreements that person is responsible for.  One record per person, or per group responsible for a Meeting series</description>
    <fields>
        <fullName>Advisory_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Advisory Profile</label>
        <referenceTo>ABC_Profile__c</referenceTo>
        <relationshipName>Credit_Portfolios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deactivation_Reason__c</fullName>
        <label>Deactivation Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Over Credit Balance Limit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over Age Limit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee no longer exists</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_warning_Aging__c</fullName>
        <label>Final warning – Aging</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_warning_Balance__c</fullName>
        <label>Final warning - Balance</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Over_Balance_Warning_Sent_On__c</fullName>
        <description>This field is to hold the datetime value when the last balance warning email was sent.</description>
        <label>Last Over Balance Warning Sent On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Over_balance_Countdown_days__c</fullName>
        <formula>IF( NOT(ISBLANK(Final_warning_Balance__c)),  Final_warning_Balance__c - TODAY(), null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Over balance – Countdown days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Utilized_Balance__c</fullName>
        <formula>IF( Advisory_Profile_Credit_Limit__c &gt; 0, Balance__c/Advisory_Profile_Credit_Limit__c, null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utilized Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Credit Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Sched_PopulateFinalWarningBalance.cls
/**
 *  Description     :   This class is to check if any of the Portfolio in under the Final  Warning Balance  limit and then updat that field
 *
 *  Created By      :   Bhavi Sharma
 *
 *  Created Date    :   11/04/2015
 *
 *  Revision Logs   :   V_1.0 - Created
 *
 **/
global class Sched_PopulateFinalWarningBalance implements Schedulable {
    
    //execute method
    global void execute(SchedulableContext SC) {
        
        //Calculate Warning Email Status and Warning dates
        Sched_PopulateFinalWarningBalance.calculateFinalWarningBalance();
    }
    
    //Static method so it can be executed from anywhere
    public static void calculateFinalWarningBalance() {
        
        //Fetch all the portfoli records under Final warning aging
        List<Portfolio__c> portfolios = [Select Id, Status__c, Deactivation_Reason__c, Last_Over_Balance_Warning_Sent_On__c, 
        										Final_warning_Balance__c, Over_balance_Countdown_days__c, Utilized_Balance__c,
        										Advisory_Profile__r.Over_balance_Countdown_days__c
        										from Portfolio__c 
                                                where 
                                                //Only pull the Credit Card if it's active and over limit
                                                Utilized_Balance__c > 100 AND
                                                Status__c =: CreditCardConstants.PORTFOLIO_STATUS_ACTIVATED
                                         ];
                                                        
        //Loop through the records and populate the Final_Warning_Aging__c
        for(Portfolio__c portfolio : portfolios) {
            
            //Countdown days
            Decimal countdownDays = portfolio.Over_balance_Countdown_days__c != null ? portfolio.Over_balance_Countdown_days__c : portfolio.Advisory_Profile__r.Over_balance_Countdown_days__c;
            System.debug('countdownDays:::::' + countdownDays);
            //Card deactivation date
            Date deactivationDate = Date.today() + Integer.valueOf(countdownDays);
        	if(portfolio.Final_warning_Balance__c != deactivationDate)
        		portfolio.Final_warning_Balance__c = deactivationDate;
            System.debug('Utilized_Balance__c:::::' + portfolio.Utilized_Balance__c);
            //First Warning Portfolios
            if(portfolio.Over_balance_Countdown_days__c == null || portfolio.Over_balance_Countdown_days__c > 0) {
                
                //Send the email right away to user
                portfolio.Last_Over_Balance_Warning_Sent_On__c = Datetime.Now();
            } else {
            	
            	//Deactivate the card along with the reason
            	portfolio.Status__c = CreditCardConstants.PORTFOLIO_STATUS_DEACTIVATED;
            	portfolio.Deactivation_Reason__c = CreditCardConstants.PORTFOLIO_DEACTIVATION_REASON_OVER_CREDIT_BALANNCE_LIMIT;
            }
        }

        //Ceck for the size and run update
        if(portfolios.size() > 0)
            update portfolios;
    }
}