objects/ABC_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Over_aging_Maximum_days__c</fullName>
        <defaultValue>45</defaultValue>
        <label>Over aging – Maximum days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Over_aging_Warning_days__c</fullName>
        <defaultValue>20</defaultValue>
        <label>Over aging – Warning days 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Over_balance_Countdown_days__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Over balance – Countdown days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Over_balance_Warning_threshold_1__c</fullName>
        <defaultValue>0.60</defaultValue>
        <label>Over balance – Warning threshold 1</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Over_balance_Warning_threshold_2__c</fullName>
        <defaultValue>0.80</defaultValue>
        <label>Over balance – Warning threshold 2</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Provider_Profile__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Provider Profile</label>
        <referenceTo>Provider_Profile__c</referenceTo>
        <relationshipLabel>ABC Profiles</relationshipLabel>
        <relationshipName>ABC_Profiles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ABC Profile</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ABC Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Credit_Card__c.object
<CustomObject>
    <description>A credit card or payment authorization</description>
    <fields>
        <fullName>Card_Requested_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <label>Card Requested By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Credit Cards</relationshipLabel>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_Vendor__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <inlineHelpText>Card Issuer</inlineHelpText>
        <label>Card Vendor</label>
        <picklist>
            <picklistValues>
                <fullName>BMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comdata</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Employee_Id__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <inlineHelpText>Employee Finance Code Id</inlineHelpText>
        <label>zzzEmployee Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Account__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <label>Portfolio</label>
        <referenceTo>Portfolio__c</referenceTo>
        <relationshipLabel>Credit Cards</relationshipLabel>
        <relationshipName>Credit_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <label>Advisory Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Card</label>
    <nameField>
        <label>Credit Card Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <recordTypes>
        <fullName>ABC_Staff_Credit_Card</fullName>
        <active>true</active>
        <description>Credit Card for use by a staff member for business travel and other travel expenses</description>
        <label>ABC Staff Credit Card</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Card_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Card_Vendor__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin.  Used in Approve Card Request Flow</description>
        <label>Card Vendor</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Card_Record_Type__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin.  Used in Approve Card Request Flow</description>
        <label>Staff Card Record Type</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Portfolio_Record_Type__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin.  Used in Approve Card Request Flow</description>
        <label>Staff Portfolio Record Type</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <inlineHelpText>Set to &apos;Active&apos; to make this the active set of settings (Only one may be set as Active)</inlineHelpText>
        <label>Status</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Credit Card Settings</label>
    <nameField>
        <label>Credit Card Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Card Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OSR__c.object
<CustomObject>
    <description>Operational Service Request</description>
    <fields>
        <fullName>Address_City__c</fullName>
        <description>Used for Credit Card expedited shipping address
        
        Origin: CR-2089 - CreditCardAdmin</description>
        <label>Address City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>Used for Credit Card expedited shipping address
        
        Origin: CR-2089 - CreditCardAdmin</description>
        <label>Address Line 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_State__c</fullName>
        <description>Used for Credit Card expedited shipping address
        
        Origin: CR-2089 - CreditCardAdmin</description>
        <inlineHelpText>2 Letter State Abbreviation</inlineHelpText>
        <label>Address State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Updated by Credit Card Request from Travel Portal
        
        Origin: CR-2089 - CreditCardAdmin</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>OSR</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>OSR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSRs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Portfolio__c.object
<CustomObject>
    <description>Contains details of all credit cards or payment authorization agreements that person is responsible for.  One record per person, or per group responsible for a Meeting series</description>
    <fields>
        <fullName>Billing_Address_Attention_To__c</fullName>
        <label>Billing Address Attention To</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Address_City__c</fullName>
        <label>Billing Address City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <label>Billing Address Line 1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_2__c</fullName>
        <label>Billing Address Line 2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Address_PostalCode__c</fullName>
        <label>Billing Address PostalCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Address_State__c</fullName>
        <label>Billing Address State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Holder__c</fullName>
        <label>Card Holder</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Credit Portfolios (Card Holder)</relationshipLabel>
        <relationshipName>Credit_Portfolios</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name_On_Card__c</fullName>
        <label>First Name On Card</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_On_Card__c</fullName>
        <label>Last Name On Card</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Over_aging_Maximum_days__c</fullName>
        <formula>Advisory_Profile__r.Over_aging_Maximum_days__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Over aging – Maximum days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Over_balance_Countdown_days__c</fullName>
        <formula>IF( NOT(ISBLANK(Final_warning_Balance__c)),  Final_warning_Balance__c - TODAY(), null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Over balance – Countdown days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Over_balance_Warning_threshold_1__c</fullName>
        <formula>Advisory_Profile__r.Over_balance_Warning_threshold_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Over balance – Warning threshold 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Over_balance_Warning_threshold_2__c</fullName>
        <formula>Advisory_Profile__r.Over_balance_Warning_threshold_2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Over balance – Warning threshold 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Portfolio_Owner_Finance_Code__c</fullName>
        <description>Populate from Contact - Contact.Employee User Record.Finance Code
        
        Origin: CR-2089 - CreditCardAdmin</description>
        <externalId>true</externalId>
        <label>Portfolio Owner Finance Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Portfolios</pluralLabel>
    <recordTypes>
        <fullName>Employee_Payment_Account</fullName>
        <active>true</active>
        <description>Payment Account for all cards for an employee</description>
        <label>Employee Payment Account</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Provider_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Provider_Profile_ID__c</fullName>
        <externalId>true</externalId>
        <label>Provider Profile ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Provider Profile</label>
    <nameField>
        <label>Provider Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_Batch_ProcessOSRs.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.    
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_Batch_ProcessOSRs {
/**
 *  Description     :   Test class for Batch_ProcessOSRs
 *
 *  Created By      :   Bhavi Sharma
 *
 *  Created Date    :   01/30/2014
 *
 *  Revision Logs   :   V_1.0 - Created
 *                      V_1.1 - Modified - 12/9/2014 - By Bhavi  Sharma
 * 						V_1.2 - Modified - 12/1/2015- By Mahendra Swarnkar - Removed the Credit_Limit__c field reference, as it will no longer in use.
 *
 *  Coverage        :   78%
 *
 **/
    
    //instance of Mock service class 
    static CreditCardServiceMockClass mockController = new CreditCardServiceMockClass();
    
    //HttpRequest instance
    static Httprequest req = new Httprequest();
    
    //Setup test data first. This will be available in the entire class
    @testSetup static void setup() {
    
        //insert Credit Card Settings record
        Credit_Card_Settings__c configCCDefaultSetting = TestUtilities.CreateCreditCardSettings();
        insert configCCDefaultSetting;
        
        //Set helper class variable
        CreditCardHelper.configDefaults = configCCDefaultSetting;
        CreditCardConstants.CONFIG_DEFAULT = configCCDefaultSetting;
    }
    
    //Test add Credit Card method
    static testMethod void testReplaceCard() {
    
        //User record
        User currentUser;
        
        //Update the User Finance Code if not alreayd populated
        System.runAs(new User(Id = UserInfo.getUserId())) {
            
            //Update the Employee Id
            currentUser = new User(Id = UserInfo.getUserId(), Finance_Code__c = '50011');
            update currentUser;
        }
        
         //insert Credit Card Settings record 
        Credit_Card_Settings__c configCCDefaultSetting = CreditCardConstants.CONFIG_DEFAULT;
        
        //insert Contact record
        Contact contact = TestUtilities.CreateNewContact(false);
        contact.Birthdate = System.today().addYears(-28);
        contact.Employee_ID__c = '50011';
        contact.Employee_User_Record__c = UserInfo.getUserId();
        insert contact;
        
        //Create a Provider Profile instance
        Provider_Profile__c pP = new Provider_Profile__c(Provider_Profile_ID__c = '2');
        insert pP;
        
        //Create a test ABC Profile record
        ABC_Profile__c abcProfile = new ABC_Profile__c(Name = 'Test', 
                                                            Over_aging_Warning_days__c = 35, 
                                                            Over_aging_Maximum_days__c = 45, 
                                                            Over_balance_Warning_threshold_1__c = .75, 
                                                            Over_balance_Warning_threshold_2__c = .90, 
                                                            Over_balance_Countdown_days__c = 3,
                                                            Provider_Profile__c = pP.Id);
        insert abcProfile;
        
        //Quering portfolio record types details
        List<RecordType> rdTypesPortfolio = [select Id from RecordType 
                                            where DeveloperName = 'Employee_Payment_Account' AND
                                            SobjectType = 'Portfolio__c' AND IsActive = true];
        
        //Quering credit card record types details
        List<RecordType> rdTypesCreditCard = [select Id from RecordType 
                                                WHERE DeveloperName = 'ABC_Staff_Credit_Card' AND
                                                SobjectType = 'Credit_Card__c' AND IsActive = true];
        
        //Assert for the results
        System.assert(rdTypesPortfolio != null); 
        System.assert(rdTypesCreditCard != null);
        
        //Update configCCDefaultSetting field
        configCCDefaultSetting.Staff_Portfolio_Record_Type__c = rdTypesPortfolio[0].id;
        configCCDefaultSetting.Staff_Card_Record_Type__c = rdTypesCreditCard[0].id;
        update configCCDefaultSetting;
        
        //Portfolio Records
        Portfolio__c portfolio = new Portfolio__c(Billing_Address_Attention_To__c = 'Test', 
                                                    Billing_Address_Line_1__c = 'Test', 
                                                    Billing_Address_Line_2__c = 'Test', 
                                                    Billing_Address_City__c = 'San Francisco', 
                                                    Billing_Address_State__c = 'CA', 
                                                    Billing_Address_PostalCode__c = '98565', 
                                                    First_Name_On_Card__c = 'Bhavi', 
                                                    Last_Name_On_Card__c = 'Sharma', 
                                                    Card_Holder__c = contact.Id, 
                                                    RecordTypeId = configCCDefaultSetting.Staff_Portfolio_Record_Type__c, 
                                                    Status__c = CreditCardConstants.PORTFOLIO_STATUS_ACTIVATED);
        insert portfolio;
        
        //At this stage workflow will be get executed and Owner Finance code will be get populated
        //Assert for the results
        portfolio = [Select Id, Portfolio_Owner_Finance_Code__c from Portfolio__c where Id =: portfolio.Id];
        System.assertEquals(currentUser.Finance_Code__c, portfolio.Portfolio_Owner_Finance_Code__c);
        
        //Create a new Credit Card record
        Credit_Card__c creditCard = new Credit_Card__c(Card_Requested_By__c = contact.Id, 
                                                            Card_Vendor__c = configCCDefaultSetting.Card_Vendor__c,
                                                            Payment_Account__c = portfolio.Id, 
                                                            RecordTypeId = configCCDefaultSetting.Staff_Card_Record_Type__c, 
                                                            Status__c = CreditCardConstants.CC_STATUS_ACTIVE,
                                                            Card_Set_up_Status__c = CreditCardConstants.CC_SETUP_STATUS_SUCCESS);
        insert creditCard;
          
        //Resord Type Credit Card request
        List<RecordType> recordTypeOSRCreditCardRequest =[Select Id from RecordType where SObjectType = 'OSR__c' 
                                                            AND DeveloperName =: CreditCardConstants.OSR_RECORD_TYPE_DEVELOPER_NAME_CREDIT_CARD_REQUEST 
                                                            AND IsActive = true limit 1];
        System.assertEquals(1, recordTypeOSRCreditCardRequest.size());
        
        //List of OSR to be record
        OSR__c oSR = new OSR__c(RecordTypeId = recordTypeOSRCreditCardRequest[0].Id, Request_Type__c = CreditCardConstants.OSR_REQUEST_TYPE_REPLACEMENT_ABC_CREDIT_CARD,
                     Status__c = CreditCardConstants.OSR_STATUS_NEW, Related_Card__c = creditCard.Id, Contact__c = contact.Id, 
                     Address_To_Name__c = 'Test', Address_Line_1__c = 'Test', Address_City__c = 'Test',
                     Address_Postal_Code__c = 'Test', Origin__c = CreditCardConstants.OSR_ORIGIN_TRAVEL_PORTAL,
                     Address_State__c = 'Test');
            
        //Start testing from here
        Test.startTest();
        
        //Initialize method number for deactivateCreditCardForReplacement
        CreditCardServiceMockClass.methodNumber = 3;
        
        //Response of deactivateCreditCardForReplacement request
        HttpService.response = mockController.respond(req);
        
        //Insert the OSR record, it will execute the batch automatically
        insert oSR;
        
        //Stop Test Here
        Test.stopTest();
    
        //Fetch data from database and assert the results
        oSR = [Select Status__c, Cancellation_Reason__c from OSR__c where Id =: oSR.Id];
        System.assertEquals(null, oSR.Cancellation_Reason__c);
        System.assertEquals(CreditCardConstants.OSR_STATUS_COMPLETE, oSR.Status__c);
        
        //Cards
        creditCard = [Select Status__c, Card_Deactivation_Status__c from Credit_Card__c where Id =: creditCard.Id order by Status__c];
        System.assertEquals(CreditCardConstants.CC_STATUS_PENDING_DEACTIVATION, creditCard.Status__c);
        System.assertEquals(CreditCardConstants.CC_DEACTIVATION_STATUS_PENDING_REPLACEMENT_ACTIVATION, creditCard.Card_Deactivation_Status__c);
    }
    
    //Test add Credit Card method
    static testMethod void testReplaceLostCard() {
    
        //User record
        User currentUser;
        
        //Update the User Finance Code if not alreayd populated
        System.runAs(new User(Id = UserInfo.getUserId())) {
            
            //Update the Employee Id
            currentUser = new User(Id = UserInfo.getUserId(), Finance_Code__c = '50011');
            update currentUser;
        }
        
         //insert Credit Card Settings record 
        Credit_Card_Settings__c configCCDefaultSetting = CreditCardConstants.CONFIG_DEFAULT;
        
        //insert Contact record
        Contact contact = TestUtilities.CreateNewContact(false);
        contact.Birthdate = System.today().addYears(-28);
        contact.Employee_ID__c = '50011';
        contact.Employee_User_Record__c = UserInfo.getUserId();
        insert contact;
        
        //Create a Provider Profile instance
        Provider_Profile__c pP = new Provider_Profile__c(Provider_Profile_ID__c = '2');
        insert pP;
        
        //Create a test ABC Profile record
        ABC_Profile__c abcProfile = new ABC_Profile__c(Name = 'Test', 
                                                            Over_aging_Warning_days__c = 35, 
                                                            Over_aging_Maximum_days__c = 45, 
                                                            Over_balance_Warning_threshold_1__c = .75, 
                                                            Over_balance_Warning_threshold_2__c = .90, 
                                                            Over_balance_Countdown_days__c = 3,
                                                            Provider_Profile__c = pP.Id);
        insert abcProfile;
        
        //Quering portfolio record types details
        List<RecordType> rdTypesPortfolio = [select Id from RecordType 
                                            where DeveloperName = 'Employee_Payment_Account' AND
                                            SobjectType = 'Portfolio__c' AND IsActive = true];
        
        //Quering credit card record types details
        List<RecordType> rdTypesCreditCard = [select Id from RecordType 
                                                WHERE DeveloperName = 'ABC_Staff_Credit_Card' AND
                                                SobjectType = 'Credit_Card__c' AND IsActive = true];
        
        //Assert for the results
        System.assert(rdTypesPortfolio != null); 
        System.assert(rdTypesCreditCard != null);
        
        //Update configCCDefaultSetting field
        configCCDefaultSetting.Staff_Portfolio_Record_Type__c = rdTypesPortfolio[0].id;
        configCCDefaultSetting.Staff_Card_Record_Type__c = rdTypesCreditCard[0].id;
        update configCCDefaultSetting;
        
        //Portfolio Records
        Portfolio__c portfolio = new Portfolio__c(Billing_Address_Attention_To__c = 'Test', 
                                                    Billing_Address_Line_1__c = 'Test', 
                                                    Billing_Address_Line_2__c = 'Test', 
                                                    Billing_Address_City__c = 'San Francisco', 
                                                    Billing_Address_State__c = 'CA', 
                                                    Billing_Address_PostalCode__c = '98565', 
                                                    First_Name_On_Card__c = 'Bhavi', 
                                                    Last_Name_On_Card__c = 'Sharma', 
                                                    Card_Holder__c = contact.Id, 
                                                    RecordTypeId = configCCDefaultSetting.Staff_Portfolio_Record_Type__c, 
                                                    Status__c = CreditCardConstants.PORTFOLIO_STATUS_ACTIVATED);
        insert portfolio;
        
        //At this stage workflow will be get executed and Owner Finance code will be get populated
        //Assert for the results
        portfolio = [Select Id, Portfolio_Owner_Finance_Code__c from Portfolio__c where Id =: portfolio.Id];
        System.assertEquals(currentUser.Finance_Code__c, portfolio.Portfolio_Owner_Finance_Code__c);
        
        //Create a new Credit Card record
        Credit_Card__c creditCard = new Credit_Card__c(Card_Requested_By__c = contact.Id, 
                                                            Card_Vendor__c = configCCDefaultSetting.Card_Vendor__c,
                                                            Payment_Account__c = portfolio.Id, 
                                                            RecordTypeId = configCCDefaultSetting.Staff_Card_Record_Type__c, 
                                                            Status__c = CreditCardConstants.CC_STATUS_ACTIVE,
                                                            Card_Set_up_Status__c = CreditCardConstants.CC_SETUP_STATUS_SUCCESS);
        insert creditCard;
          
        //Resord Type Credit Card request
        List<RecordType> recordTypeOSRCreditCardRequest =[Select Id from RecordType where SObjectType = 'OSR__c' 
                                                            AND DeveloperName =: CreditCardConstants.OSR_RECORD_TYPE_DEVELOPER_NAME_CREDIT_CARD_REQUEST 
                                                            AND IsActive = true limit 1];
        System.assertEquals(1, recordTypeOSRCreditCardRequest.size());
        
        //OSR record
        OSR__c oSR = new OSR__c(RecordTypeId = recordTypeOSRCreditCardRequest[0].Id, Request_Reason__c = CreditCardConstants.OSR_REQUEST_REASON_LOST, 
                                Request_Type__c = CreditCardConstants.OSR_REQUEST_TYPE_REPLACEMENT_ABC_CREDIT_CARD, Status__c = CreditCardConstants.OSR_STATUS_NEW, 
                                Related_Card__c = creditCard.Id, Contact__c = contact.Id, Address_To_Name__c = 'Test', Address_Line_1__c = 'Test', 
                                Address_City__c = 'Test', Address_State__c = 'Test', Address_Postal_Code__c = 'Test', 
                                Origin__c = CreditCardConstants.OSR_ORIGIN_TRAVEL_PORTAL);
         
        //Start testing from here
        Test.startTest();
        
        //Initialize method number for deactivateCreditCardForReplacement
        CreditCardServiceMockClass.methodNumber = 3;
        HttpService.response = mockController.respond(req);
        
        //Insert the OSR record, it will execute the batch automatically
        insert oSR;
        
        //Stop Test Here
        Test.stopTest();
    
        //Assert for the results
        oSR = [Select Status__c, Cancellation_Reason__c from OSR__c where Id =: oSR.Id];
        System.assertEquals(null, oSR.Cancellation_Reason__c);
        System.assertEquals(CreditCardConstants.OSR_STATUS_COMPLETE, oSR.Status__c);
        
        //Cards
        creditCard = [Select Status__c, Card_Deactivation_Status__c from Credit_Card__c where Id =: creditCard.Id  order by Status__c];
        System.assertEquals(CreditCardConstants.CC_STATUS_DEACTIVATED, creditCard.Status__c);
        System.assertEquals(CreditCardConstants.CC_DEACTIVATION_STATUS_DEACTIVATED, creditCard.Card_Deactivation_Status__c);
    }
}