objects/ABC_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Over_aging_Maximum_days__c</fullName>
        <defaultValue>45</defaultValue>
        <label>Over aging – Maximum days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Over_aging_Warning_days__c</fullName>
        <defaultValue>20</defaultValue>
        <label>Over aging – Warning days 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ABC Profile</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ABC Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Portfolio__c.object
<CustomObject>
    <description>Contains details of all credit cards or payment authorization agreements that person is responsible for.  One record per person, or per group responsible for a Meeting series</description>
    <fields>
        <fullName>Advisory_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Advisory Profile</label>
        <referenceTo>ABC_Profile__c</referenceTo>
        <relationshipName>Credit_Portfolios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deactivation_Reason__c</fullName>
        <label>Deactivation Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Over Credit Balance Limit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over Age Limit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee no longer exists</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_warning_Aging__c</fullName>
        <label>Final warning – Aging</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Oldest_Transaction_Over_Warning_Days__c</fullName>
        <formula>Oldest_transaction__c &lt; TODAY() - (Advisory_Profile__r.Over_aging_Warning_days__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Oldest Transaction Over Warning Days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Oldest_Transaction_Days__c</fullName>
        <formula>TODAY() - Oldest_transaction__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Oldest Transaction Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Oldest_transaction__c</fullName>
        <label>Oldest transaction</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Over_aging_Maximum_days__c</fullName>
        <formula>Advisory_Profile__r.Over_aging_Maximum_days__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Over aging – Maximum days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Warning_Email_Status__c</fullName>
        <description>Created for CR-20151020-9342</description>
        <label>Warning Email Status</label>
        <picklist>
            <picklistValues>
                <fullName>Send First Warning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Warning Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Second Warning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Warning Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Third Warning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Warning Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivate Portfolio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio Deactivated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Warning_Type__c</fullName>
        <formula>IF(
	AND(
		(Oldest_transaction__c + Advisory_Profile__r.Over_aging_Warning_days__c) &lt; TODAY(),
		(Oldest_transaction__c + Advisory_Profile__r.Over_aging_Warning_days_2__c) &gt;= TODAY()
	),
	&apos;First&apos;,
	IF(
		AND(
			(Oldest_transaction__c + Advisory_Profile__r.Over_aging_Warning_days_2__c) &lt; TODAY(),
			(Oldest_transaction__c + Advisory_Profile__r.Over_aging_Warning_days_3__c) &gt;= TODAY()
		),
		&apos;Second&apos;,
		IF(
			AND(
				(Oldest_transaction__c + Advisory_Profile__r.Over_aging_Warning_days_3__c) &lt; TODAY(),
				(Oldest_transaction__c + Advisory_Profile__r.Over_aging_Maximum_days__c) &gt;= TODAY()
			),
			&apos;Third&apos;,
			IF(
				AND(
					(Oldest_transaction__c + Advisory_Profile__r.Over_aging_Maximum_days__c) &lt; TODAY()
				),
				&apos;Deactivate&apos;,
				&apos;&apos;
			)
		)
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Warning Type</label>
        <type>Text</type>
    </fields>
    <label>Credit Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Sched_PopulateFinalWarningAging.cls
/**
 *  Description     :   This class is to check if any of the Portfolio in under the Final  Warning Aging  limit and then updat that field
 *
 *  Created By      :   Bhavi Sharma
 *
 *  Created Date    :   12/03/2014
 *
 *  Revision Logs   :   V_1.0 - Created
 *						V_1.2 - 10/23/2015 - Bhavi Sharma - CR-20151019-9335 - Deactivation will be handled by Scheduled Job now
 *
 **/
global class Sched_PopulateFinalWarningAging implements Schedulable {
    
    //execute method
    global void execute(SchedulableContext SC) {
        
        //Calculate Warning Email Status and Warning dates
        Sched_PopulateFinalWarningAging.calculateFinalWarningAging();
    }
    
    //Static method so it can be executed from anywhere
    public static void calculateFinalWarningAging() {
        
        //Fetch all the portfoli records under Final warning aging
        List<Portfolio__c> portfolios = [Select Id, Oldest_Transaction__c, Is_Oldest_Transaction_Over_Warning_Days__c, Oldest_Transaction_Days__c,
                                                Warning_Type__c, Warning_Email_Status__c, Status__c, Deactivation_Reason__c, Final_Warning_Aging__c,
                                                Advisory_Profile__r.Over_aging_Warning_days__c, 
                                                Advisory_Profile__r.Over_aging_Maximum_days__c from Portfolio__c 
                                                where 
                                                //Pull the records fits in First Threshold
                                                (Is_Oldest_Transaction_Over_Warning_Days__c = true
                                                    AND Warning_Type__c =: CreditCardConstants.PORTFOLIO_WARNING_TYPE_FIRST
                                                    AND Warning_Email_Status__c !=: CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_SEND_FIRST_WARNING
                                                    AND Warning_Email_Status__c !=: CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_FIRST_WARNING_SENT
                                                ) OR
                                                //Pull the records fits in Second Threshold
                                                (Is_Oldest_Transaction_Over_Warning_Days__c = true
                                                    AND Warning_Type__c =: CreditCardConstants.PORTFOLIO_WARNING_TYPE_SECOND
                                                    AND Warning_Email_Status__c !=: CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_SEND_SECOND_WARNING
                                                    AND Warning_Email_Status__c !=: CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_SECOND_WARNING_SENT
                                                ) OR
                                                //Pull the records fits in Third Threshold
                                                (Is_Oldest_Transaction_Over_Warning_Days__c = true
                                                    AND Warning_Type__c =: CreditCardConstants.PORTFOLIO_WARNING_TYPE_THIRD
                                                    AND Warning_Email_Status__c !=: CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_SEND_THIRD_WARNING
                                                    AND Warning_Email_Status__c !=: CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_THIRD_WARNING_SENT
                                                ) OR
                                                //Pull the records fits in Final Threshold
                                                (Is_Oldest_Transaction_Over_Warning_Days__c = true
                                                    AND Warning_Type__c =: CreditCardConstants.PORTFOLIO_WARNING_TYPE_DEACTIVATE
                                                    AND Warning_Email_Status__c !=: CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_DEACTIVATE_PORTFOLIO
                                                    AND Warning_Email_Status__c !=: CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_PORTFOLIO_DEACTIVATED
                                                ) OR
                                                //Pull the records fits in blank warning criteria and activation again
                                                (Warning_Type__c !=: CreditCardConstants.PORTFOLIO_WARNING_TYPE_DEACTIVATE
                                                    AND Status__c =: CreditCardConstants.PORTFOLIO_STATUS_DEACTIVATED
                                                    AND Deactivation_Reason__c =: CreditCardConstants.PORTFOLIO_DEACTIVATION_REASON_OVER_AGE_LIMIT
                                                )
                                         ];
                                                        
        //Loop through the records and populate the Final_Warning_Aging__c
        for(Portfolio__c portfolio : portfolios) {
            
            //First Warning Portfolios
            if(portfolio.Is_Oldest_Transaction_Over_Warning_Days__c == true
                && portfolio.Warning_Type__c == CreditCardConstants.PORTFOLIO_WARNING_TYPE_FIRST
                && portfolio.Warning_Email_Status__c != CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_SEND_FIRST_WARNING
                && portfolio.Warning_Email_Status__c != CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_FIRST_WARNING_SENT) {
                
                //Set the warning type
                portfolio.Warning_Email_Status__c = CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_SEND_FIRST_WARNING;
                        
            } 
            
            //Check for teh records applicable for second threshold
            else if(portfolio.Is_Oldest_Transaction_Over_Warning_Days__c == true
                && portfolio.Warning_Type__c == CreditCardConstants.PORTFOLIO_WARNING_TYPE_SECOND
                && portfolio.Warning_Email_Status__c != CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_SEND_SECOND_WARNING
                && portfolio.Warning_Email_Status__c != CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_SECOND_WARNING_SENT) {
                
                //Set the warning type
                portfolio.Warning_Email_Status__c = CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_SEND_SECOND_WARNING;
                        
            } 
            
            //Check for teh records applicable for third threshold
            else if(portfolio.Is_Oldest_Transaction_Over_Warning_Days__c == true
                && portfolio.Warning_Type__c == CreditCardConstants.PORTFOLIO_WARNING_TYPE_THIRD
                && portfolio.Warning_Email_Status__c != CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_SEND_THIRD_WARNING
                && portfolio.Warning_Email_Status__c != CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_THIRD_WARNING_SENT) {
                
                //Set the warning type
                portfolio.Warning_Email_Status__c = CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_SEND_THIRD_WARNING;
                    
            } 
            
            //Check for the records applicable for deactivattion
            else if(portfolio.Is_Oldest_Transaction_Over_Warning_Days__c == true
                && portfolio.Warning_Type__c == CreditCardConstants.PORTFOLIO_WARNING_TYPE_DEACTIVATE
                && portfolio.Warning_Email_Status__c != CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_DEACTIVATE_PORTFOLIO
                && portfolio.Warning_Email_Status__c != CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_PORTFOLIO_DEACTIVATED) {
                
                //Set the warning type
                portfolio.Warning_Email_Status__c = CreditCardConstants.PORTFOLIO_WARNING_EMAIL_STATUS_DEACTIVATE_PORTFOLIO;
                portfolio.Status__c = CreditCardConstants.PORTFOLIO_STATUS_DEACTIVATED;
                portfolio.Deactivation_Reason__c = CreditCardConstants.PORTFOLIO_DEACTIVATION_REASON_OVER_AGE_LIMIT;
                        
            }
            
            //Check for the records can be activated again
            if((portfolio.Oldest_Transaction_Days__c == null 
            	|| portfolio.Oldest_Transaction_Days__c <= portfolio.Advisory_Profile__r.Over_aging_Maximum_days__c) 
                && portfolio.Status__c == CreditCardConstants.PORTFOLIO_STATUS_DEACTIVATED
                && portfolio.Deactivation_Reason__c == CreditCardConstants.PORTFOLIO_DEACTIVATION_REASON_OVER_AGE_LIMIT) {
                
                //Set the warning type
                portfolio.Status__c = CreditCardConstants.PORTFOLIO_STATUS_ACTIVATED;
            }
            
            //Set the date value
            if(portfolio.Oldest_Transaction__c != null) {
	            
	            Date finalWarningAging = portfolio.Oldest_Transaction__c + (Integer)portfolio.Advisory_Profile__r.Over_aging_Maximum_days__c;
	            if(portfolio.Is_Oldest_Transaction_Over_Warning_Days__c == true && portfolio.Final_Warning_Aging__c != finalWarningAging)
	                portfolio.Final_Warning_Aging__c = finalWarningAging;
	            else if(portfolio.Is_Oldest_Transaction_Over_Warning_Days__c == false && portfolio.Final_Warning_Aging__c != null)
	                portfolio.Final_Warning_Aging__c = null;
            } else
            	portfolio.Final_Warning_Aging__c = null;
        }

        //Ceck for the size and run update
        if(portfolios.size() > 0)
            update portfolios;
    }
}