objects/Advisory_Event__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as part of the Events Management project</description>
        <label>Cost Center</label>
        <referenceTo>Cost_Center__c</referenceTo>
        <relationshipName>Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as part of the Events Management project</description>
        <label>Parent Event</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Event, Series</value>
            </filterItems>
            <filterItems>
                <field>Advisory_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Series</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Session</value>
            </filterItems>
            <filterItems>
                <field>Advisory_Event__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Event</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Advisory_Event__c</referenceTo>
        <relationshipLabel>Advisory Events</relationshipLabel>
        <relationshipName>Advisory_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Created as part of the Events Management project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Forecasted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Calendar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Manual Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open - Waitlist Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Advisory Event</label>
    <nameField>
        <label>Advisory Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advisory Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Cost_Center__c.object
<CustomObject>
    <description>Created as part of the Events Management Project</description>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as part of the Events Management project</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budget_G_L</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Created as part of the Events Management project</description>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event_Registration__c.object
<CustomObject>
    <fields>
        <fullName>Advisory_Event__c</fullName>
        <label>Advisory Event</label>
        <referenceTo>Advisory_Event__c</referenceTo>
        <relationshipLabel>Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Identified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VOID</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Expense_Authorization__c.object
<CustomObject>
    <fields>
        <fullName>Advisory_Event__c</fullName>
        <formula>Event_Registration__r.Advisory_Event__r.Name</formula>
        <label>Advisory Event</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Populated by trigger from related Meeting Budget G/L record.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expense_Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Registration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Registration</label>
        <referenceTo>Event_Registration__c</referenceTo>
        <relationshipLabel>Expense Authorizations</relationshipLabel>
        <relationshipName>Expense_Authorizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Flight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accommodations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other, non-travel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expense Authorization</label>
    <nameField>
        <label>Expense Authorization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Authorizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_ExpenseAuthTriggerHelper.cls
/**
 * 	@description	:	Test class for the ExpenseAuthTriggerHelper Class.
 * 
 * 	@Created By		:	Victor Hanson
 * 
 * 	@Change History	:	V1.0 - Created - 01/27/2015 - Victor Hanson - CR-20140520-5562
 * 
 **/
@isTest
public class Test_ExpenseAuthTriggerHelper {
	//returns a budget GL record
    public static Cost_Center__c createCostCenter(Id userId, boolean createAndInsert) {
        
        Cost_Center__c costCenter = new Cost_Center__c(Approver__c = userId,
                                                   Description__c = 'Test');
        if (createAndInsert) insert costCenter;
        return costCenter;
    }
    
    /**
     * @description: For the first record, set the Approver on the Budget G/L record, then update the Expense Auth record and verify that the Approver field there is updated as expected.
	 *				 For the second record, leave the Approver blank on the main Budget G/L.  Add a Budget G/L and Approver for a Parent Meeting. Then update the Expense Auth record and verify that the Approver field is updated as expected.
	 *				 For the third record, leave the Approver blank on the main Budget G/L.  Update the Expense Auth record and verify that the Approver field remains blank.
     **/
    static testMethod void test1() {
        
        //create a contact
        Contact con = TestUtilities.CreateNewContact(true);
        
        //create 3 budget G/L
        Cost_Center__c budgetGL_Approver = createCostCenter(userInfo.getUserId(), false);
        Cost_Center__c budgetGL_noApprover = createCostCenter(null, false);
        Cost_Center__c budgetGL3 = createCostCenter(null, false);
        list<Cost_Center__c> budgetGLs = new list<Cost_Center__c> { budgetGL_Approver, budgetGL_noApprover, budgetGL3 };
        insert budgetGLs;
        
        //create the master
        Advisory_Event__c meeting1 = TestUtilities.createEvent(Constants.RECORD_TYPE_ID_ADV_EVENT_SERIES, budgetGL_Approver.Id, false);
        Advisory_Event__c meeting2 = TestUtilities.createEvent(Constants.RECORD_TYPE_ID_ADV_EVENT_SERIES, budgetGL_noApprover.Id, false);
        list<Advisory_Event__c> meetings = new list<Advisory_Event__c> { meeting1, meeting2  };
        insert meetings;
        
        //insert child meeting
        Advisory_Event__c meeting2Child = TestUtilities.createEvent(Constants.RECORD_TYPE_ID_ADV_EVENT_SERIES, budgetGL_noApprover.Id, false);
        meeting2Child.Parent_Event__c = meeting2.Id;
        insert meeting2Child;
        
        //create registration
        Event_Registration__c reg1 = TestUtilities.createRegistration(meeting1.Id, con.Id, false);
        Event_Registration__c reg2Child = TestUtilities.createRegistration(meeting2Child.Id, con.Id, false);
        list<Event_Registration__c> registrations = new list<Event_Registration__c> { reg1, reg2Child };
        insert registrations;
        
        //create expense auth
        Expense_Authorization__c eAuth1 = new Expense_Authorization__c(Event_Registration__c = reg1.Id,
                                                                       Start_Date__c = system.today(),
                                                                       End_Date__c = system.today(),
                                                                       Amount__c = 123,
                                                                       Status__c = 'New',
                                                                       Type__c = 'Accomodations');
        Expense_Authorization__c eAuth2Child = new Expense_Authorization__c(Event_Registration__c = reg2Child.Id,
                                                                            Start_Date__c = system.today(),
                                                                            End_Date__c = system.today(),
                                                                            Amount__c = 123,
                                                                            Status__c = 'New',
                                                                            Type__c = 'Accomodations');
        list<Expense_Authorization__c> expenseAuths = new list<Expense_Authorization__c> { eAuth1, eAuth2Child };
        insert expenseAuths;
        
        //get the updated expense auth records
        expenseAuths = [SELECT Id, Approver__c FROM Expense_Authorization__c WHERE Id IN :expenseAuths];
        
        for (Expense_Authorization__c eAuth : expenseAuths) {
            if (eAuth.Id == eAuth1.Id) {
                system.assertEquals(budgetGL_Approver.Approver__c, eAuth.Approver__c);
            }
            
            else if (eAuth.Id == eAuth2Child.Id) {
                system.assertEquals(null, eAuth.Approver__c);
            }
        }
        
        //add an approver to the budget G/L related to the parent2 meeting
        budgetGL_noApprover.Approver__c = userInfo.getUserId();
        update budgetGL_noApprover;
        
        //now update the eAuth2Child
        update eAuth2Child;
        
        //verify the eAuth2Child record now has an approver due to the parent meeting's BudgetGL Approver being populated
        eAuth2Child = [SELECT Id, Approver__c FROM Expense_Authorization__c WHERE Id = :eAuth2Child.Id];
        system.assertEquals(userInfo.getUserId(), eAuth2Child.Approver__c);
    }
}