objects/Advisory_Idea__c.object
<CustomObject>
    <description>This is the object which will contain the Ideas for the Innovation Ideas Page</description>
    <fields>
        <fullName>Comments_Count__c</fullName>
        <label>Comments Count</label>
        <summaryForeignKey>Advisory_Idea_Comment__c.Advisory_Idea__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>High_Level_Description__c</fullName>
        <label>High Level Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <summarizedField>Advisory_Idea_Vote__c.Type_Value__c</summarizedField>
        <summaryForeignKey>Advisory_Idea_Vote__c.Advisory_Idea__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Advisory Idea</label>
    <nameField>
        <displayFormat>Idea-{0}</displayFormat>
        <label>Idea Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisory Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Advisory_Idea_Comment__c.object
<CustomObject>
    <description>This object tracks the comments associated with the Advisory Ideas listed on the Ideas Page.</description>
    <fields>
        <fullName>Advisory_Idea__c</fullName>
        <label>Advisory Idea</label>
        <referenceTo>Advisory_Idea__c</referenceTo>
        <relationshipLabel>Advisory Idea Comments</relationshipLabel>
        <relationshipName>Advisory_Idea_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commented_By__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Commented By</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Employee</value>
            </filterItems>
            <filterItems>
                <field>Contact.User_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Advisory Idea Comments</relationshipLabel>
        <relationshipName>Comment_Posted_By</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Advisory Idea Comment</label>
    <nameField>
        <displayFormat>Comm-{0}</displayFormat>
        <label>Advisory Idea Comment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisory Idea Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Advisory_Idea_Vote__c.object
<CustomObject>
    <description>The object tracks the voting scores of the Ideas from the Advisory Ideas Object</description>
    <fields>
        <fullName>Advisory_Idea__c</fullName>
        <label>Advisory Idea</label>
        <referenceTo>Advisory_Idea__c</referenceTo>
        <relationshipLabel>Advisory Idea Votes</relationshipLabel>
        <relationshipName>Advisory_Idea_Votes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Voted_By__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Voted By</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Employee</value>
            </filterItems>
            <filterItems>
                <field>Contact.User_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Advisory Idea Votes</relationshipLabel>
        <relationshipName>Vote_Casted_By</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Advisory Idea Vote</label>
    <nameField>
        <displayFormat>Vote-{0}</displayFormat>
        <label>Advisory Idea Vote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advisory Idea Votes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IdeaWrapper.cls
public class IdeaWrapper {
    public Advisory_Idea__c WrappedItem { get; set; }

    public Integer TotalComments { get; set;}
    public Integer TotalScore { get; set; }
    public boolean HasMyVote { get; set; }
    public boolean HasMyComment { get; set; }
    public String HighLevelDescription { get; set;}
    public String Title{ get; set;}

    public IdeaWrapper(Advisory_Idea__c item, Id currentContactId) {
        System.debug('##IdeaWrapper input: ' + item);
        WrappedItem = item;

        TotalComments = (Integer) item.Comments_Count__c;
        TotalScore = (Integer) item.Score__c;
        HighLevelDescription = item.High_Level_Description__c;
        Title = item.Title__c;

        HasMyVote = false;
        try{
            for (Advisory_Idea_Vote__c vote : item.Advisory_Idea_Votes__r) {
                if (vote.Voted_By__c == currentContactId) {
                    HasMyVote = true;
                    break;
                }
            }
        } catch(Exception ex) {
            List<Advisory_Idea_Vote__c> myVotes = [SELECT Id FROM Advisory_Idea_Vote__c
                                                  WHERE Advisory_Idea__c=:item.id AND Voted_By__c=:currentContactId];
            HasMyVote = myVotes.size() > 0;
        }

        HasMyComment = false;
        for (Advisory_Idea_Comment__c comment : item.Advisory_Idea_Comments__r) {
            if (comment.Commented_By__c == currentContactId) {
                HasMyComment = true;
                break;
            }
        }

        System.debug('##IdeaWrapper output: ' + this);
    }
}