objects/Condition__c.object
<CustomObject>
    <description>Each Individual Goal has limiting/defining factors. Those factors commonly include (among others):
•	Collection Perspectives
•	Dates
•	Staff Relationships
•	Assignment roles
This object holds those limiting/defining factors, both those that are inclusions and those that are exclusions.</description>
    <fields>
        <fullName>Standard_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Template</label>
        <referenceTo>Standard_Goal__c</referenceTo>
        <relationshipLabel>Conditions</relationshipLabel>
        <relationshipName>Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <recordTypes>
        <fullName>Institution</fullName>
        <active>true</active>
        <label>Institution</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Goal_Type__c.object
<CustomObject>
    <description>This object holds lookup values for defining goals. There are two types of values being identified:
1.	Users would create records differentiated (via the Description field) to identify the different types of goals. 
2.	Each record would indicate the type of data or process interaction with the transactions that would meet that goal; effectively, this answers the question, “Where do we tell the automation to find the transactions?</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Base_Process__c</fullName>
        <label>Base Process</label>
        <picklist>
            <picklistValues>
                <fullName>Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NBB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OAB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualitative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Goal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Goal Template</label>
        <type>Checkbox</type>
    </fields>
    <label>Goal Type</label>
    <nameField>
        <label>Goal Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Personal_Goal__c.object
<CustomObject>
    <description>Personal Goals represent the individual targets that each Payee must achieve. Some targets are simply a reframing of another target. For example, the “Career Committee Grade” Personal Goal may simply represent a first half/second half interpretation of the normal “Incentive” Personal Goal (which is itself quarterly).</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Type</label>
        <referenceTo>Goal_Type__c</referenceTo>
        <relationshipLabel>Personal Goals</relationshipLabel>
        <relationshipName>Personal_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period_End__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Start__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Template</label>
        <referenceTo>Standard_Goal__c</referenceTo>
        <relationshipLabel>Personal Goals</relationshipLabel>
        <relationshipName>Personal_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Personal Goal</label>
    <nameField>
        <label>Personal Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Goals</pluralLabel>
    <recordTypes>
        <fullName>Personal_Goal</fullName>
        <active>true</active>
        <description>Will be connected to exactly one Proposed Goal</description>
        <label>Goal Snapshot</label>
    </recordTypes>
    <recordTypes>
        <fullName>Proposal</fullName>
        <active>true</active>
        <description>Every record starts here</description>
        <label>Proposed Goal</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Personal_Plan__c.object
<CustomObject>
    <description>This is the organizing/summarizing object that incorporates Personal Goals. The determination as to when a given Payee may have overlapping or simultaneously active Personal Plans ultimately is a decision made by a member of the Incentives Team. As a result, there are no controls in place to identify or prevent duplicate Personal Plans. 
If an Personal Plan represents the next iteration of a prior Personal Plan, the latest revision will identify the Personal Plan whose place is being taken.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Personal Plan</label>
    <nameField>
        <label>Personal Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Perspective__c.object
<CustomObject>
    <description>This object holds the Perspective definitions.
Within the context of a Program Collection, given consumers may interpret the contents of that Program Collection differently: what one consumer takes as a collection of five Programs, for example, another may interpret as having only three Programs. Since both consumers will use the same terminology to describe the collection, the Perspective allows for a differentiation of the definition of that Program Collection by the intended use or consumer.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Drives availability for selection in Program Relationship only</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Perspectives</relationshipLabel>
        <relationshipName>Group_Purposes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Perspective</label>
    <nameField>
        <label>Perspective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Perspectives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Program_Group__c.object
<CustomObject>
    <description>This object holds the Program Collection definitions.Program Collections are organizing records for broadly recognized collections of Programs. This is an augmentation to the extant concepts of a “Program hierarchy” based on the attributes (Market, Business Line, Vertical, Reporting Group) of specific Programs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Drives availability for selection in Program Relationship only</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Collections</relationshipLabel>
        <relationshipName>Program_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Collection</label>
    <nameField>
        <label>Program Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Collections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Program_Perspective__c.object
<CustomObject>
    <description>This object holds the unique association of a Program Collection and a Perspective. 
When establishing a relationship between a Program or Program Collection and any other Program Collection, that relationship must be typified by a Perspective. Rather than require users to identify both the Perspective and Program Collectionwith each association, the association is instead drawn between the child record (Program or Program Collection) and the Collection Perspective, which encapsulates the unique collection for a particular consumption purpose.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Drives availability for selection in Program Relationship only</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Collection Perspectives</relationshipLabel>
        <relationshipName>Program_Perspectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Collection Perspective</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Perspectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Standard_Goal__c.object
<CustomObject>
    <description>This object holds the primary metadata relating the Enterprise Goals to their respective details and intended Payees.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Goal Templates (Business Owner)</relationshipLabel>
        <relationshipName>Master_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Template Type</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Goal Type you have selected is inactive.</errorMessage>
            <filterItems>
                <field>Goal_Type__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Goal_Type__c.Standard_Goal__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Goal_Type__c</referenceTo>
        <relationshipLabel>Goal Templates</relationshipLabel>
        <relationshipName>Standard_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period_End__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Start__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <label>Goal Template</label>
    <nameField>
        <label>Goal Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Templates</pluralLabel>
    <recordTypes>
        <fullName>NBB</fullName>
        <active>true</active>
        <label>NBB</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Standard_Goal_Detail__c.object
<CustomObject>
    <description>This object holds the specifics of a Goal Template. Each Goal Template will have multiple Detail records. These records are templates for application to individuals, and if used to create any Personal Goals, those will relate back to this record for easy identification and review.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used in lookups only</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Goal_Type__c.Standard_Goal__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Goal_Type__c</referenceTo>
        <relationshipLabel>Goal Template Details</relationshipLabel>
        <relationshipName>Master_Goal_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period_End__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Start__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Goal__c</fullName>
        <label>Goal Template</label>
        <referenceTo>Standard_Goal__c</referenceTo>
        <relationshipLabel>Goal Template Details</relationshipLabel>
        <relationshipName>Standard_Goal_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Goal Template Detail</label>
    <nameField>
        <label>Goal Template Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Template Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_Trigger_PersonalGoal.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData = false)
private class Test_Trigger_PersonalGoal {
  /**
    *   Purpose         :   Test class for Trigger_PersonalGoal
    *            
    *   Create By       :   Padmesh Soni
    *
    *   Created Date    :   08/18/2015
    *
    *   Revision Log    :   V_1.0 - Created - CR-20150729-9114 
    * 						V_2.0 - Modified By - Rajeev Jain - 1/13/2016 -  ISSP Deployment C Release QA changes.
    * 						Commented out validatesPersonalGoal(myUnitTest test method) , since its no longer needed.    
    * 
    *   Coverage        :   V_1.0 - 97%
    **/
  
    //Setup test data from class
    @testSetup static void setupTestDataForClass() {
        
        //Create an institution
        Account account = TestUtilities.CreateNewAccount(false);
        
        //Insert
        insert account;
        
        //Create a Contact
        Contact contact = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'test@test.com', AccountId = account.Id,
                                      Employee_User_Record__c = Userinfo.getUserId());
        
        //Insert
        insert contact;
    
        //Create Goal Types
        List<Goal_Type__c> goalTypes = new List<Goal_Type__c>();
        
        //Add new goal type in list
        goalTypes.add(new Goal_Type__c(Name = 'TestGoalType1', Active__c = true, Standard_Goal__c = true, Base_Process__c = 'NBB', Description__c = 'Testing of Goal Type'));
        goalTypes.add(new Goal_Type__c(Name = 'TestGoalType2', Active__c = true, Standard_Goal__c = true, Base_Process__c = 'CM', Description__c = 'Testing of Goal Types'));
        goalTypes.add(new Goal_Type__c(Name = 'TestGoalType3', Active__c = false, Standard_Goal__c = true, Base_Process__c = 'Activity', Description__c = 'Testing of Goal'));
        goalTypes.add(new Goal_Type__c(Name = 'TestGoalType4', Active__c = false, Standard_Goal__c = true, Base_Process__c = 'Renewal', Description__c = 'Goal Type'));
        
        //Insert 
        insert goalTypes;

        //Create Standard Goals
        List<Standard_Goal__c> standardGoals = new List<Standard_Goal__c>();
        
        //Add new Standard Goals in list
        standardGoals.add(new Standard_Goal__c(Name = 'StandardGoal1', Active__c = true, Amount__c = 100, Business_Owner__c = contact.Id,
                                               Description__c = 'Testing of Standard Goal', Goal_Type__c = goalTypes[0].Id, 
                                               Period_Start__c = System.today(), Period_End__c = System.today().addDays(4)));
        standardGoals.add(new Standard_Goal__c(Name = 'StandardGoal2', Active__c = true, Amount__c = 200, Business_Owner__c = contact.Id,
                                               Description__c = 'Testing of Standard Goal', Goal_Type__c = goalTypes[1].Id,
                                               Period_Start__c = System.today().addDays(10), Period_End__c = System.today().addDays(20)));
        standardGoals.add(new Standard_Goal__c(Name = 'StandardGoal3', Active__c = false, Amount__c = 300, Business_Owner__c = contact.Id,
                                               Description__c = 'Testing of Standard Goal', Goal_Type__c = goalTypes[1].Id,
                                               Period_Start__c = System.today().addDays(25), Period_End__c = System.today().addDays(30)));
        
        //Insert 
        insert standardGoals;
                               
        //Create Standard Goal Details
        List<Standard_Goal_Detail__c> standardGoalDetails = new List<Standard_Goal_Detail__c>();
        
        //Add new Standard Goal Details in list
        standardGoalDetails.add(new Standard_Goal_Detail__c(Name = 'StandardGoalDetail1', Active__c = true, Description__c = 'Testing',Target_Type__c = 'Paced',
                                                            Standard_Goal__c = standardGoals[0].Id));
        standardGoalDetails.add(new Standard_Goal_Detail__c(Name = 'StandardGoalDetail2', Active__c = true, Description__c = 'Testing',Target_Type__c = 'Paced',
                                                            Standard_Goal__c = standardGoals[0].Id));
        standardGoalDetails.add(new Standard_Goal_Detail__c(Name = 'StandardGoalDetail3', Active__c = true, Description__c = 'Testing',Target_Type__c = 'Paced',
                                                            Standard_Goal__c = standardGoals[1].Id));
        standardGoalDetails.add(new Standard_Goal_Detail__c(Name = 'StandardGoalDetail4', Active__c = true, Description__c = 'Testing',Target_Type__c = 'Paced',
                                                            Standard_Goal__c = standardGoals[1].Id));
        standardGoalDetails.add(new Standard_Goal_Detail__c(Name = 'StandardGoalDetail5', Active__c = true, Description__c = 'Testing',Target_Type__c = 'Paced',
                                                            Standard_Goal__c = standardGoals[2].Id));
        
        //Insert 
        insert standardGoalDetails;
        
        //Create Personal Plan
        List<Personal_Plan__c> personalPlans = new List<Personal_Plan__c>();
        
        //Add new Personal Plan in list
        personalPlans.add(new Personal_Plan__c(Name = 'PersonalPlan1', Active__c = true, Description__c = 'Testing', Staff_Member__c = contact.Id,
                                              Plan_Start__c = System.today().addDays(1), Plan_End__c = System.today().addDays(10)));
        personalPlans.add(new Personal_Plan__c(Name = 'PersonalPlan2', Active__c = true, Description__c = 'Testing', Staff_Member__c = contact.Id,
                                              Plan_Start__c = System.today().addDays(12), Plan_End__c = System.today().addDays(18)));
        personalPlans.add(new Personal_Plan__c(Name = 'PersonalPlan3', Active__c = true, Description__c = 'Testing', Staff_Member__c = contact.Id,
                                              Plan_Start__c = System.today().addDays(20),  Plan_End__c = System.today().addDays(25)));
        
        //Insert
        insert personalPlans;
    
    }
    
    //Test method for validatesPersonalGoal method
    /*static testMethod void myUnitTest() {
        
        //List of Goal Type
        List<Goal_Type__c> goalTypes = [Select Id From Goal_Type__c];
       
        //List of Personal Plan
        List<Personal_Plan__c> personalPlans = [Select Id From Personal_Plan__c];
        
        //List of Stanndard Goal Detail
        List<Standard_Goal_Detail__c> fetchSGDs = [Select Id From Standard_Goal_Detail__c];
        
        //List of record type
        List<RecordType> recordTypes = [select Id, DeveloperName From RecordType Where SObjectType = 'Personal_Goal__c' 
                                        AND DeveloperName IN ('Personal_Goal', 'Proposal') ORDER BY DeveloperName ASC LIMIT 2];
        
        //Create Personal Goal
        List<Personal_Goal__c> personalGoals = new List<Personal_Goal__c>();
        
        //Add new Personal Goal in list
        personalGoals.add(new Personal_Goal__c(Name = 'PersonalGoal1', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[0].Id,
                                               Personal_Plan__c = personalPlans[0].Id, Description__c = 'Testing', Amount__c = 100, Standard_Goal_Detail__c = fetchSGDs[0].Id,
                                               Period_Start__c = System.today().addDays(1), Period_End__c = System.today().addDays(10)));
        //Add new Personal Goal in list
        personalGoals.add(new Personal_Goal__c(Name = 'PersonalGoal2', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[0].Id,
                                               Personal_Plan__c = personalPlans[0].Id, Description__c = 'Testing', Amount__c = 100, Standard_Goal_Detail__c = fetchSGDs[0].Id,
                                               Period_Start__c = System.today().addDays(12), Period_End__c = System.today().addDays(20)));
        //Add new Personal Goal in list
        personalGoals.add(new Personal_Goal__c(Name = 'PersonalGoal3', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[0].Id,
                                               Personal_Plan__c = personalPlans[0].Id, Description__c = 'Testing', Amount__c = 100, Standard_Goal_Detail__c = fetchSGDs[0].Id,
                                               Period_Start__c = System.today().addDays(21), Period_End__c = System.today().addDays(40)));
        
        //Start testing from here
        Test.startTest();
        
        //Try to insert record that will throw an exception that will cover in catch part
        try {    
            
            //Insert
            insert personalGoals;
            
            //Assert for Result
            //System.assert(false);
        }
        
        //Catch block to handle exception
        catch(Exception ex) {
        
            //Assert for Result
            System.assert(ex.getMessage().contains(Label.ERROR_CONTINUOUS_PG));
        }
 
        personalGoals[1].Period_Start__c = System.today().addDays(5);
 
        //Try to insert record that will throw an exception that will cover in catch part
        try {    
            
            //Insert 
            insert personalGoals;
            
            //Assert for Result
            System.assert(false);
        }
        
        //Catch block to handle exception
        catch(Exception ex) {
        
            //Assert for Result
            System.assert(ex.getMessage().contains(Label.ERROR_UNIQUENESS_PG));
        }
        
        //Update Personal Goal record with start date and insert
        personalGoals[1].Period_Start__c = System.today().addDays(11);
        
        //Insert
        insert personalGoals;
        
        //Update Personal Goal record with start date and insert
        personalGoals[2].Period_Start__c = System.today().addDays(25);
        
        //Try to update record that will throw an exception that will cover in catch part
        try {    
        
            //Update
            update personalGoals[2];

            //Assert for Result
            System.assert(false);
        }
        
        //Catch block to handle exception
        catch(Exception ex) {
        
            //Assert for Result
            System.assert(ex.getMessage().contains(Label.ERROR_CONTINUOUS_PG));
        }

        //Update SGDP record with start date and insert
        personalGoals[2].Period_Start__c = System.today().addDays(18);
        
        //Try to update record that will throw an exception that will cover in catch part
        try {    
        
            //Update
            update personalGoals[2];

            //Assert for Result
            System.assert(false);
        }
        
        //Catch block to handle exception
        catch(Exception ex) {
        
            //Assert for Result
            System.assert(ex.getMessage().contains(Label.ERROR_UNIQUENESS_PG));
        }
        
        
        //Update Personal Goal record with start date and insert
        personalGoals[2].Period_Start__c = System.today().addDays(21);
        
        //Update
        update personalGoals[2];
        
        //Create New Personal Goal
        List<Personal_Goal__c> personalGoalsNew = new List<Personal_Goal__c>();
        
        //Add new Personal Goal in list
        personalGoalsNew.add(new Personal_Goal__c(Name = 'PersonalGoal1', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[0].Id,
                                               Personal_Plan__c = personalPlans[1].Id, Description__c = 'Testing', Amount__c = 100,
                                               Period_Start__c = System.today().addDays(1), Period_End__c = System.today().addDays(10)));
        //Add new Personal Goal in list
        personalGoalsNew.add(new Personal_Goal__c(Name = 'PersonalGoal2', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[0].Id,
                                               Personal_Plan__c = personalPlans[1].Id, Description__c = 'Testing', Amount__c = 100,
                                               Period_Start__c = System.today().addDays(11), Period_End__c = System.today().addDays(20)));
        
        //Insert
        insert personalGoalsNew;
        
        List<Personal_Goal__c> pGList = new List<Personal_Goal__c>();
        
        //Add new Personal Goal in list
        pGList.add(new Personal_Goal__c(Name = 'PersonalGoal3', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[0].Id,
                                               Personal_Plan__c = personalPlans[0].Id, Description__c = 'Testing', Amount__c = 100, Standard_Goal_Detail__c = fetchSGDs[0].Id,
                                               Period_Start__c = System.today().addDays(41), Period_End__c = System.today().addDays(50)));
        insert pGList;
        
        pGList[0].Period_Start__c = System.today().addDays(42);
        
        //Try to update record that will throw an exception that will cover in catch part
        try {    
            
            //Update 
            update pGList;
            
            //Assert for Result
            System.assert(false);
        }
        
        //Catch block to handle exception
        catch(Exception ex) {
        
            //Assert for Result
            System.assert(ex.getMessage().contains(Label.ERROR_CONTINUOUS_PG));
        }
        
        
        //Stop Testing here
        Test.stopTest();
    }*/
    
    //Test method for createProposalGoal method
    static testMethod void myUnitTest1() {
        
        //List of Goal Type
        List<Goal_Type__c> goalTypes = [Select Id From Goal_Type__c];
           
        //List of Personal Plan
        List<Personal_Plan__c> personalPlans = [Select Id From Personal_Plan__c];
           
        //List of record type
        List<RecordType> recordTypes = [select Id, DeveloperName From RecordType Where SObjectType = 'Personal_Goal__c' 
                                            AND DeveloperName IN ('Personal_Goal', 'Proposal') ORDER BY DeveloperName ASC LIMIT 2];
            
        //Create Personal Goal
        List<Personal_Goal__c> personalGoals = new List<Personal_Goal__c>();
            
        //Add new Personal Goal in list
        personalGoals.add(new Personal_Goal__c(Name = 'PersonalGoal1', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[0].Id,
                                                   Personal_Plan__c = personalPlans[0].Id, Description__c = 'Testing', Amount__c = 100, 
                                                   Period_Start__c = System.today().addDays(1), Period_End__c = System.today().addDays(10)));
        //Add new Personal Goal in list
        personalGoals.add(new Personal_Goal__c(Name = 'PersonalGoal2', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[0].Id,
                                                   Personal_Plan__c = personalPlans[0].Id, Description__c = 'Testing', Amount__c = 100,
                                                   Period_Start__c = System.today().addDays(11), Period_End__c = System.today().addDays(20)));
        //Add new Personal Goal in list
        personalGoals.add(new Personal_Goal__c(Name = 'PersonalGoal3', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[1].Id,
                                               Personal_Plan__c = personalPlans[0].Id, Description__c = 'Testing', Amount__c = 100,
                                               Period_Start__c = System.today().addDays(21), Period_End__c = System.today().addDays(40)));
        
        //Start testing from here
        Test.startTest();
        
        //Insert
        insert personalGoals;
        
        //Query Through Personal Goal
        List<Personal_Goal__c> pGCount = [Select Id From Personal_Goal__c];
        
        //Assert for Result
        System.assertEquals(5, pGCount.size());
        
        //Stop Testing here
        Test.stopTest();
        
    }
    
    //Test method for createConditionsForPG method
    static testMethod void testcreateConditionsForPG(){
        
        //List of Goal Type
        List<Goal_Type__c> goalTypes = [Select Id From Goal_Type__c];
        
        //List of Standard Goal
        List<Standard_Goal__c> standardGoals = [Select Id From Standard_Goal__c];
        
        //List of Standard Goal Detail
        List<Standard_Goal_Detail__c> standardGoalDetails = [Select Id From Standard_Goal_Detail__c];
       
        //List of record type
        List<RecordType> recordTypes = [select Id, DeveloperName From RecordType Where SObjectType = 'Personal_Goal__c' 
                                        AND DeveloperName IN ('Personal_Goal', 'Proposal') ORDER BY DeveloperName ASC LIMIT 2];

        //Create Perspective 
        List<Perspective__c> perspectives = new List<Perspective__c>();
        
        //Add new recrods in list 
        perspectives.add(new Perspective__c(Name = 'Perspective 1'));
        perspectives.add(new Perspective__c(Name = 'Perspective 2'));
        
        //Insert
        insert perspectives;
        
        //Create Program Collection
        List<Program_Group__c> programCollections = new List<Program_Group__c>();
        
        //Add new recrods in list 
        programCollections.add(new Program_Group__c(Name = 'PC 1'));
        programCollections.add(new Program_Group__c(Name = 'PC 2'));
        
        //Insert
        insert programCollections;
        
        // Create program Perspective
        List<Program_Perspective__c> programPerspectives = new List<Program_Perspective__c>();
        
        //Add new recrods in list 
        programPerspectives.add(new Program_Perspective__c(Name = 'pp1' , Active__c = true,Perspective__c = perspectives[0].Id, Program_Group__c = programCollections[0].Id ));
        programPerspectives.add(new Program_Perspective__c(Name = 'pp2' , Active__c = true,Perspective__c = perspectives[1].Id, Program_Group__c = programCollections[1].Id));
        
        //Insert Program Pespective
        insert programPerspectives;
                
        //List of Condition                             
        List<Condition__c> conditions = new List<Condition__c>();
        
        conditions.add(new Condition__c(Name = 'condition1', Standard_Goal__c = standardGoals[0].Id, Collection_Perspective__c = programPerspectives[0].Id, Condition_Type__c = 'Exclude'));
        conditions.add(new Condition__c(Name = 'condition2', Standard_Goal__c = standardGoals[0].Id, Collection_Perspective__c = programPerspectives[0].Id, Condition_Type__c = 'Exclude'));
        conditions.add(new Condition__c(Name = 'condition3', Standard_Goal__c = standardGoals[1].Id, Collection_Perspective__c = programPerspectives[1].Id, Condition_Type__c = 'Exclude'));
        conditions.add(new Condition__c(Name = 'condition4', Standard_Goal__c = standardGoals[0].Id, Standard_Goal_Detail__c = standardGoalDetails[0].Id, Collection_Perspective__c = programPerspectives[0].Id, Condition_Type__c = 'Exclude'));
        conditions.add(new Condition__c(Name = 'condition5', Standard_Goal__c = standardGoals[2].Id, Standard_Goal_Detail__c = standardGoalDetails[0].Id, Collection_Perspective__c = programPerspectives[1].Id, Condition_Type__c = 'Exclude'));
        
        //Insert 
        insert conditions;
        
        //Create Personal Goal
        List<Personal_Goal__c> personalGoals = new List<Personal_Goal__c>();
        
        //Add new Personal Goal in list
        personalGoals.add(new Personal_Goal__c(Name = 'PersonalGoal1', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[0].Id,
                                               Standard_Goal__c = standardGoals[0].Id, Standard_Goal_Detail__c = standardGoalDetails[0].Id, Description__c = 'Testing', Amount__c = 100, 
                                               Period_Start__c = System.today().addDays(1), Period_End__c = System.today().addDays(10)));
        //Add new Personal Goal in list
        personalGoals.add(new Personal_Goal__c(Name = 'PersonalGoal2', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[0].Id,
                                               Standard_Goal__c = standardGoals[1].Id, Standard_Goal_Detail__c = standardGoalDetails[1].Id, Description__c = 'Testing', Amount__c = 100,
                                               Period_Start__c = System.today().addDays(12), Period_End__c = System.today().addDays(20)));
        //Add new Personal Goal in list
        personalGoals.add(new Personal_Goal__c(Name = 'PersonalGoal3', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[1].Id,
                                               Standard_Goal__c = standardGoals[2].Id, Standard_Goal_Detail__c = standardGoalDetails[2].Id, Description__c = 'Testing', Amount__c = 100,
                                               Period_Start__c = System.today().addDays(21), Period_End__c = System.today().addDays(40)));
        
        //Create Personal Goal
        List<Personal_Goal__c> pGWithPrGList = new List<Personal_Goal__c>();
        
        //Start testing from here
        Test.startTest();

        //Insert
        insert personalGoals;
        /*
        //Add new Personal Goal in list
        pGWithPrGList.add(new Personal_Goal__c(Name = 'PersonalGoal1', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[1].Id,
                                               Primary_Goal__c = personalGoals[0].Id, Description__c = 'Testing', Amount__c = 100, 
                                               Period_Start__c = System.today().addDays(1), Period_End__c = System.today().addDays(10)));
        //Add new Personal Goal in list
        pGWithPrGList.add(new Personal_Goal__c(Name = 'PersonalGoal2', Goal_Type__c = goalTypes[0].Id, Active__c = true, RecordTypeId = recordTypes[1].Id,
                                               Primary_Goal__c = personalGoals[1].Id, Description__c = 'Testing', Amount__c = 100,
                                               Period_Start__c = System.today().addDays(12), Period_End__c = System.today().addDays(20)));
        
        //Query through Condition
        List<Condition__c> conditionsList = [Select Id, Personal_Goal__c From Condition__c Where Personal_Goal__c IN : personalGoals];
        
        //Assert for result
        System.assertEquals(5,conditionsList.size());
        
        //Update personal goal
        personalGoals[0].Name = 'testing1';
        
        //Update
        update personalGoals;
        
        //Query Through Condition
        List<Condition__c> conditionsL = [Select Id, Personal_Goal__c From Condition__c Where Personal_Goal__c IN : personalGoals];
        
        //Assert for result
        System.assertEquals(5, conditionsL.size());
        
        //Insert
        insert pGWithPrGList; 
        
        //Query through Condition
        List<Condition__c> conditionRecords = [Select Id, Personal_Goal__c From Condition__c Where Personal_Goal__c IN : pGWithPrGList];
        
        //Assert for result
        System.assertEquals(5,conditionRecords.size());
        */
        //Stop testing from here
        Test.stopTest();
    }
    
    //Test method for activateProposals method
    static testMethod void myUnitTest2() {

        //List of Standard Goal
        List<Standard_Goal__c> standardGoals = [Select Id From Standard_Goal__c];

        //List of Standard Goal Detail
        List<Standard_Goal_Detail__c> standardGoalDetails = [Select Id From Standard_Goal_Detail__c];

        //Create Perspective 
        List<Perspective__c> perspectives = new List<Perspective__c>();

        //Add new recrods in list 
        perspectives.add(new Perspective__c(Name = 'Perspective 1'));
        perspectives.add(new Perspective__c(Name = 'Perspective 2'));

        //Insert
        insert perspectives;

        //Create Program Collection
        List<Program_Group__c> programCollections = new List<Program_Group__c>();

        //Add new recrods in list 
        programCollections.add(new Program_Group__c(Name = 'PC 1'));
        programCollections.add(new Program_Group__c(Name = 'PC 2'));

        //Insert
        insert programCollections;

        // Create program Perspective
        List<Program_Perspective__c> programPerspectives = new List<Program_Perspective__c>();

        //Add new recrods in list 
        programPerspectives.add(new Program_Perspective__c(Name = 'pp1' , Active__c = true,Perspective__c = perspectives[0].Id, Program_Group__c = programCollections[0].Id ));
        programPerspectives.add(new Program_Perspective__c(Name = 'pp2' , Active__c = true,Perspective__c = perspectives[1].Id, Program_Group__c = programCollections[1].Id));

        //Insert Program Pespective
        insert programPerspectives;
        
        //List of Goal Type
        List<Goal_Type__c> goalTypes = [Select Id From Goal_Type__c];
           
        //List of Personal Plan
        List<Personal_Plan__c> personalPlans = [Select Id From Personal_Plan__c];
           
        //List of record type
        List<RecordType> recordTypes = [Select Id, DeveloperName From RecordType Where SObjectType = 'Personal_Goal__c' 
                                            AND DeveloperName IN ('Personal_Goal', 'Proposal') ORDER BY DeveloperName ASC LIMIT 2];
            
        //Create Personal Goal
        List<Personal_Goal__c> personalGoals = new List<Personal_Goal__c>();
            
        //Add new Personal Goal in list
        personalGoals.add(new Personal_Goal__c(Name = 'PersonalGoal1', Active__c = true, Goal_Type__c = goalTypes[0].Id, RecordTypeId = recordTypes[0].Id,
                                               Standard_Goal__c = standardGoals[0].Id, Description__c = 'Testing', Amount__c = 100,  
                                               Period_Start__c = System.today().addDays(1), Period_End__c = System.today().addDays(10)));
        
        //Insert
        insert personalGoals;
        
        //Create Personal Goal
        List<Personal_Goal__c> pGwithProposals = new List<Personal_Goal__c>();
        
        
        //Add new Personal Goal in list
        pGwithProposals.add(new Personal_Goal__c(Name = 'PersonalGoal2', Active__c = true, Goal_Type__c = goalTypes[0].Id, RecordTypeId = recordTypes[1].Id,
                                                 Primary_Goal__c = personalGoals[0].Id,  Description__c = 'Testing', Amount__c = 10011, 
                                                 Period_Start__c = System.today().addDays(11), Period_End__c = System.today().addDays(20)));
        
        //Add new Personal Goal in list
        pGwithProposals.add(new Personal_Goal__c(Name = 'PersonalGoal3',  Active__c = true, Goal_Type__c = goalTypes[0].Id, RecordTypeId = recordTypes[1].Id,
                                                 Primary_Goal__c = personalGoals[0].Id,  Description__c = 'Testing', Amount__c = 10012, 
                                                 Period_Start__c = System.today().addDays(11), Period_End__c = System.today().addDays(20)));
        
        //Insert 
        insert pGwithProposals;

        List<Personal_Goal__c> tests = [Select Id from Personal_Goal__c];
        System.assertEquals(4, tests.size());
        
        //List of Condition                             
        List<Condition__c> conditions = new List<Condition__c>();

        conditions.add(new Condition__c(Name = 'condition1', Personal_Goal__c = pGwithProposals[0].Id, Collection_Perspective__c = programPerspectives[1].Id, Condition_Type__c = 'Exclude'));
        conditions.add(new Condition__c(Name = 'condition2', Personal_Goal__c = pGwithProposals[0].Id, Collection_Perspective__c = programPerspectives[0].Id, Condition_Type__c = 'Include'));
        conditions.add(new Condition__c(Name = 'condition3', Personal_Goal__c = pGwithProposals[1].Id, Collection_Perspective__c = programPerspectives[0].Id, Condition_Type__c = 'Exclude'));
        conditions.add(new Condition__c(Name = 'condition4', Personal_Goal__c = pGwithProposals[1].Id, Collection_Perspective__c = programPerspectives[1].Id, Condition_Type__c = 'Include'));
        conditions.add(new Condition__c(Name = 'condition5', Personal_Goal__c = personalGoals[0].Id, Collection_Perspective__c = programPerspectives[0].Id, Condition_Type__c = 'Exclude'));
        
        //Insert  
        insert conditions;

        //Start testing from here
        Test.startTest();
        
        //Update Proposals Active field to true (Old = false)
        pGwithProposals[1].Active__c = true;
        
        //Update
        update pGwithProposals;

        //Query Through Personal Goal
        List<Personal_Goal__c> pG = [Select Id, Primary_Goal__c, Active_Proposal__c, Active__c From Personal_Goal__c order by CreatedDate];

        //Assert For Result
        System.assertEquals(personalGoals[0].Id, pG[1].Primary_Goal__c);
        System.assertEquals(personalGoals[0].Id, pG[2].Primary_Goal__c);
        System.assertEquals(true, pG[1].Active__c);
        
        //Query through Condition
        List<Condition__c> conditionRecords = [Select Id, Personal_Goal__c, Name From Condition__c Where Personal_Goal__c IN : pGwithProposals];
        
        System.assertEquals(4 , conditionRecords.size());
        
        //
        PersonalGoalTriggerHelper.executeActiveProposals = true;
        
        //Update Proposals Active field to true (Old = false)
        pGwithProposals[0].Active__c = true;
        
        //Update
        update pGwithProposals;
        
        //Query Through Personal Goals
        List<Personal_Goal__c> pGs = [Select Id, Primary_Goal__c, Active_Proposal__c, Active__c From Personal_Goal__c order by CreatedDate];
                
        //Query through Condition for Proposals type
        List<Condition__c> conditionss = [Select Id, Personal_Goal__c, Name From Condition__c Where Personal_Goal__c IN : pGwithProposals];
        
        //Query through Condition for Personal Goal Type
        List<Condition__c> conditionPG = [Select Id, Personal_Goal__c, Name From Condition__c Where Personal_Goal__c IN : personalGoals];
        
        //Assert for results
        System.assertEquals(personalGoals[0].Id, pGs[1].Primary_Goal__c);
        System.assertEquals(personalGoals[0].Id, pGs[2].Primary_Goal__c);
        System.assertEquals(4 , conditionss.size());
        System.assertEquals(1 , conditionPG.size());
        
        //Set flag value
        PersonalGoalTriggerHelper.executeActiveProposals = true;
        
        //Set proposal goal to true
        pGwithProposals[0].Active__c = true;
        pGwithProposals[1].Active__c = true;
        
        //Update
        update pGwithProposals;
        
        
        //Query to fetch record type for personal goal record type
        List<Personal_Goal__c> personalRT = [Select Id, Name, Amount__c , Period_Start__c, Period_End__c, Active_Proposal__c, RecordTypeId From Personal_Goal__c Where RecordTypeId =: recordTypes[0].Id];
        
        //Assert for result
        System.assertEquals(1 , personalRT.size());
        
        //Query to fetch record type for personal goal record type
        List<Personal_Goal__c> personalRTss = [Select Id, Name, Amount__c , Active__c, Period_Start__c, Period_End__c, Active_Proposal__c, RecordTypeId From Personal_Goal__c Where RecordTypeId =: recordTypes[1].Id];
        
        System.debug('personalRTss:::::' + personalRTss);
        System.debug('pGwithProposals' +personalRTss[0].Active__c);
        System.debug('pGwithProposals::' +personalRTss[0].RecordTypeId); 
        
        //Assign Active Proposal to proposal goal 
        personalRT[0].Active_Proposal__c = pGwithProposals[0].Id;
        
        //Set flag value
        PersonalGoalTriggerHelper.executeActiveProposals = true;
        
        //update personal goal
        update personalRT;
        
        //Query to fetch record type for personal goal record type
        List<Personal_Goal__c> personalRTs = [Select Id, Name, Amount__c , Period_Start__c, Period_End__c, Active_Proposal__c, RecordTypeId From Personal_Goal__c Where RecordTypeId =: recordTypes[0].Id];
        
        //System.debug('personalRTpersonalRT ::::'  + personalRT);
    
        System.assertEquals(personalRTs[0].Amount__c, pGwithProposals[0].Amount__c);
        System.assertEquals(personalRTs[0].Period_Start__c, pGwithProposals[0].Period_Start__c);
        System.assertEquals(personalRTs[0].Period_End__c, pGwithProposals[0].Period_End__c);
                
        //Update Proposals Active field to false
        pGwithProposals[0].Active__c = false;
        pGwithProposals[1].Active__c = false;
        
        //Update proposal goal
        update pGwithProposals;
        
        //Update Proposals Active field to true (Old = false)
        pGwithProposals[0].Active__c = true;
        pGwithProposals[1].Active__c = true;
                
        //Update proposal goal
        update pGwithProposals;
                
        //System.assertEquals(personalGoals[0].Id, pGs[1].Primary_Goal__c);
    
        //System.assertEquals();
        
        //Stop testing from here
        Test.stopTest();
        
    }   
}