objects/Condition__c.object
<CustomObject>
    <description>Each Individual Goal has limiting/defining factors. Those factors commonly include (among others):
•	Collection Perspectives
•	Dates
•	Staff Relationships
•	Assignment roles
This object holds those limiting/defining factors, both those that are inclusions and those that are exclusions.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Goal_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Template Detail</label>
        <referenceTo>Standard_Goal_Detail__c</referenceTo>
        <relationshipLabel>Conditions</relationshipLabel>
        <relationshipName>Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Template</label>
        <referenceTo>Standard_Goal__c</referenceTo>
        <relationshipLabel>Conditions</relationshipLabel>
        <relationshipName>Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Condition</label>
    <nameField>
        <label>Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Goal_Template_Detail_Measurement_Period__c.object
<CustomObject>
    <fields>
        <fullName>Goal_Template_Detail__c</fullName>
        <label>Goal Template Detail</label>
        <referenceTo>Standard_Goal_Detail__c</referenceTo>
        <relationshipLabel>Goal Template Detail Measurement Periods</relationshipLabel>
        <relationshipName>Goal_Template_Detail_Measurement_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Measurement_Date__c</fullName>
        <label>Measurement Date</label>
        <type>Date</type>
    </fields>
    <label>Goal Template Detail Measurement Period</label>
    <nameField>
        <label>Goal Template Detail Measurement Periods</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Template Detail Measurement Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Goal_Type__c.object
<CustomObject>
    <description>This object holds lookup values for defining goals. There are two types of values being identified:
1.	Users would create records differentiated (via the Description field) to identify the different types of goals. 
2.	Each record would indicate the type of data or process interaction with the transactions that would meet that goal; effectively, this answers the question, “Where do we tell the automation to find the transactions?</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Base_Process__c</fullName>
        <label>Base Process</label>
        <picklist>
            <picklistValues>
                <fullName>Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NBB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OAB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualitative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Goal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Goal Template</label>
        <type>Checkbox</type>
    </fields>
    <label>Goal Type</label>
    <nameField>
        <label>Goal Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Standard_Goal__c.object
<CustomObject>
    <description>This object holds the primary metadata relating the Enterprise Goals to their respective details and intended Payees.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Goal Templates (Business Owner)</relationshipLabel>
        <relationshipName>Master_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Counter__c</fullName>
        <label>Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Template Type</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Goal Type you have selected is inactive.</errorMessage>
            <filterItems>
                <field>Goal_Type__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Goal_Type__c.Standard_Goal__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Goal_Type__c</referenceTo>
        <relationshipLabel>Goal Templates</relationshipLabel>
        <relationshipName>Standard_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Period_End__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Start__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Type__c</fullName>
        <label>Template Type</label>
        <picklist>
            <picklistValues>
                <fullName>Group</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Goal Template</label>
    <nameField>
        <label>Goal Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Standard_Goal_Detail__c.object
<CustomObject>
    <description>This object holds the specifics of a Goal Template. Each Goal Template will have multiple Detail records. These records are templates for application to individuals, and if used to create any Personal Goals, those will relate back to this record for easy identification and review.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used in lookups only</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Baseline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Baseline</label>
        <referenceTo>Standard_Goal_Detail__c</referenceTo>
        <relationshipName>Standard_Goal_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Goal_Type__c.Standard_Goal__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Goal_Type__c</referenceTo>
        <relationshipLabel>Goal Template Details</relationshipLabel>
        <relationshipName>Master_Goal_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Standard_Goal_Detail__c</referenceTo>
        <relationshipLabel>Goal Template Details (Parent)</relationshipLabel>
        <relationshipName>Goal_Template_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <label>Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Period_End__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Start__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Goal__c</fullName>
        <label>Goal Template</label>
        <referenceTo>Standard_Goal__c</referenceTo>
        <relationshipLabel>Goal Template Details</relationshipLabel>
        <relationshipName>Standard_Goal_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <label>Target Type</label>
        <picklist>
            <picklistValues>
                <fullName>Explicit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paced</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Goal Template Detail</label>
    <nameField>
        <label>Goal Template Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Template Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Standard_Goal_Detail_Pacing__c.object
<CustomObject>
    <description>These records are created generally through the Define Standards VF, and represent the allocation of a given Goal Template Detail across multiple periods. This distribution is represented by a percentage assignment to each record, the total of which should equate to 100 (however, there is no requirement that period allocations equal 100).</description>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Standard_Goal_Detail__r.Amount__c * Percent_Manual__c</formula>
        <label>Calculated Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percent_Manual__c</fullName>
        <label>Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <formula>Standard_Goal_Detail__r.Percent__c * Percent_Manual__c</formula>
        <label>Calculated Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Period_End__c</fullName>
        <label>Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_Start__c</fullName>
        <label>Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Goal_Detail__c</fullName>
        <label>Goal Template Detail</label>
        <referenceTo>Standard_Goal_Detail__c</referenceTo>
        <relationshipLabel>Goal Template Details Pacing</relationshipLabel>
        <relationshipName>Standard_Goal_Details_Pacing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Template</label>
        <referenceTo>Standard_Goal__c</referenceTo>
        <relationshipLabel>Goal Template Details Pacing</relationshipLabel>
        <relationshipName>Standard_Goal_Details_Pacing</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Goal Template Detail Pacing</label>
    <nameField>
        <label>Goal Template Detail Pacing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Template Details Pacing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Standard_Goal_Sales_Role__c.object
<CustomObject>
    <description>One or many Business Titles may be associated with a Goal Template.</description>
    <fields>
        <fullName>Standard_Goal__c</fullName>
        <label>Goal Template</label>
        <referenceTo>Standard_Goal__c</referenceTo>
        <relationshipLabel>Goal Template Business Titles</relationshipLabel>
        <relationshipName>Standard_Goal_Sales_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Goal Template Business Title</label>
    <nameField>
        <label>Goal Template Business Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Template Business Titles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Value_Type__c.object
<CustomObject>
    <description>This object holds the definitions of the different attributes that can be assigned to a Contact via Staff Attribute.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Value Type</label>
    <nameField>
        <label>Value Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_CloneGoalTemplateController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData = false)
private class Test_CloneGoalTemplateController {

/**
 *   Purpose         :   Test class for CloneGoalTemplateController
 *            
 *   Create By       :   Subhash Garhwal
 *
 *   Created Date    :   10/24/2015
 *
 *   Revision Log    :   V_1.0 - Created - CR-20150729-9114
 * 
 *   Coverage        :   V_1.0 - 95%
 **/
    
    //Test Method
    static testMethod void myUnitTest() {
        
        // TO DO: implement unit test
        
        /********************       Create test data         **********************/
        
        //Query through the Conditions record type
        List<RecordType> rTypes = [Select Id, DeveloperName From RecordType Where SObjectType = 'Condition__c' ORDER BY DeveloperName ASC];
        
        //Account
        Account account = TestUtilities.CreateNewAccount(false);
        
        //Insert
        insert account;
        
        //Assert
        System.assert(account != null);
        
        //Create Contact records
        List<Contact> contacts = new List<Contact>();
        
        //Add new contact record in list
        contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact 1', Email = 'test1@test.com', AccountId = account.Id, Employee_User_Record__c = Userinfo.getUserId()));
        contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact 2', Email = 'test2@test.com', AccountId = account.Id, Employee_User_Record__c = Userinfo.getUserId()));
        
        //Insert
        insert contacts;
        
        //Assert
        System.assert(contacts.size() > 0);
        
        //List of goal type
        List<Goal_Type__c> goalTypes = new List<Goal_Type__c>();
        
        //Add new goal types in list to insert
        goalTypes.add(new Goal_Type__c(Description__c = 'GT 1', Base_Process__c = 'Other', Standard_Goal__c = true, Active__c = true));
        goalTypes.add(new Goal_Type__c(Description__c = 'GT 2', Base_Process__c = 'Other', Standard_Goal__c = true, Active__c = true));
        goalTypes.add(new Goal_Type__c(Description__c = 'GTD 1', Base_Process__c = 'Other', Standard_Goal__c = false, Active__c = true));
        goalTypes.add(new Goal_Type__c(Description__c = 'GTD 2', Base_Process__c = 'Other', Standard_Goal__c = false, Active__c = true));
        
        //Insert
        insert goalTypes;
        
        //Assert
        System.assert(goalTypes.size() > 0);
        
        //List of Goal Template
        List<Standard_Goal__c> goalTemplates = new List<Standard_Goal__c>();
        
        //Add new goal template in the list
        goalTemplates.add(new Standard_Goal__c(Active__c = true, Amount__c = 100000, Business_Owner__c = contacts[0].Id, Description__c = 'Goal Temp 1',
                                               Goal_Type__c = goalTypes[0].Id, Period_Start__c = System.today(), Period_End__c = System.today().addDays(365),
                                               Standard_Type__c = 'Group'));
        
        goalTemplates.add(new Standard_Goal__c(Active__c = true, Counter__c = 100000, Business_Owner__c = contacts[1].Id, Description__c = 'Goal Temp 2',
                                               Goal_Type__c = goalTypes[1].Id, Period_Start__c = System.today(), Period_End__c = System.today().addDays(365),
                                               Standard_Type__c = 'Group'));
        
        goalTemplates.add(new Standard_Goal__c(Active__c = true, Percent__c = 80, Business_Owner__c = contacts[1].Id, Description__c = 'Goal Temp 3',
                                               Goal_Type__c = goalTypes[1].Id, Period_Start__c = System.today(), Period_End__c = System.today().addDays(365),
                                               Standard_Type__c = 'Personal'));
        
        //Insert
        insert goalTemplates;
        
        //Assert
        System.assert(goalTemplates.size() > 0);
        
        //List of Goal Template Details
        List<Standard_Goal_Detail__c> goalTempDetails = new List<Standard_Goal_Detail__c>();
        
        //Add new GTD in the list
        goalTempDetails.add(new Standard_Goal_Detail__c(Standard_Goal__c = goalTemplates[0].Id, Active__c = true, Description__c = 'GT 1 GTD 1',
                                                        Goal_Type__c = goalTypes[2].Id, Target_Type__c = 'Paced'));
        
        goalTempDetails.add(new Standard_Goal_Detail__c(Standard_Goal__c = goalTemplates[0].Id, Active__c = true, Description__c = 'GT 1 GTD 2',
                                                        Goal_Type__c = goalTypes[3].Id, Target_Type__c = 'Paced', Period_Start__c = System.today(),
                                                        Period_End__c = System.today().addDays(100)));
                                                        
        goalTempDetails.add(new Standard_Goal_Detail__c(Standard_Goal__c = goalTemplates[0].Id, Active__c = true, Description__c = 'GT 1 GTD 3',
                                                        Goal_Type__c = goalTypes[2].Id, Target_Type__c = 'Explicit', Period_Start__c = System.today(),
                                                        Period_End__c = System.today().addDays(100)));
        
        goalTempDetails.add(new Standard_Goal_Detail__c(Standard_Goal__c = goalTemplates[1].Id, Active__c = true, Description__c = 'GT 2 GTD 1',
                                                        Goal_Type__c = goalTypes[2].Id, Target_Type__c = 'Paced'));
        
        goalTempDetails.add(new Standard_Goal_Detail__c(Standard_Goal__c = goalTemplates[1].Id, Active__c = true, Description__c = 'GT 2 GTD 2',
                                                        Goal_Type__c = goalTypes[3].Id, Target_Type__c = 'Paced', Period_Start__c = System.today(),
                                                        Period_End__c = System.today().addDays(20)));
                                                        
        goalTempDetails.add(new Standard_Goal_Detail__c(Standard_Goal__c = goalTemplates[1].Id, Active__c = true, Description__c = 'GT 2 GTD 3',
                                                        Goal_Type__c = goalTypes[2].Id, Target_Type__c = 'Explicit', Period_Start__c = System.today(),
                                                        Period_End__c = System.today().addDays(120)));
       
       //Insert
       insert goalTempDetails;
       
       //Assert
       System.assert(goalTempDetails.size() > 0);
       
       //List of Goal Template Detail Measurement Period
        List<Goal_Template_Detail_Measurement_Period__c> gTMPeriods = new List<Goal_Template_Detail_Measurement_Period__c>();
        
        //Add new GTDMP in the list
        gTMPeriods.add(new Goal_Template_Detail_Measurement_Period__c(Goal_Template_Detail__c= goalTempDetails[0].Id, Measurement_Date__c = System.today()));
       
       //Insert
       insert gTMPeriods ;
       
       //Assert
       System.assert(gTMPeriods .size() > 0);
       
       //Update Parent and baseline
       goalTempDetails[0].Baseline__c = goalTempDetails[2].Id;
       goalTempDetails[0].Parent__c = goalTempDetails[1].Id; 
       
       //update records
       update goalTempDetails;
       
       //List of goal template detail pacings
       List<Standard_Goal_Detail_Pacing__c> gTDPacings = new List<Standard_Goal_Detail_Pacing__c>();
       
       //add in pacings in the list
       gTDPacings.add(new Standard_Goal_Detail_Pacing__c(Standard_Goal__c = goalTemplates[0].Id, Standard_Goal_Detail__c = goalTempDetails[0].Id,
                                                         Period_Start__c = System.today().addDays(10), Period_End__c = System.today().addDays(50),
                                                         Description__c = 'GT 1 GTD 1 GTDP 1', Percent_Manual__c = 70));
        
        gTDPacings.add(new Standard_Goal_Detail_Pacing__c(Standard_Goal__c = goalTemplates[0].Id, Standard_Goal_Detail__c = goalTempDetails[0].Id,
                                                         Period_Start__c = System.today().addDays(51), Period_End__c = System.today().addDays(150),
                                                         Description__c = 'GT 1 GTD 1 GTDP 2', Percent_Manual__c = 30));
        
        gTDPacings.add(new Standard_Goal_Detail_Pacing__c(Standard_Goal__c = goalTemplates[0].Id, Standard_Goal_Detail__c = goalTempDetails[1].Id,
                                                         Period_Start__c = System.today().addDays(20), Period_End__c = System.today().addDays(90),
                                                         Description__c = 'GT 1 GTD 2 GTDP 1', Percent_Manual__c = 100));
        
        gTDPacings.add(new Standard_Goal_Detail_Pacing__c(Standard_Goal__c = goalTemplates[0].Id, Standard_Goal_Detail__c = goalTempDetails[2].Id,
                                                         Period_Start__c = System.today().addDays(20), Period_End__c = System.today().addDays(90),
                                                         Description__c = 'GT 1 GTD 3 GTDP 1', Percent_Manual__c = 100));
        
        gTDPacings.add(new Standard_Goal_Detail_Pacing__c(Standard_Goal__c = goalTemplates[1].Id, Standard_Goal_Detail__c = goalTempDetails[3].Id,
                                                         Period_Start__c = System.today().addDays(10), Period_End__c = System.today().addDays(50),
                                                         Description__c = 'GT 2 GTD 1 GTDP 1', Percent_Manual__c = 70));
        
        gTDPacings.add(new Standard_Goal_Detail_Pacing__c(Standard_Goal__c = goalTemplates[1].Id, Standard_Goal_Detail__c = goalTempDetails[3].Id,
                                                         Period_Start__c = System.today().addDays(51), Period_End__c = System.today().addDays(150),
                                                         Description__c = 'GT 2 GTD 1 GTDP 2', Percent_Manual__c = 30));
        
        gTDPacings.add(new Standard_Goal_Detail_Pacing__c(Standard_Goal__c = goalTemplates[1].Id, Standard_Goal_Detail__c = goalTempDetails[4].Id,
                                                         Period_Start__c = System.today().addDays(20), Period_End__c = System.today().addDays(90),
                                                         Description__c = 'GT 2 GTD 2 GTDP 1', Percent_Manual__c = 100));
        
        gTDPacings.add(new Standard_Goal_Detail_Pacing__c(Standard_Goal__c = goalTemplates[1].Id, Standard_Goal_Detail__c = goalTempDetails[5].Id,
                                                         Period_Start__c = System.today().addDays(20), Period_End__c = System.today().addDays(90),
                                                         Description__c = 'GT 2 GTD 3 GTDP 1', Percent_Manual__c = 100));
        
        //Insert
        insert gTDPacings;
        
        //Assert
        System.assert(gTDPacings.size() > 0);
        
        //List of conditions
        List<Condition__c> conditions = new List<Condition__c>();
        
        //Add new condition in list
        conditions.add(new Condition__c(RecordTypeId = rTypes[0].Id, Standard_Goal__c = goalTemplates[0].Id, Start_Date__c = System.today(),
                                        End_Date__c = System.today().addDays(1), Date_Type__c = 'Anniversary', Condition_Type__c = 'Include'));
        
        conditions.add(new Condition__c(RecordTypeId = rTypes[0].Id, Standard_Goal__c = goalTemplates[0].Id, Standard_Goal_Detail__c = goalTempDetails[0].Id,
                                        Start_Date__c = System.today().addDays(2), End_Date__c = System.today().addDays(10), Date_Type__c = 'Renewal',
                                        Condition_Type__c = 'Include'));
        
        conditions.add(new Condition__c(RecordTypeId = rTypes[6].Id, Standard_Goal__c = goalTemplates[0].Id, Standard_Goal_Detail__c = goalTempDetails[2].Id,
                                        Start_Date__c = System.today().addDays(11), End_Date__c = System.today().addDays(15), Agreement_Type__c = 'LOA',
                                        Condition_Type__c = 'Include'));
        
        conditions.add(new Condition__c(RecordTypeId = rTypes[0].Id, Standard_Goal__c = goalTemplates[1].Id, Start_Date__c = System.today(),
                                        End_Date__c = System.today().addDays(1), Date_Type__c = 'Anniversary', Condition_Type__c = 'Include'));
        
        conditions.add(new Condition__c(RecordTypeId = rTypes[0].Id, Standard_Goal__c = goalTemplates[1].Id, Standard_Goal_Detail__c = goalTempDetails[3].Id,
                                        Start_Date__c = System.today().addDays(2), End_Date__c = System.today().addDays(10), Date_Type__c = 'Renewal',
                                        Condition_Type__c = 'Include'));
        
        conditions.add(new Condition__c(RecordTypeId = rTypes[6].Id, Standard_Goal__c = goalTemplates[1].Id, Standard_Goal_Detail__c = goalTempDetails[4].Id,
                                        Start_Date__c = System.today().addDays(11), End_Date__c = System.today().addDays(15), Agreement_Type__c = 'LOA',
                                        Condition_Type__c = 'Include'));
        
        conditions.add(new Condition__c(RecordTypeId = rTypes[0].Id, Standard_Goal__c = goalTemplates[2].Id, Start_Date__c = System.today(),
                                        End_Date__c = System.today().addDays(1), Date_Type__c = 'Anniversary', Condition_Type__c = 'Include'));
        
        conditions.add(new Condition__c(RecordTypeId = rTypes[6].Id, Standard_Goal__c = goalTemplates[2].Id, Start_Date__c = System.today().addDays(11),
                                        End_Date__c = System.today().addDays(15), Agreement_Type__c = 'LOA', Condition_Type__c = 'Include'));
        
        //Insert
        insert conditions;
        
        //Assert
        System.assert(conditions.size() > 0);
        
        //List of Values Types
        List<Value_Type__c> valueTypes = new List<Value_Type__c>();
        
        //Add new value type in list
        valueTypes.add(new Value_Type__c(Category__c = 'Business Title', Values_Permitted__c = 'Text'));
        
        //Insert
        insert valueTypes;
        
        //Assert
        System.assert(valueTypes.size() > 0);
        
        //List of GTBTs
        List<Standard_Goal_Sales_Role__c> gTBTitles = new List<Standard_Goal_Sales_Role__c>();
        
        //Add new GTBT 
        gTBTitles.add(new Standard_Goal_Sales_Role__c(Standard_Goal__c = goalTemplates[1].Id, Sales_Role__c = valueTypes[0].Id));
        gTBTitles.add(new Standard_Goal_Sales_Role__c(Standard_Goal__c = goalTemplates[1].Id, Sales_Role__c = valueTypes[0].Id));
        gTBTitles.add(new Standard_Goal_Sales_Role__c(Standard_Goal__c = goalTemplates[2].Id, Sales_Role__c = valueTypes[0].Id));
        
        //Insert
        insert gTBTitles;
        
        //Assert
        System.assert(gTBTitles.size() > 0);
        
        //Start testing from here
        Test.startTest();
        
        //Query through the Goal Templates
        List<Standard_Goal__c> goalTemps = [Select Id From Standard_Goal__c];
        
        //Assert for result
        System.assertEquals(3, goalTemps.size());
        
        //Query through the GTD
        List<Standard_Goal_Detail__c> gTDetails = [Select Id From Standard_Goal_Detail__c];
        
        //Assert for result
        System.assertEquals(6, gTDetails.size());
        
        //Query through the GTDP
        List<Standard_Goal_Detail_Pacing__c> gTempDPacings = [Select Id From Standard_Goal_Detail_Pacing__c];
        
        //Assert for result
        System.assertEquals(8, gTempDPacings.size());
        
        //Query through the Condition
        List<Condition__c> conditionList = [Select Id From Condition__c];
        
        //Assert for result
        System.assertEquals(8, conditionList.size());
        
        //Query through the GTBT
        List<Standard_Goal_Sales_Role__c> gTBTs = [Select Id From Standard_Goal_Sales_Role__c];
        
        //Asset for result
        System.assertEquals(3, gTBTs.size());
        
        //Standard controller       
        ApexPages.StandardController sc = new ApexPages.standardController(new Standard_Goal__c());
        
        //Instance of controller
        CloneGoalTemplateController controller = new CloneGoalTemplateController(sc);
        
        //Call method to clone the Goal Template (As passed Goal Template not having any Id so no record will get cloned).
        controller.cloneGoalTemplates();
        
        //Query through the Goal Templates
        goalTemps = [Select Id From Standard_Goal__c];
        
        //Assert for result
        System.assertEquals(3, goalTemps.size());
        
        //Query through the Goal_Template_Detail_Measurement_Period__c
        gTMPeriods = [Select Id From Goal_Template_Detail_Measurement_Period__c];
        
        //Assert for result
        System.assertEquals(1, gTMPeriods.size());
        
        //Set saved record in std controller 
        sc = new ApexPages.standardController(goalTemplates[0]);
        
        //Constructor
        controller = new CloneGoalTemplateController(sc);
        
        //Call method to clone the Goal Template
        controller.cloneGoalTemplates();
        
        //Query through the Goal Templates
        goalTemps = [Select Id, CreatedDate, Description__c From Standard_Goal__c ORDER BY CreatedDate ASC];
        
        //Assert for result
        System.assertEquals(4, goalTemps.size());
        
        //Query through the Goal Template
        goalTemps = [Select Id, Description__c, (Select Id From Standard_Goal_Details__r), (Select Id From Conditions__r),
                                                (Select Id From Standard_Goal_Sales_Roles__r) From Standard_Goal__c Where Description__c = 'Clone of: Goal Temp 1'];
        
        //Asserts for results
        System.assertEquals(1, goalTemps.size());
        System.assertEquals('Clone of: Goal Temp 1', goalTemps[0].Description__c);
        System.assertEquals(3, goalTemps[0].Standard_Goal_Details__r.size());
        System.assertEquals(3, goalTemps[0].Conditions__r.size());
        System.assertEquals(0, goalTemps[0].Standard_Goal_Sales_Roles__r.size());
        
        //Query through the Pacings
        gTempDPacings = [Select Id From Standard_Goal_Detail_Pacing__c Where Standard_Goal_Detail__c IN : goalTemps[0].Standard_Goal_Details__r];
        
        System.assertEquals(4, gTempDPacings.size());
        
        //Query through the Goal_Template_Detail_Measurement_Period__c
        gTMPeriods = [Select Id From Goal_Template_Detail_Measurement_Period__c];
        
        //Assert for result
        System.assertEquals(2, gTMPeriods.size());
        
        //Re-Set saved record in std controller
        sc = new ApexPages.standardController(new Standard_Goal__c());
        
        //Constructor
        controller = new CloneGoalTemplateController(sc);
        
        //Set the standard set controller
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(new List<Standard_Goal__c>());
        
        //Constructor
        controller = new CloneGoalTemplateController(ssc);
        
        //Call method to clone the Goal Template
        controller.cloneGoalTemplates();
        
        //Query through the Goal Templates
        goalTemps = [Select Id From Standard_Goal__c ORDER BY CreatedDate ASC];
        
        //Assert for result
        System.assertEquals(4, goalTemps.size());
        
        //Query through the Goal_Template_Detail_Measurement_Period__c
        gTMPeriods = [Select Id From Goal_Template_Detail_Measurement_Period__c];
        
        //Assert for result
        System.assertEquals(2, gTMPeriods.size());
        
        //Set the standard set controller
        ssc = new ApexPages.StandardSetController(new List<Standard_Goal__c>{goalTemplates[1], goalTemplates[2]});
        ssc.setSelected(new List<Standard_Goal__c>{goalTemplates[1], goalTemplates[2]});
        
        //Constructor
        controller = new CloneGoalTemplateController(ssc);
        
        //Call method to clone the Goal Template
        controller.cloneGoalTemplates();
        
        //Query through the Goal Templates
        goalTemps = [Select Id, Description__c From Standard_Goal__c];
        
        //Assert for result
        System.assertEquals(6, goalTemps.size());
        
        //Query through the GTD
        gTDetails = [Select Id From Standard_Goal_Detail__c];
        
        //Assert for result
        System.assertEquals(12, gTDetails.size());
        
        //Query through the Goal_Template_Detail_Measurement_Period__c
        gTMPeriods = [Select Id From Goal_Template_Detail_Measurement_Period__c];
        
        //Assert for result
        System.assertEquals(2, gTMPeriods.size());
        
        //Query through the GTDP
        gTempDPacings = [Select Id From Standard_Goal_Detail_Pacing__c];
        
        //Assert for result
        System.assertEquals(16, gTempDPacings.size());
        
        //Query through the Condition
        conditionList = [Select Id From Condition__c];
        
        //Assert for result
        System.assertEquals(16, conditionList.size());
        
        //Query through the GTBT
        gTBTs = [Select Id From Standard_Goal_Sales_Role__c];
        
        //Asset for result
        System.assertEquals(6, gTBTs.size());
        
        //Stop testing here
        Test.stopTest();
    }
}