objects/ConsolidatedInvoice__c.object
<CustomObject>
    <fields>
        <fullName>PrintStatus__c</fullName>
        <label>Print Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Printed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Consolidated Invoice</label>
    <nameField>
        <displayFormat>CINV{00000}</displayFormat>
        <label>Consolidated Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consolidated Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCInvBulkPrintExtension.cls
@isTest
private class TestCInvBulkPrintExtension {
    static testMethod void testContinuePrinting()
    {
        ConsolidatedInvoice__c ci = new ConsolidatedInvoice__c(PrintStatus__c = 'Not Printed');
        insert ci;
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController([Select Id, Name from ConsolidatedInvoice__c Where Id = :ci.id]);
        sc.setSelected(new List<ConsolidatedInvoice__c>{ci});

Test.startTest();
        CInvBulkPrintExtension handler = new CInvBulkPrintExtension(sc);
        handler.ContinuePrinting();
Test.stopTest();

        ci = [Select Id, Name, PrintStatus__c from ConsolidatedInvoice__c Where Id = :ci.id];
        System.AssertEquals('Printed', ci.PrintStatus__c);
    }
}