objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <formula>Text(Program__r.Business_line__c)</formula>
        <label>Business Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Renewal_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Renewal Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contract Renewal Opportunity</relationshipLabel>
        <relationshipName>Contracts_ABC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payer_Account__c</fullName>
        <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
        <label>Payer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts ABC</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Acronym__c</fullName>
        <formula>Program__r.Program_Acronym__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Acronym</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contracts ABC</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
        <label>Start</label>
        <type>Date</type>
    </fields>
    <label>Contract ABC</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts ABC</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CR-3485-This field is used in an integration with Eloqua. Please research with the appropriate stakeholders/liaisons before altering it&apos;s meaning, usage, field type or other field characteristics. Do not delete or change the current API name.</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_Contract_Idenfied__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active Contract Identified</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Memberships (Active Contract Identified)</relationshipLabel>
        <relationshipName>Memberships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_Marketer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Marketer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <formula>Active_Contract_Idenfied__r.Source_Opportunity__r.End__c</formula>
        <label>End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Acronym__c</fullName>
        <formula>Program__r.Program_Acronym__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Acronym</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CR-3485-This field is used in an integration with Eloqua. Please research with the appropriate stakeholders/liaisons before altering it&apos;s meaning, usage, field type or other field characteristics. Do not delete or change the current API name.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <formula>Active_Contract_Idenfied__r.Source_Opportunity__r.Start__c</formula>
        <label>Start</label>
        <type>Date</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Membership_Key_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Membership Key Contacts</relationshipLabel>
        <relationshipName>Membership_Key_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Membership</label>
        <referenceTo>Membership__c</referenceTo>
        <relationshipLabel>Membership Key Contacts</relationshipLabel>
        <relationshipName>Membership_Key_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Type__c</fullName>
        <label>Role Type</label>
        <picklist>
            <picklistValues>
                <fullName>CIH programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCIC programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Higher Ed Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital Research Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iRound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TD Programs</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Membership Key Contact</label>
    <nameField>
        <label>Membership Key Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membership Key Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
    <fields>
        <fullName>Business_line__c</fullName>
        <label>Business line</label>
        <picklist>
            <picklistValues>
                <fullName>CLN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Create_memberships__c</fullName>
        <label>Create memberships?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Business_Marketer__c</fullName>
        <label>New Business Marketer</label>
        <picklist>
            <picklistValues>
                <fullName>ABI RI Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE or EA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCLF Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical Integration Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ClinOps Solution Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concuity Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crimson Clinical Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crimson Market Advantage Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Engagement Survey Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Employee Health Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Spend Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ITI Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFI Products Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OptiLink Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayNav Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PBM Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI Clinical Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI Operations Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI Strategy Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SALC Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TD Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tech Insights Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UBER Marketer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULC Marketer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Acronym__c</fullName>
        <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
        <label>Program Acronym</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Site_Profile__c.object
<CustomObject>
    <description>Determines the site(s) that a Contact has access to.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Site Profiles</relationshipLabel>
        <relationshipName>Site_Profiles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Site Profile</label>
    <nameField>
        <displayFormat>SP-{0000000}</displayFormat>
        <label>Site Profile Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_MembershipKeyContactTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_MembershipKeyContactTrigger {
/*
    Purpose         :   Test class for Trigger_MembershipKeyContact
                
    Create By       :   Simplyforce Technology
    
    Created Date    :   12/16/2012
    
    Current Version :   V1.0
    
    Revision Log    :   V1.0 - Created
                        v1.1 - (SUNJ 12/19/13) - CR-20130118-2218

    Coverage        :   Trigger_MembershipKeyContact - 100%
                        MembershipKeyContactTriggerHelper - 100%
*/
    static User usr = [select id from User where isActive = true AND UserType = 'Standard' limit 1];
    
    static testMethod void myUnitTest() {
        //Bypass Dupeblocker
        Util.IsTest(true);
        Util.IsTesting = true;
        
        // setup the custom setting
        Util.resetRecordtypeSettings();
        
        system.debug('### Test Case 1 ###');
        
        Account acc = new Account(Name = 'Test Case Account 1', RecordTypeId = Util.recordtypemap('Account').get('US Corporate'), Academy_Programs_Available_for_Outreach__c = '', BI_Programs_Available_for_Outreach__c = '', Core_Programs_Available_for_Outreach__c = '');
        insert acc;
        
        Program__c testProg1 = new Program__c(Name='Test Trigger Program', New_Business_Marketer__c = 'RI Marketer', Program_Acronym__c='ZZZ', Create_memberships__c='No', Business_line__c = 'PT');
        insert testProg1;
        
        Program__c testProg2 = new Program__c(Name='Test Trigger Program', New_Business_Marketer__c = 'RI Marketer', Program_Acronym__c='Test Update', Create_memberships__c='No', Business_line__c = 'PT');
        insert testProg2;
        
        AccountTeamMember accMember = new AccountTeamMember(
            UserId = usr.Id,
            AccountId = acc.Id,
            TeamMemberRole = testProg1.New_Business_Marketer__c);
            //AccountAccessLevel = 'Read');
        insert accMember;
        
        Opportunity testOpp = new Opportunity(Name='Test Opp', StageName = 'Prospect', Amount=1, CloseDate = System.today(), AccountId = acc.Id);
        insert testOpp;
        
        Contract__c testContract1 = new Contract__c(
            Name='Test Contract1', Payer_Account__c = acc.Id, Program__c = testProg1.Id, 
            Start__c = System.Today().addDays(-10), End__c = system.today().addDays(355),
            Contract_Renewal_Opportunity__c = testOpp.Id
            );
            
        insert testContract1;
        
        List<Membership__c> memberships = new List<Membership__c>();
        
        //Test.startTest
        Test.startTest();
        
        Membership__c member1 = new Membership__c(
            Name = 'Test Membership',
            Account_Name__c = acc.Id,
            Program__c = testProg1.Id,
            Active_Contract_Idenfied__c = testContract1.Id);
        
        memberships.add(member1);
        
        Membership__c member2 = new Membership__c(
            Name = 'Test Membership',
            Account_Name__c = acc.Id,
            OwnerId = usr.Id,
            Assigned_Marketer__c = usr.Id, 
            Program__c = testProg1.Id,
            Active_Contract_Idenfied__c = testContract1.Id
        );
        
        memberships.add(member2);
        
        Membership__c member3 = new Membership__c(
            Name = 'Test Membership',
            Account_Name__c = acc.Id,
            Program__c = testProg1.Id,
            OwnerId = usr.Id,
            Assigned_Marketer__c = usr.Id);
        
        Util.IsBatch = false;
        Util.IsTrigger_ContractFieldUpdate = false;
        Util.IsTrigger_Opportunity_ValidationAndFieldUpdates = false;
        Util.IsTrigger_EventPrewire = false;
        Util.IsTrigger_EventUpdateFields = false;
        Util.IsTrigger_ContractIntegratedAcctRunning = false;
        
        insert memberships;
        insert member3;
        
        Site_Profile__c sProfile = Test_SiteUserHelper.CreateSiteProfile(SiteUserHelper.SITE_ADVISORY, true);
        
        Contact con = [SELECT Id, Name, Email FROM Contact WHERE Id = :sProfile.Contact__c];
        
        //Test Case for - CR-20121019-1641
        update member2;
        
        //Insert membership key contact record
        Membership_Key_Contact__c testMembershipKeyContact = new Membership_Key_Contact__c(
            Contact__c = con.id,
            Name='Test 1', 
            Role_Type__c = 'PT', 
            Role__c = 'Exec Sponsor', 
            Membership__c = member2.Id,
            Pubs__c = true,
            Meetings__c = true);
        insert testMembershipKeyContact;
        
        member2 = [select id, Membership_Status__c, OwnerId, Assigned_Marketer__c, Active_Contract_Idenfied__c, Latest_Contract__c, Earliest_Contract__c from Membership__c where Id = :member2.Id];
        system.debug('\n\nm2.Membership_Status__c ' + member2.Membership_Status__c);
        
        //Assert for the result
        con = [Select Id, Membership_Contact_Pubs__c, Membership_Contact_Meetings__c from Contact where Id =: con.Id];
        System.assertEquals(testProg1.Program_Acronym__c, con.Membership_Contact_Pubs__c);
        System.assertEquals(testProg1.Program_Acronym__c, con.Membership_Contact_Meetings__c);
        
        //Stop test here    
        Test.stopTest();
    }
}