objects/Contract__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <formula>Text(Program__r.Business_line__c)</formula>
        <label>Business Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Billing_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Billing Schedule</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only select Billing Schedules associated with the Payer Account on this Contract.</errorMessage>
            <filterItems>
                <field>$Source.Payer_Account__c</field>
                <operation>equals</operation>
                <valueField>Invoice_Billing_Schedule__c.Institution__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Invoice_Billing_Schedule__c</referenceTo>
        <relationshipLabel>Contracts ABC</relationshipLabel>
        <relationshipName>Contracts_ABC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Join_Date__c</fullName>
        <description>If this is the first contract, then the date is set manually.  Otherwise it is the Previous Contract&apos;s join Date</description>
        <label>Join Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Main_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Negotiated_Amount__c</fullName>
        <label>Negotiated Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payer_Account__c</fullName>
        <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
        <label>Payer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts ABC</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Contracts ABC</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
        <label>Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Dropped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Honorary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>NBB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
        <label>Year</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Contract ABC</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts ABC</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice_Billing_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>ABC Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Billing Schedules</relationshipLabel>
        <relationshipName>Invoice_Billing_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Negotiated_Amt__c = Line_Items_Total_Amt__c , IMAGE(&quot;/img/samples/flag_green.gif&quot;,&quot;All Amounts Scheduled&quot;),
IF(Total_Negotiated_Amt__c &gt; Line_Items_Total_Amt__c, IMAGE(&quot;/img/samples/flag_yellow.gif&quot;,&quot;ALERT: Additional Line Item Amounts Needed&quot;),
IF(Total_Negotiated_Amt__c &lt; Line_Items_Total_Amt__c, IMAGE(&quot;/img/samples/flag_red.gif&quot;,&quot;WARNING: Line Items exceed Negotiated Amounts&quot;),&quot; &quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Invoice Billing Schedule</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Invoice Billing Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Billing Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Line_Item_Schedule__c.object
<CustomObject>
    <description>To store the breakdown of the contracts abc negotiated amount</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>USD Amount that will be posted to GL</inlineHelpText>
        <label>USD Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Line Item Schedules</relationshipLabel>
        <relationshipName>Line_Item_Schedule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <formula>Contract__r.Payer_Account__r.Account_Formal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Billing_Schedule_del__c</fullName>
        <label>Invoice Billing Schedule</label>
        <referenceTo>Invoice_Billing_Schedule__c</referenceTo>
        <relationshipLabel>Line Item Schedules</relationshipLabel>
        <relationshipName>Line_Item_Schedules_del</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Comment__c</fullName>
        <description>Populates on the Invoice sent to Member; Invoice Comment must match for all line items included on invoice, else Validation will fail and invoice will not be created.</description>
        <inlineHelpText>This comment will display on the Invoice sent to Members beneath the list of programs and amounts being billed. Invoice Comment must be the same on all Line Items Schedules included in the invoice in order to be generated.</inlineHelpText>
        <label>Invoice Comment</label>
        <length>800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Contact__c</fullName>
        <formula>Contract__r.Invoice_Contact__r.FirstName &amp;&quot; &quot;&amp; Contract__r.Invoice_Contact__r.LastName</formula>
        <label>Invoice Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Main_Contact__c</fullName>
        <formula>Contract__r.Main_Contact__r.FirstName &amp;&quot; &quot; &amp; Contract__r.Main_Contact__r.LastName</formula>
        <label>Main Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Contract__r.Program__r.Program_Formal_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>To distinquish line items on an invoice; defaults to &apos;Member Fee&apos;</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Admin Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billable Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Fee</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel T&amp;M</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Line Item Schedule</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Item Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
    <fields>
        <fullName>Business_line__c</fullName>
        <label>Business line</label>
        <picklist>
            <picklistValues>
                <fullName>CLN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Upsell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_AddContractsToInvoiceBillingSched.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition. 
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_AddContractsToInvoiceBillingSched {
/*
    Purpose:    Test Class for AddContractsToInvoiceBillingSchedule
                
    Create By:  Simplyforce Technology
    
    Created Date:   10/27/2011
    
    Current Version:    V1.0 
						V1.1 - Modified By - Mahendra Swarnkar - 4/2/2016 - CR-20160113-9513
    
    Revision Log:   Created  
    
    Coverage : 100%         
*/
    static testMethod void myUnitTest() {
        
        //fecth the existing record type from data base
        List<RecordType> listRecordType = [Select SobjectType, Name, IsActive, Id, DeveloperName From RecordType
                                            where IsActive = true and SobjectType = 'Account' and DeveloperName ='US_Provider' limit 1];
        
        //check for the list size
        if(listRecordType.size() > 0) {
            
            //create the account and contact sample data
            Account institution = new Account(Name = 'TestAccount', RecordTypeId = listRecordType[0].Id);
            insert institution;
            
            //insert the  Invoice Billing record
            Invoice_Billing_Schedule__c invoiceBillingSchedule = new Invoice_Billing_Schedule__c(Institution__c = institution.Id);
            insert invoiceBillingSchedule;
            
            //insert the program test data
            Program__c program = new Program__c(Name = 'TestProgram');
            insert program;
            
            //insert the Main contact record
            Contact mainContact = new Contact(LastName = 'TestLastName', AccountId = institution.Id, Record_Type__c = listRecordType[0].Name);
            insert mainContact;
            
            // Create invoice billing data
            Invoice_Billing_Schedule__c ibs = new Invoice_Billing_Schedule__c(Institution__c = institution.Id);
            insert ibs;
            
            List<Contract__c> listContract = new List<Contract__c>();
            
            for(Integer i = 0; i < 101; i++) {
                listContract.add(new Contract__c(Negotiated_Amount__c = 100, Type__c = 'Test', Start__c = Date.today(), End__c = Date.today(), 
                                                        Year__c = '2011', Program__c = program.Id, Join_Date__c = Date.today(),  
                                                        Main_Contact__c = mainContact.Id, Invoice_Contact__c = mainContact.Id,
                                                        Status__c = Constants.STATUS_ATL, Payer_Account__c = institution.Id));
            }
            
            insert listContract;
        
            // VRH 7/6/12 - The code below that was adding Line_Item_Schedule__c records was breaking this unit test 
            /*//Create 200 LIS records to test the ContractABCTriggerHelper.validateIBSIdForContactABC functionality
            List<Line_Item_Schedule__c> listLIS = new List<Line_Item_Schedule__c>();

            for(Integer i = 0; i < 101; i++) {
                listLIS.add(new Line_Item_Schedule__c(Contract__c = listContract[i].Id, Invoice_Billing_Schedule_del__c = listContract[i].Invoice_Billing_Schedule__c, 
                                                                    Type__c = 'Test', Invoice_Date__c = Date.today(), Invoice_Comment__c = 'Test', 
                                                                    Amount__c = 20));
            }
            
            insert listLIS;*/
            
                        
            /*//insert dummay Contract ABC record
            Contract__c contractABC = new Contract__c(Negotiated_Amount__c = 100, Type__c = 'Test', Start__c = Date.today(), End__c = Date.today(), 
                                                        Year__c = '2011', Program__c = program.Id, Join_Date__c = Date.today(),  
                                                        Main_Contact__c = mainContact.Id, Invoice_Contact__c = mainContact.Id,
                                                        Status__c = Constants.STATUS_ATL, Payer_Account__c = institution.Id);
            insert contractABC;*/
            
            //start test from here 
            Test.startTest();
            
            //initiate controller
            AddContractsToInvoiceBillingSchedule controller = new AddContractsToInvoiceBillingSchedule(new ApexPages.StandardController(invoiceBillingSchedule));
            
            //assert for the constructor result
            System.assertEquals(101, controller.listContractABCWrapper.size());
            
            for(Integer i = 0; i < 101; i++) {
                //mark the wrapper record selected
                controller.listContractABCWrapper[i].selected = true;
            }
            
            //call add contract method
            controller.addContracts();
            
            //fecth the contract back and assert the result
            List<Contract__c> contracts = [Select Invoice_Billing_Schedule__c from Contract__c where Id IN: listContract];
            System.assertEquals(101, contracts.size());
            System.assertEquals(invoiceBillingSchedule.Id, contracts[0].Invoice_Billing_Schedule__c);
            
            //catch the exception part
            controller.listContractABCWrapper[0].contractABC = new Contract__c(Status__c = Constants.STATUS_ATL, Payer_Account__c = institution.Id);
            
            //call add contract method
            controller.addContracts();
            
            //check error on page
            System.assert(ApexPages.hasMessages(ApexPages.Severity.ERROR));
            
            //stop test here
            Test.stopTest();
        }
    }
    
    //Creted By - Mahendra Swarnkar - 4/2/2016 - CR-20160113-9513
	Public static testMethod void myUnitTest1() {
        
		//fecth the existing record type from data base
        List<RecordType> listRecordType = [Select SobjectType, Name, IsActive, Id, DeveloperName From RecordType
                                            where IsActive = true and SobjectType = 'Account' and DeveloperName ='US_Provider' limit 1];
        
        //check for the list size
        if(listRecordType.size() > 0) {
            
            //create the account and contact sample data
            Account institution = new Account(Name = 'TestAccount', RecordTypeId = listRecordType[0].Id);
            insert institution;
            
            //insert the  Invoice Billing record
            Invoice_Billing_Schedule__c invoiceBillingSchedule =  new Invoice_Billing_Schedule__c(Institution__c = institution.Id);
			insert invoiceBillingSchedule;

            //insert the program test data
			List<Program__c> programs = new List<Program__c>();
			programs.add(new Program__c(Name = 'TestProgramCLN', Business_line__c = 'CLN'));
			programs.add(new Program__c(Name = 'TestProgramSW', Business_line__c = 'SW'));
			programs.add(new Program__c(Name = 'TestProgramPT', Business_line__c = 'PT'));
            
			insert programs;

            //insert the Main contact record
            Contact mainContact = new Contact(LastName = 'TestLastName', AccountId = institution.Id, Record_Type__c = listRecordType[0].Name);
            insert mainContact;
            
            //Insert Contracts
			List<Contract__c> contracts = new List<Contract__c>();
			contracts.add(new Contract__c(Negotiated_Amount__c = 100, Type__c = 'Test', Start__c = Date.today(), End__c = Date.today(), 
                                            Year__c = '2011', Program__c = programs[0].Id, Join_Date__c = Date.today(),  
                                            Main_Contact__c = mainContact.Id, Invoice_Contact__c = mainContact.Id,
                                            Status__c = Constants.STATUS_ATL, Payer_Account__c = institution.Id, Invoice_Billing_Schedule__c = invoiceBillingSchedule.Id));

            contracts.add(new Contract__c(Negotiated_Amount__c = 100, Type__c = 'Test', Start__c = Date.today(), End__c = Date.today(), 
											Year__c = '2011', Program__c = programs[1].Id, Join_Date__c = Date.today(),  
                                            Main_Contact__c = mainContact.Id, Invoice_Contact__c = mainContact.Id,
                                            Status__c = Constants.STATUS_ATL, Payer_Account__c = institution.Id));
            
			//Insert the Contracts
            insert contracts;
            
            //Insert Line Item Schedule test data
            List<Line_Item_Schedule__c> listLIS = new List<Line_Item_Schedule__c>();
            listLIS.add(new Line_Item_Schedule__c(Contract__c = contracts[0].Id, Invoice_Billing_Schedule_del__c = invoiceBillingSchedule.Id, 
													Type__c = 'Test', Invoice_Date__c = Date.today(), Invoice_Comment__c = 'Test', 
                                                    Amount__c = 20));
            insert listLIS;
            
            //start test from here 
            Test.startTest();
            
            //initiate controller
            AddContractsToInvoiceBillingSchedule controller = new AddContractsToInvoiceBillingSchedule(new ApexPages.StandardController(invoiceBillingSchedule));
            
            //assert for the constructor result
            System.assertEquals(1, controller.listContractABCWrapper.size());
            
			//mark the wrapper record selected
            controller.listContractABCWrapper[0].selected = true;
            Id tempContractId = controller.listContractABCWrapper[0].contractABC.Id;
            
            //call add contract method
            controller.addContracts();
            
            //fecth the contract back and assert the result
            List<Contract__c> contractsOnIBS = [Select Invoice_Billing_Schedule__c, Invoice_Billing_Schedule__r.Division__c from Contract__c where Id =: tempContractId];
            System.assertEquals(invoiceBillingSchedule.Id, contractsOnIBS[0].Invoice_Billing_Schedule__c);
			System.assertEquals('CLN', contractsOnIBS[0].Invoice_Billing_Schedule__r.Division__c);
            
			//Update and insert the Contracts
			contracts[0].Program__c = programs[1].Id;
            contracts.add(new Contract__c(Negotiated_Amount__c = 100, Type__c = 'Test', Start__c = Date.today(), End__c = Date.today(), 
                                                        Year__c = '2011', Program__c = programs[2].Id, Join_Date__c = Date.today(),  
                                                        Main_Contact__c = mainContact.Id, Invoice_Contact__c = mainContact.Id,
                                                        Status__c = Constants.STATUS_ATL, Payer_Account__c = institution.Id));
			upsert contracts;
            
			//Insert Line Item Schedule for Contract
            listLIS.add(new Line_Item_Schedule__c(Contract__c = contracts[1].Id, Invoice_Billing_Schedule_del__c = invoiceBillingSchedule.Id, 
													Type__c = 'Test', Invoice_Date__c = Date.today(), Invoice_Comment__c = 'Test', 
                                                    Amount__c = 20));
            insert listLIS[1];
            
            //initiate controller
            controller = new AddContractsToInvoiceBillingSchedule(new ApexPages.StandardController(invoiceBillingSchedule));
            
            //assert for the constructor result
            System.assertEquals(1, controller.listContractABCWrapper.size());
            
			//mark the wrapper record selected
            controller.listContractABCWrapper[0].selected = true;
            
            //call add contract method
            controller.addContracts();
            
            //fecth the contract back and assert the result
            contractsOnIBS = [Select Invoice_Billing_Schedule__c, Invoice_Billing_Schedule__r.Division__c from Contract__c where Id IN: contracts];
            System.assertEquals('SW', contractsOnIBS[0].Invoice_Billing_Schedule__r.Division__c);
            
            //Insert Line Item Schedule for Contract
            listLIS.add(new Line_Item_Schedule__c(Contract__c = contracts[2].Id, Invoice_Billing_Schedule_del__c = invoiceBillingSchedule.Id, 
													Type__c = 'Test', Invoice_Date__c = Date.today(), Invoice_Comment__c = 'Test', 
                                                    Amount__c = 20));
            insert listLIS[2];
            
			//Insert new Contract
			Contract__c contractABC = new Contract__c(Negotiated_Amount__c = 100, Type__c = 'Test', Start__c = Date.today(), End__c = Date.today(), 
                                                        Year__c = '2011', Program__c = programs[2].Id, Join_Date__c = Date.today(),  
                                                        Main_Contact__c = mainContact.Id, Invoice_Contact__c = mainContact.Id,
                                                        Status__c = Constants.STATUS_ATL, Payer_Account__c = institution.Id);
			insert contractABC;

			//initiate controller
            controller = new AddContractsToInvoiceBillingSchedule(new ApexPages.StandardController(invoiceBillingSchedule));
            
            //assert for the constructor result
            System.assertEquals(1, controller.listContractABCWrapper.size());
            
			//mark the wrapper record selected
            controller.listContractABCWrapper[0].selected = true;
            
            //call add contract method
            controller.addContracts();
            
            //fecth the contract back and assert the result
            contractsOnIBS = [Select Invoice_Billing_Schedule__c, Invoice_Billing_Schedule__r.Division__c from Contract__c where Id IN: contracts];
            System.assertEquals('ABC Corporate', contractsOnIBS[0].Invoice_Billing_Schedule__r.Division__c);

            //stop test here
            Test.stopTest();
        }
    }
    
}