objects/Contract__c.object
<CustomObject>
    <label>Contract ABC</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts ABC</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract_Docs_to_Opps_MtM__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Documents__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Documents</label>
        <referenceTo>Contract_Document__c</referenceTo>
        <relationshipLabel>Opps with This Contract Document</relationshipLabel>
        <relationshipName>Contract_Docs_to_Opps_MtMs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts Docs for this Opp</relationshipLabel>
        <relationshipName>Contract_Docs_to_Opps_MtMs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Docs to Opps MtM</label>
    <nameField>
        <label>Contract Docs to Opps MtM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Docs to Opps MtMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract Documents</relationshipLabel>
        <relationshipName>Contract_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Contract Document</label>
    <nameField>
        <label>Contract Document</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contracts_to_Contract_Docs_MtM__c.object
<CustomObject>
    <fields>
        <fullName>Contracts_ABC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contracts</label>
        <referenceTo>Contract__c</referenceTo>
        <relationshipLabel>Contract Docs on this Contract</relationshipLabel>
        <relationshipName>Contracts_to_Contract_Docs_MtMs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contracts to Contract Docs  MtM</label>
    <nameField>
        <label>Contracts to Contract Docs  MtM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts to Contract Docs  MtMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testContractsToContractDocsMTMUtilities.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class testContractsToContractDocsMTMUtilities {

    static testmethod void testCreateNewDoc() { 
        //Bypass Dupeblocker
        Util.IsTest(true);
        // Create a new contract_ABC record
        Contract__c contract = TestUtilities.CreateNewContract(true);
        // Create a new opportunity (this opportunity is 'booked' from the contract)
        Opportunity opp = TestUtilities.CreateNewOpportunity(false);
        opp.Signed_Opportunity_Contract__c = contract.Id;
        insert opp;
        
        Contract_Document__c conDoc = new Contract_Document__c(Account__c = opp.AccountId, Name__c='testdoc1');
        insert conDoc;
        
        /** start test **/
        test.startTest();
        // create a contract to document mtm record
        Contract_Docs_to_Opps_MtM__c docMTM = new Contract_Docs_to_Opps_MtM__c(Opportunity__c = opp.Id, Contract_Documents__c = conDoc.Id);
        insert docMTM;
        // now that the record is inserted, the opportunity related to this contract
        // should have this new Contract doc MTM record associated with it
        test.stopTest();
        /** stop test **/
        
        List<Contract_Docs_to_Opps_MtM__c> contractToOppsMTM = [SELECT Id FROM Contract_Docs_to_Opps_MtM__c WHERE Opportunity__c = :opp.Id];
        system.assertEquals(1, contractToOppsMTM.size());
    }
    
    static testmethod void testAddDocsToContract() { 
        //Bypass Dupeblocker
        Util.IsTest(true);
        // Create a new contract_ABC record
        Contract__c contract = TestUtilities.CreateNewContract(true);
        // Create a new opportunity (this opportunity is 'booked' from the contract)
        Opportunity opp = TestUtilities.CreateNewOpportunity(false);
        opp.Signed_Opportunity_Contract__c = contract.Id;
        insert opp;
        
        Contract_Document__c conDoc = new Contract_Document__c(Account__c = opp.AccountId, Name__c='testdoc1');
        insert conDoc;
        
        /** start test **/
        test.startTest();
        // create a contract doc to Opp mtm record
        Contract_Docs_to_Opps_MtM__c docMTM = new Contract_Docs_to_Opps_MtM__c(Opportunity__c = opp.Id, Contract_Documents__c = conDoc.Id);
        insert docMTM;
        // now that the record is inserted, the opportunity related to this contract
        // should have this new Contract doc MTM record associated with it
        test.stopTest();
        /** stop test **/
        
        List<Contracts_to_Contract_Docs_MtM__c> conToConDocs = [SELECT Id FROM Contracts_to_Contract_Docs_MtM__c WHERE Contracts_ABC__c = :contract.Id];
        system.assertEquals(1, conToConDocs.size());
    }
}