objects/Credit_Card__c.object
<CustomObject>
    <description>A credit card or payment authorization</description>
    <fields>
        <fullName>Card_Employee_Number__c</fullName>
        <label>Card Employee Number</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <description>Used to store the encrypted card number in a plain text field so it can be used in formulas, etc</description>
        <label>Card Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Requested_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <label>Card Requested By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Credit Cards</relationshipLabel>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee_Id__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <inlineHelpText>Employee Finance Code Id</inlineHelpText>
        <label>zzzEmployee Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Account__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <label>Portfolio</label>
        <referenceTo>Portfolio__c</referenceTo>
        <relationshipLabel>Credit Cards</relationshipLabel>
        <relationshipName>Credit_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <label>Advisory Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Card</label>
    <nameField>
        <label>Credit Card Record</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Credit_Card_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <inlineHelpText>Set to &apos;Active&apos; to make this the active set of settings (Only one may be set as Active)</inlineHelpText>
        <label>Status</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Credit Card Settings</label>
    <nameField>
        <label>Credit Card Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Card Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OSR__c.object
<CustomObject>
    <description>Operational Service Request</description>
    <fields>
        <fullName>Alert_Message__c</fullName>
        <description>This field is to store the email body of a Credit Card Alert message, which is received by the CreditCardAlertService Apex Email Service.
        
        Origin: CR-2089 - CreditCardAdmin</description>
        <inlineHelpText>Body of alert email message</inlineHelpText>
        <label>Alert Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alert_Summary__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <label>Alert Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Employee_Number__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <formula>IF(NOT(ISBLANK(Related_Card__c)),Related_Card__r.Card_Employee_Number__c,&apos;&apos;)</formula>
        <label>Card Employee Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <formula>IF( NOT(  ISBLANK(Related_Card__r.Card_Number__c) ) , &apos;XXXX-XXXX-XXXX-&apos;+RIGHT(Related_Card__r.Card_Number__c, 4), &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>zzzCard Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Updated by Credit Card Request from Travel Portal
        
        Origin: CR-2089 - CreditCardAdmin</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>OSR</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>OSR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OSRs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Portfolio__c.object
<CustomObject>
    <description>Contains details of all credit cards or payment authorization agreements that person is responsible for.  One record per person, or per group responsible for a Meeting series</description>
    <fields>
        <fullName>Card_Holder__c</fullName>
        <label>Card Holder</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Credit Portfolios (Card Holder)</relationshipLabel>
        <relationshipName>Credit_Portfolios</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Portfolio_Owner_Finance_Code__c</fullName>
        <description>Populate from Contact - Contact.Employee User Record.Finance Code
        
        Origin: CR-2089 - CreditCardAdmin</description>
        <externalId>true</externalId>
        <label>Portfolio Owner Finance Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Activated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit Portfolio</label>
    <nameField>
        <label>Portfolio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_CreditCardAlertService.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_CreditCardAlertService {
/**
 *  Purpose         :   This class is used for testing CreditCardAlertService class.
 *
 *  Created By      :   Bhavi Sharma
 *
 *  Created Date    :   09/07/2013
 *
 *  Current Version :   V_1.0 - Created
 *
 **/
    
    //Test method
    static testmethod void testInboundCreateOSR() {
        
        //query result of RecordTypes
        List<RecordType> recordTypes = [SELECT Id, DeveloperName FROM RecordType 
                                            WHERE (SobjectType = 'Account' OR SobjectType = 'Contact') 
                                                    AND (DeveloperName = 'US_Provider' OR DeveloperName = 'Employee') 
                                                    AND IsActive = true ORDER BY SobjectType];
        
        //assert statement
        System.assertEquals(2, recordTypes.size());
        
        //insert Account record
        Account account = new Account(Name = 'Test Account', RecordTypeId = recordTypes[0].Id, Status__c = 'Active');
        insert account;
        
        //insert Contact record
        List<Contact> contacts = new List<Contact>();
        contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact', AccountId = account.Id, RecordTypeId = recordTypes[1].Id, Employee_ID__c = '23456'));
        contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact', AccountId = account.Id, RecordTypeId = recordTypes[1].Id, Employee_ID__c = '55673560'));
        
        insert contacts;
        
        //insert Credit Card Settings record
        Credit_Card_Settings__c ccDefaultSetting = CreditCardConstants.CONFIG_DEFAULT;
        
        //Payment Account record
        List<Portfolio__c> payments = new List<Portfolio__c>();
        payments.add(new Portfolio__c(Status__c = Constants.ACTIVE, Card_Holder__c = contacts[0].Id, Portfolio_Owner_Finance_Code__c = '678981'));
        payments.add(new Portfolio__c(Status__c = Constants.ACTIVE, Card_Holder__c = contacts[1].Id, Portfolio_Owner_Finance_Code__c = '678941'));
        insert payments;
        
        //Encrypt Card Number String
        String encryptCardNumber1 = CreditCardService.Encrypt('5567356025410287');
        String encryptCardNumber2 = CreditCardService.Encrypt('5567356025413426');
        
        //Credit Card record
        List<Credit_Card__c> cards = new List<Credit_Card__c>(); 
        cards.add(new Credit_Card__c(Card_Number__c = encryptCardNumber1, Card_Employee_Number__c = '55673560', Status__c = 'Active', Card_Requested_By__c = contacts[0].Id, Payment_Account__c = payments[0].Id));
        cards.add(new Credit_Card__c(Card_Number__c = encryptCardNumber2, Card_Employee_Number__c = '23456', Status__c = 'Active', Card_Requested_By__c = contacts[0].Id, Payment_Account__c = payments[1].Id));
        insert cards;
                                                                                        
        // Create a new email, envelope object 
        Messaging.InboundEmail email1 = new Messaging.InboundEmail();
        Messaging.InboundEnvelope envelop1 = new Messaging.InboundEnvelope();
        email1.subject = 'This is Fraud credit card.'+ Math.random();
        envelop1.fromAddress = 'user@gmail.com';
        email1.PlainTextBody = 'This is fraud credit card.'+ '\n' + 'Employee ID: 55673560'+ '\n';
        
        // Create a new email, envelope object 
        Messaging.InboundEmail email2 = new Messaging.InboundEmail();
        Messaging.InboundEnvelope envelop2 = new Messaging.InboundEnvelope();
        email2.subject = 'This is Decline credit card.'+ Math.random();
        envelop2.fromAddress = 'user@gmail.com';
        email2.PlainTextBody = 'This is Decline credit card.'+ '\n' + 'Employee ID: 23456'+ '\n';
        
        // Create a new email, envelope object 
        Messaging.InboundEmail email3 = new Messaging.InboundEmail();
        Messaging.InboundEnvelope envelop3 = new Messaging.InboundEnvelope();
        email3.subject = 'This is Declined credit card.'+ Math.random();
        envelop3.fromAddress = 'user@gmail.com';
        email3.PlainTextBody = 'This is Declined credit card.';
        
        // Create a new email, envelope object 
        Messaging.InboundEmail email4 = new Messaging.InboundEmail();
        Messaging.InboundEnvelope envelop4 = new Messaging.InboundEnvelope();
        email4.subject = 'This is Declined credit card.'+ Math.random();
        envelop4.fromAddress = 'user@gmail.com';
        email4.PlainTextBody = 'This is Declined credit card.'+ '\n' + 'Card Number: 5567356025413426'+ '\n';
        
        //Test starts here
        Test.startTest();
        
        // call the class and test it with the data in the testMethod
        CreditCardAlertService creditAlertSrvc = new CreditCardAlertService();
        creditAlertSrvc.handleInboundEmail(email1, envelop1);  
        creditAlertSrvc.handleInboundEmail(email2, envelop2);  
        creditAlertSrvc.handleInboundEmail(email3, envelop3);  
        creditAlertSrvc.handleInboundEmail(email4, envelop4);  
        
        //query Result of OSR record
        List<OSR__c> oSRs = [SELECT Id, Alert_Message__c FROM OSR__c WHERE Alert_Summary__c =: email1.subject OR Alert_Summary__c =: email2.subject
                                    OR Alert_Summary__c =: email3.subject OR Alert_Summary__c =: email4.subject];
        
        //assert statement
        System.assertEquals(2, oSRs.size());
        
        //Test stops here
        Test.stopTest();
    }
}