objects/Deployment__c.object
<CustomObject>
    <description>This object will show the project deployment details including the schedule.</description>
    <fields>
        <fullName>CMA_Status_Formula__c</fullName>
        <formula>IF(OR(AND(BLANKVALUE(C_A_DC__c,Actual_Initial_Site_Demo__c)&lt;C_E_DC__c, BLANKVALUE(C_A_DC__c,TODAY())&lt;C_E_DC__c, Actual_Initial_Site_Demo__c&lt;=TODAY()),C_A_DC__c&lt;TODAY()),
&quot;Green&quot;,
IF(AND(BLANKVALUE(C_A_DC__c, TODAY()) &gt; C_E_DC__c + 28, NOT ISBLANK(Actual_Initial_Site_Demo__c), Actual_Initial_Site_Demo__c&lt;=TODAY()),
&quot;Red&quot;,
IF(AND(BLANKVALUE(C_A_DC__c, TODAY()) &gt; C_E_DC__c, NOT ISBLANK(Actual_Initial_Site_Demo__c), Actual_Initial_Site_Demo__c&lt;=TODAY()),
&quot;Yellow&quot;,
IF(AND(BLANKVALUE(Actual_Initial_Site_Demo__c,C_A_IVC__c)&lt;Initial_Site_Demo_Exp__c, BLANKVALUE(Actual_Initial_Site_Demo__c,TODAY())&lt;Initial_Site_Demo_Exp__c, C_A_IVC__c&lt;=TODAY()),
&quot;Green&quot;,
IF(AND(BLANKVALUE(Actual_Initial_Site_Demo__c, TODAY()) &gt; C_E_DC__c, NOT ISBLANK(C_A_IVC__c), C_A_IVC__c&lt;=TODAY()),
&quot;Red&quot;,
IF(AND(BLANKVALUE(Actual_Initial_Site_Demo__c, TODAY()) &gt; Initial_Site_Demo_Exp__c, NOT ISBLANK(C_A_IVC__c), C_A_IVC__c&lt;=TODAY()),
&quot;Yellow&quot;,
IF(AND(BLANKVALUE(C_A_IVC__c,C_A_DDC__c)&lt;C_E_IVC__c, BLANKVALUE(C_A_IVC__c,TODAY())&lt;C_E_IVC__c, C_A_DDC__c&lt;=TODAY()),
&quot;Green&quot;,
IF(AND(BLANKVALUE(C_A_IVC__c, TODAY()) &gt; Initial_Site_Demo_Exp__c, NOT ISBLANK(C_A_DDC__c), C_A_DDC__c&lt;=TODAY()),
&quot;Red&quot;,
IF(AND(BLANKVALUE(C_A_IVC__c, TODAY()) &gt; C_E_IVC__c, NOT ISBLANK(C_A_DDC__c), C_A_DDC__c&lt;=TODAY()),
&quot;Yellow&quot;,
IF(AND(BLANKVALUE(C_A_DDC__c,Feedback_on_Initial_Data_Actual__c)&lt;C_E_DDC__c, BLANKVALUE(C_A_DDC__c,TODAY())&lt;C_E_DDC__c, Feedback_on_Initial_Data_Actual__c&lt;=TODAY()),
&quot;Green&quot;,
IF(AND(BLANKVALUE(C_A_DDC__c, TODAY()) &gt; C_E_IVC__c, NOT ISBLANK(Feedback_on_Initial_Data_Actual__c), Feedback_on_Initial_Data_Actual__c&lt;=TODAY()),
&quot;Red&quot;,
IF(AND(BLANKVALUE(C_A_DDC__c, TODAY()) &gt; C_E_DDC__c, NOT ISBLANK(Feedback_on_Initial_Data_Actual__c), Feedback_on_Initial_Data_Actual__c&lt;=TODAY()),
&quot;Yellow&quot;,
IF(AND(BLANKVALUE(Feedback_on_Initial_Data_Actual__c,C_A_TPC__c)&lt;Feedback_on_Initial_Data_Expected__c, BLANKVALUE(Feedback_on_Initial_Data_Actual__c,TODAY())&lt;Feedback_on_Initial_Data_Expected__c, C_A_TPC__c&lt;=TODAY()),
&quot;Green&quot;,
IF(AND(BLANKVALUE(Feedback_on_Initial_Data_Actual__c, TODAY()) &gt; C_E_DDC__c, NOT ISBLANK(C_A_TPC__c), C_A_TPC__c&lt;=TODAY()),
&quot;Red&quot;,
IF(AND(BLANKVALUE(Feedback_on_Initial_Data_Actual__c, TODAY()) &gt; Feedback_on_Initial_Data_Expected__c, NOT ISBLANK(C_A_TPC__c), C_A_TPC__c&lt;=TODAY()),
&quot;Yellow&quot;,
IF(AND(C_A_TPC__c&lt;=C_E_TPC__c, NOT ISBLANK(C_A_TPC__c)),
&quot;Green&quot;,
IF(BLANKVALUE(C_A_TPC__c, TODAY()) &gt; Feedback_on_Initial_Data_Expected__c,
&quot;Red&quot;,
IF(BLANKVALUE(C_A_TPC__c, TODAY()) &gt; C_E_TPC__c,
&quot;Yellow&quot;,
&quot;Future/On Hold&quot;))))))))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Deployment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPM_Deployment_Status__c</fullName>
        <inlineHelpText>Subjective deployment status as agreed upon by deployment team.</inlineHelpText>
        <label>Deployment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
                <color>#A53711</color>
            </picklistValues>
            <picklistValues>
                <fullName>Future/On Hold</fullName>
                <color>#666666</color>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>C_A_DC__c</fullName>
        <description>Phase 4 milestone field common to all Crimson products</description>
        <inlineHelpText>Date site is moved to production</inlineHelpText>
        <label>Deployment Sign Off (Actual)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>C_A_DS__c</fullName>
        <description>Phase I milestone field common to all Crimson products</description>
        <label>Deployment Start (Actual)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deployment_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select type of deployment to control milestones and internal deployment targets</inlineHelpText>
        <label>Deployment Type</label>
        <referenceTo>Deployment_Type__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment_Type__c.object
<CustomObject>
    <description>This object will contain attributes of deployments for different BI products. A unique record of this object type will need to be created for each product that requires custom thresholds for milestones.</description>
    <label>Deployment Type</label>
    <nameField>
        <label>Deployment Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_BatchUpdateDeploymentStatus.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
*/
@isTest
private class Test_BatchUpdateDeploymentStatus {
/**
 *	Purpose			:	Test class for Batch_UpdateDeploymentStatus
 *
 *	Created By		:	Bhavi Sharma
 *
 *	Created Date	:	05/14/2013
 *
 *	Revision Logs	:	V_1.0 - Created
 *
 *	Coverage		:	100% 	
 *
 **/ 
    static testMethod void myUnitTest() {
        
        //select Record types
		Id recordtypeId = [select id from RecordType where SObjectType = 'Deployment__c' and Name = :Constants.RECORD_TYPE_DEPLOYMENT_CMA_DEPLOYMENT].id;

		//Project type record
		Project__c project = new Project__c(Name = 'ProjectDemo');

		//Insert Project record
		insert project;

		//Deployment type record
		Deployment_Type__c deploy = new Deployment_Type__c(Name = 'Test Deployment Type');

		//insert
		insert deploy;

		//Deployment record
		//Create a list of deployment records to be inserted
		List<Deployment__c> deployments = new List<Deployment__c>();
		deployments.add(new Deployment__c(Name = 'DeploymentDemo1', Project__c = project.Id,Deployment_Type__c = deploy.Id, C_A_DS__c = Date.today(),
														CPM_Deployment_Status__c = 'Green', C_A_DC__c = Date.today()-2, RecordTypeId = recordtypeId));
		deployments.add(new Deployment__c(Name = 'DeploymentDemo2', Project__c = project.Id,Deployment_Type__c = deploy.Id, C_A_DS__c = Date.today(),
														CPM_Deployment_Status__c = 'Red', C_A_DC__c = Date.today()-2, RecordTypeId = recordtypeId));

		//Insert 
		insert deployments;
		
		//Start Test form here
		Test.StartTest();

		//Execute Batch job
		Database.executeBatch(new Batch_UpdateDeploymentStatus());

		//stop Test here
		Test.StopTest();

		//assert for the results
		for(Deployment__c deployment : [Select Id, CMA_Status_Formula__c, CPM_Deployment_Status__c from Deployment__c where Id IN: deployments]) {
		
			//assert statement
			System.assertEquals(deployment.CMA_Status_Formula__c, deployment.CPM_Deployment_Status__c);
		}
    }
}