objects/DP_Picklist__c.object
<CustomObject>
    <description>The Picklist custom object will contain the list of available dynamic picklists.  The Alpha Sort attribute is TRUE if the items are sorted alphabetically.  When FALSE, the sort order must be specified in the PicklistEntry custom object.</description>
    <fields>
        <fullName>Alpha_Sort__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Set to TRUE if the list items should be alphabetically sorted</inlineHelpText>
        <label>Alpha Sort</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Person who is most knowledgeable about this picklist</inlineHelpText>
        <label>Business Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Picklists</relationshipLabel>
        <relationshipName>Picklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Original_CR__c</fullName>
        <label>Original CR</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Picklist</label>
    <nameField>
        <label>Picklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DP_Picklist_Dependency__c.object
<CustomObject>
    <fields>
        <fullName>Controlling_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Controlling Entry</label>
        <referenceTo>DP_Picklist_Entry__c</referenceTo>
        <relationshipLabel>Picklist Dependencies (Controlling Values)</relationshipLabel>
        <relationshipName>Picklist_Dependencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dependent_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Entry</label>
        <referenceTo>DP_Picklist_Entry__c</referenceTo>
        <relationshipLabel>Picklist Dependencies (Dependent Values)</relationshipLabel>
        <relationshipName>Picklist_Dependencies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dependent_Picklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which picklist contains the values being limited?</inlineHelpText>
        <label>Dependent Picklist</label>
        <referenceTo>DP_Picklist__c</referenceTo>
        <relationshipLabel>Picklist Dependencies</relationshipLabel>
        <relationshipName>Picklist_Dependencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Picklist Dependency</label>
    <nameField>
        <displayFormat>PLD-{00000000}</displayFormat>
        <label>Picklist Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Dependencies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DP_Picklist_Entry__c.object
<CustomObject>
    <description>The Picklist Entry custom object will contain the actual picklist values that will be available for selection.  The Sort Order field is used to set the order when the Alpha Sort option on the Picklist is FALSE.  The Active field can be used to hide a picklist value and keep it in the list if needed for historical reasons.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <inlineHelpText>Value as it will appear in a picklist selection list</inlineHelpText>
        <label>Display Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist</label>
        <referenceTo>DP_Picklist__c</referenceTo>
        <relationshipLabel>Picklist Entries</relationshipLabel>
        <relationshipName>Picklist_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <inlineHelpText>Used to sort the list when/if Alpha Sort on the main Picklist is False.</inlineHelpText>
        <label>Sort Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Picklist Entry</label>
    <nameField>
        <label>Picklist Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/DP_Picklist_Usage__c.object
<CustomObject>
    <description>The Picklist Usage custom object will contain the location (object and field) of where the dynamic picklist is used. This will also contain the field location of a controlling value for the picklist</description>
    <fields>
        <fullName>Controlling_Field__c</fullName>
        <inlineHelpText>Field which contains a value that limits the available values for this picklist.  The field must be on the same object as the picklist usage.</inlineHelpText>
        <label>Controlling Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <inlineHelpText>API Name of the Field where this picklist is used</inlineHelpText>
        <label>Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <inlineHelpText>API Name of the Object where this picklist is used</inlineHelpText>
        <label>Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Picklist</label>
        <referenceTo>DP_Picklist__c</referenceTo>
        <relationshipLabel>Picklist Usages</relationshipLabel>
        <relationshipName>Picklist_Usages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type_Dependent__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Are the values for this picklist usage limited by record type?</inlineHelpText>
        <label>Record Type Dependent?</label>
        <type>Checkbox</type>
    </fields>
    <label>Picklist Usage</label>
    <nameField>
        <displayFormat>PLU-{000000}</displayFormat>
        <label>Picklist Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Usages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Picklist__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The Picklist custom setting will contain the list of available dynamic picklists.  The Alpha Sort attribute is TRUE if the items are sorted alphabetically.  When FALSE, the sort order must be specified in the PicklistEntry custom setting.</description>
    <fields>
        <fullName>Alpha_Sort__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Are the picklist values sorted alphabetically?</inlineHelpText>
        <label>Alpha Sort</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>Picklist</label>
</CustomObject>

objects/Reference__c.object
<CustomObject>
    <fields>
        <fullName>Attribute_A__c</fullName>
        <label>Attribute A</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Module__c</fullName>
        <label>Reference Module</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Reference</label>
    <nameField>
        <displayFormat>Ref-{000000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Reference_Request__c.object
<CustomObject>
    <description>This object is used to track the request for a reference or references.</description>
    <label>Reference Request</label>
    <nameField>
        <displayFormat>RefReq-{00000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_PicklistHelper.cls
@isTest
public class Test_PicklistHelper {
    
    /**
    * @description: create the dynamic picklists
    **/
    @TestVisible private static void createDynamicPicklist() {
        //get businses owner id
        Id businessOwnerId = userInfo.getUserId();
        //create picklists
        list<DP_Picklist__c> dpPicklists = new list<DP_Picklist__c>();
        DP_Picklist__c attribute = new DP_Picklist__c(Name='Attribute',
                                                      Description__c='A general list of property names',
                                                      Alpha_Sort__c=true,
                                                      Original_CR__c='CR-2015-0826-9191',
                                                      Business_Owner__c=businessOwnerId);
        DP_Picklist__c attributeValue = new DP_Picklist__c(Name='Attribute Value',
                                                           Description__c='A general list of property names',
                                                           Alpha_Sort__c=true,
                                                           Original_CR__c='CR-2015-0826-9191',
                                                           Business_Owner__c=businessOwnerId);
        dpPicklists.add(attribute);
        dpPicklists.add(attributeValue);
        insert dpPicklists;
        
        //create picklist entries
        list<DP_Picklist_Entry__c> dpPicklistEntries = new list<DP_Picklist_Entry__c>();
        DP_Picklist_Entry__c MultiRegionalHealthSystem = new DP_Picklist_Entry__c(Name='MultiRegionalHealthSystem',
                                                                                Display_Name__c='Multi/Regional Health System',
                                                                                Picklist__c=attribute.Id,
                                                                                Object__c='',
                                                                                Active__c=true);
        dpPicklistEntries.add(MultiRegionalHealthSystem);
        DP_Picklist_Entry__c SmallRural = new DP_Picklist_Entry__c(Name='SmallRural',
                                                                                Display_Name__c='Small Rural',
                                                                                Picklist__c=attribute.Id,
                                                                                Object__c='',
                                                                                Active__c=true);
        dpPicklistEntries.add(SmallRural);
        DP_Picklist_Entry__c Size = new DP_Picklist_Entry__c(Name='Size',
                                                            Display_Name__c='Size',
                                                            Picklist__c=attribute.Id,
                                                            Object__c='',
                                                            Active__c=true);
        dpPicklistEntries.add(Size);
        insert dpPicklistEntries;
        
        //create picklist usages
        list<DP_Picklist_Usage__c> dpPicklistUsages = new list<DP_Picklist_Usage__c>();
        DP_Picklist_Usage__c pluAttribute_A = new DP_Picklist_Usage__c(Picklist__c=attribute.Id,
                                                                       Object__c='Reference__c',
                                                                       Field__c='Field_A__c',
                                                                       Controlling_Field__c='Reference_Module__c',
                                                                       Record_Type_Dependent__c=true);
        dpPicklistUsages.add(pluAttribute_A);
        
        //reference request
        DP_Picklist_Usage__c pluReference_Attributes = new DP_Picklist_Usage__c(Picklist__c=attribute.Id,
                                                                                Object__c='Reference_Request__c',
                                                                                Field__c='Reference_Attributes__c',
                                                                                Controlling_Field__c='Reference_Products__c',
                                                                                Record_Type_Dependent__c=true);
        dpPicklistUsages.add(pluReference_Attributes);
        //attribute values
        DP_Picklist_Usage__c pluAttribute_Val_A = new DP_Picklist_Usage__c(Picklist__c=attributeValue.Id,
                                                                           Object__c='Reference__c',
                                                                           Field__c='Attribute_Value_A__c',
                                                                           Controlling_Field__c='Attribute_A__c',
                                                                           Record_Type_Dependent__c=true);
        dpPicklistUsages.add(pluAttribute_Val_A);
        
        //reference attributes
        DP_Picklist_Usage__c pluReference_Attributes_2 = new DP_Picklist_Usage__c(Picklist__c=attributeValue.Id,
                                                                                  Object__c='Reference_Request__c',
                                                                                  Field__c='Reference_Attributes__c',
                                                                                  Controlling_Field__c='Reference_Attributes__c',
                                                                                  Record_Type_Dependent__c=true);
        dpPicklistUsages.add(pluReference_Attributes_2);
        
        insert dpPicklistUsages;
        
        //create Picklist Dependencies
        list<DP_Picklist_Dependency__c> dpDependencies = new list<DP_Picklist_Dependency__c>();
        DP_Picklist_Dependency__c pdSize_MultiRegionalHealthSystem = new DP_Picklist_Dependency__c(Dependent_Picklist__c=attribute.Id,
                                                                                               Controlling_Entry__c=Size.Id,
                                                                                               Dependent_Entry__c=MultiRegionalHealthSystem.Id);
        dpDependencies.add(pdSize_MultiRegionalHealthSystem);
        DP_Picklist_Dependency__c pdSize_SmallRural = new DP_Picklist_Dependency__c(Dependent_Picklist__c=attribute.Id,
                                                                                               Controlling_Entry__c=Size.Id,
                                                                                               Dependent_Entry__c=SmallRural.Id);
        dpDependencies.add(pdSize_SmallRural);
        
        
        insert dpDependencies;
    }
    
    /**
     * @description: setup the test data
     **/
    @testSetup static void setup() {
        createDynamicPicklist();
    }
    
    /**
     * @description: test the dynamic picklist helper class and verify both alpha and custom sort orders.
     **/
    static testMethod void testPicklist() {
        //get the dependent picklist map
        map<string, list<PicklistHelper.PicklistWrapper>> picklistDependencyMap = new PicklistHelper('Reference__c', 'Field_A__c', 'Picklist Usage').getWrapperMap();
        system.assertEquals(1, picklistDependencyMap.size());
        //if the user selects reference module Size, the first attribute value should be Multi/Regional Health System
        list<PicklistHelper.PicklistWrapper> attributes = picklistDependencyMap.get('Size');
        system.assertEquals('Multi/Regional Health System', attributes[0].displayName, 'if the user selects reference module Size, the first attribute value should be Multi/Regional Health System (Alpha sort)');
        
        //change the sort to custom
        list<DP_Picklist__c>  picklists = [SELECT Id, Alpha_Sort__c FROM DP_Picklist__c];
        for (DP_Picklist__c p : picklists) p.Alpha_Sort__c = false;
        update picklists;
        
        //update the custom sort order to reverse the previous (alpha) order
        list<DP_Picklist_Entry__c> entries = [SELECT Id, Name, Sort_Order__c FROM DP_Picklist_Entry__c];
        for (DP_Picklist_Entry__c e : entries) {
            if (e.Name == 'SmallRural') e.Sort_Order__c = 1;
            else if (e.Name == 'MultiRegionalHealthSystem') e.Sort_Order__c = 2;
        }
        update entries;
        
        picklistDependencyMap = new PicklistHelper('Reference__c', 'Field_A__c', 'Picklist Usage').getWrapperMap();
        //if the user selects reference module Size, the first attribute value should be SmallRural, due to the custom sort order
        attributes = picklistDependencyMap.get('Size');
        system.assertEquals('Small Rural', attributes[0].displayName, 'if the user selects reference module Size, the first attribute value should be SmallRural (Custom sort)');
        
    }
}