objects/Incentive_Change_Batch__c.object
<CustomObject>
    <description>After S&amp;O completes a series of changes for a particular exercise (moving a Program from one Collection Perspective to another, for example), they will group the logged changes together into batches, so each Incentive Change Log record will be collected into a batch. They will then search for Individual Goal impacts of that batch of changes.
Once modifications have been applied to represent that batch of changes, the batch and its underlying log records will be marked as having been applied and will no longer be eligible for batching.</description>
    <label>Incentive Change Batch</label>
    <nameField>
        <label>Incentive Change Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Change Batches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Incentive_Change_Log__c.object
<CustomObject>
    <description>We will create a record in the Incentive Change Log for each Incentive-impacting change to related meta-data (such as Program Collection, Collection Perspective, etc.). These records will be grouped by S&amp;O users into Incentive Change Batches, which will be used as the basis for identifying affected Individual Goals.
These records can only be created or modified by the system under program control (specifically, triggers on the related objects).</description>
    <fields>
        <fullName>Incentive_Change_Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incentive Change Batch</label>
        <referenceTo>Incentive_Change_Batch__c</referenceTo>
        <relationshipLabel>Incentive Change Logs</relationshipLabel>
        <relationshipName>Incentive_Change_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Incentive Change Log</label>
    <nameField>
        <displayFormat>ICL{0}</displayFormat>
        <label>Incentive Change Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Change Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CreateChangeBatchController.cls
/*
 *	Purpose			:	This class is to control the functionality of adding new Change Batch
 *                  
 *  Create By       :   Subhash Garhwal
 *  
 *  Created Date    :   09/29/2015
 *  
 *  Revision Log    :   V_1.0 Created - CR-20150729-9114
 *                      
 **/
public with sharing class CreateChangeBatchController {
	
	//Variables
	public Incentive_Change_Batch__c incentiveCBatch {get;set;}
	public List<Incentive_Change_Log__c> incentiveChangeLogs {get;set;}
	
	//Constructor
	public CreateChangeBatchController(ApexPages.StandardSetController controller) {
		
		//Initilize 
		incentiveCBatch = new Incentive_Change_Batch__c();
		
		//Get selected
		incentiveChangeLogs = (List<Incentive_Change_Log__c>) controller.getSelected();
		
		//Check for list size
		if(incentiveChangeLogs == null || incentiveChangeLogs.size() == 0)
			//Add Error on page
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select at least one record'));
            
    }
	
	/**
	 *	@description	:	Method to save the change batch record
	 *
	 *	@args			:	
	 *
	 *	@return			:	Pagereference
	 *
	 **/
	public Pagereference doSave() {
		
		//Save Point to roll back changes
        Savepoint sp = Database.setSavepoint();
        
        try {
        	
        	//Check for ICL size
        	if(incentiveChangeLogs == null || incentiveChangeLogs.size() == 0)
        		throw new CustomException('Please select at least one record');
        	
        	//Insert the Batch record
        	if(incentiveCBatch != null) {
        		
        		//Insert
        		insert incentiveCBatch;
        		
        		//Loop through the Incentive Change log records to populate the Batch
        		for(Incentive_Change_Log__c iCL : incentiveChangeLogs) {
        			
        			//Update batch
        			iCL.Incentive_Change_Batch__c = incentiveCBatch.Id;
        		}
        		
        		//Update ICL
        		update incentiveChangeLogs;
        		
        		//Return
        		return new Pagereference('/' + incentiveCBatch.Id);
        	}
        } catch(DMLException dmlExp) {
            
            //Roll Back changes
            Database.rollback(sp);
            incentiveCBatch.Id = null;
            
            //Add Error on page
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,dmlExp.getDmlMessage(0)));
            return null;
            
        }catch(Exception e) {
            
            //Roll Back changes
            Database.rollback(sp);
            incentiveCBatch.Id = null;
            
            //Add Error on page
            ApexPages.addMessages(e);
            return null;
        }
        
        //Return
        return null;
    }
}