objects/Incentive_Change_Log__c.object
<CustomObject>
    <description>We will create a record in the Incentive Change Log for each Incentive-impacting change to related meta-data (such as Program Collection, Collection Perspective, etc.). These records will be grouped by S&amp;O users into Incentive Change Batches, which will be used as the basis for identifying affected Individual Goals.
These records can only be created or modified by the system under program control (specifically, triggers on the related objects).</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Incentive Change Log</label>
    <nameField>
        <displayFormat>ICL{0}</displayFormat>
        <label>Incentive Change Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Change Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Perspective__c.object
<CustomObject>
    <description>This object holds the Perspective definitions.
Within the context of a Program Collection, given consumers may interpret the contents of that Program Collection differently: what one consumer takes as a collection of five Programs, for example, another may interpret as having only three Programs. Since both consumers will use the same terminology to describe the collection, the Perspective allows for a differentiation of the definition of that Program Collection by the intended use or consumer.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Drives availability for selection in Program Relationship only</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Perspectives</relationshipLabel>
        <relationshipName>Group_Purposes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Perspective</label>
    <nameField>
        <label>Perspective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Perspectives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Program_Group__c.object
<CustomObject>
    <description>This object holds the Program Collection definitions.Program Collections are organizing records for broadly recognized collections of Programs. This is an augmentation to the extant concepts of a “Program hierarchy” based on the attributes (Market, Business Line, Vertical, Reporting Group) of specific Programs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Drives availability for selection in Program Relationship only</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Collections</relationshipLabel>
        <relationshipName>Program_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_End__c</fullName>
        <label>Effective End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start__c</fullName>
        <label>Effective Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program Collection</label>
    <nameField>
        <label>Program Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Collections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Program_Perspective__c.object
<CustomObject>
    <description>This object holds the unique association of a Program Collection and a Perspective. 
When establishing a relationship between a Program or Program Collection and any other Program Collection, that relationship must be typified by a Perspective. Rather than require users to identify both the Perspective and Program Collectionwith each association, the association is instead drawn between the child record (Program or Program Collection) and the Collection Perspective, which encapsulates the unique collection for a particular consumption purpose.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Drives availability for selection in Program Relationship only</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Collection Perspectives</relationshipLabel>
        <relationshipName>Program_Perspectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_End__c</fullName>
        <label>Effective End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Effective Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_use_Plans_Direct__c</fullName>
        <label>In use – Plans - Direct</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_use_Plans_Indirect__c</fullName>
        <label>In use – Plans – Indirect</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_use_Staff_Direct__c</fullName>
        <label>In use – Staff – Direct</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Perspective__c</fullName>
        <label>Perspective</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Perspective__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Perspective__c</referenceTo>
        <relationshipLabel>Collection Perspectives</relationshipLabel>
        <relationshipName>Program_Perspectives</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Group__c</fullName>
        <label>Program Collection</label>
        <referenceTo>Program_Group__c</referenceTo>
        <relationshipLabel>Collection Perspectives</relationshipLabel>
        <relationshipName>Program_Perspectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Collection Perspective</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Perspectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Role_Program_Perspective__c.object
<CustomObject>
    <description>Each Staff Assignment may relate to zero or many Program Perspectives. Each of these records has its own effective dating, and these records are aggregated into a viewable list on its parent Staff Assignment for presentation on related lists and simple reports.</description>
    <fields>
        <fullName>Effective_End__c</fullName>
        <label>Effective End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start__c</fullName>
        <label>Effective Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Perspective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Perspective</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program_Perspective__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Perspective__c</referenceTo>
        <relationshipLabel>Role Program Perspectives</relationshipLabel>
        <relationshipName>Role_Program_Perspectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Role Program Perspective</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Role Program Perspectives</pluralLabel>
    <recordTypes>
        <fullName>Assigned</fullName>
        <active>true</active>
        <label>Assigned</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Membership__c.object
<CustomObject>
    <description>This object holds the relationship between the Staff member, Institution, and Assignment Role, as well as defining the effective dates associated with the SA.</description>
    <fields>
        <fullName>End_date__c</fullName>
        <label>Role End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Staff Assignments</relationshipLabel>
        <relationshipName>Team_Memberships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Role</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5) OR ((6 OR 10) AND 7) OR (8 AND 9))</booleanFilter>
            <filterItems>
                <field>Team_Role__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Opportunity</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Opportunity__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Membership</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Membership__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Assigned</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Institution__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Project__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Default</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team_Role__c</referenceTo>
        <relationshipLabel>Staff Assignments</relationshipLabel>
        <relationshipName>Team_Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Staff Assignments</relationshipLabel>
        <relationshipName>Staff_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Role Start</label>
        <type>Date</type>
    </fields>
    <label>Staff Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Assignments</pluralLabel>
    <recordTypes>
        <fullName>Assigned</fullName>
        <active>true</active>
        <description>Automatically assigned upon save</description>
        <label>Assigned</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Role__c.object
<CustomObject>
    <description>This object holds the Role definitions. Each Role is associated with a business owner largely considered responsible for assigning and analyzing the use of that Role in SAs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assignment Roles</relationshipLabel>
        <relationshipName>Staff_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for CR-20150908-9224.</description>
        <label>Institution</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_Trigger_ProgramPerspective.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData = false)
private class Test_Trigger_ProgramPerspective {
    
    /**
    *   Purpose         :   Test class for Trigger_ProgramPerspective trigger
    *            
    *   Create By       :   Subhash Garhwal
    *
    *   Created Date    :   06/26/2015
    *
    *   Revision Log    :   V_1.0 - Created
    *						V_1.1 - Added - Padmesh Soni - New method added myUnitTest2()
	*						Manual Merger By - Rajeev Jain - In test sandbox - Conflict found with Release 50 CR-20160315-9697 Mods
    *						V_1.2 - Modified - Rajeev jain - CR-20151120-9402 - Removed the usage of myUnitTest2
	*
    *   Coverage        :   V_1.0 - 100%
    *					 	V_1.1 - 100%
    **/
    
    //Test method for validateProgramPerspective
    static testMethod void myUnitTest() {
        
        // TO DO: implement unit test
        
        //Bypass Dupeblocker
        Util.IsTest(true);
        Util.isTesting = true;
        Util.BypassAllTriggers = true;
        
        //Create an institution
        Account account = TestUtilities.CreateNewAccount(false);
        
        //Insert
        insert account;
        
        //Create a Contact
        Contact contact = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'test@test.com', AccountId = account.Id, Employee_User_Record__c = Userinfo.getUserId());
        
        //Insert
        insert contact;
        
        //List of Program Groups
        List<Program_Group__c> programGroups = new List<Program_Group__c>();
        
        //Add new Program Groups in list
        programGroups.add(new Program_Group__c(Name = 'Test PG 1', Effective_Start__c = System.today().addDays(-3), Effective_End__c = System.today(),
                                               Business_Owner__c = contact.Id, Short_Name__c = 'test1211', Active__c = true));
        
        programGroups.add(new Program_Group__c(Name = 'Test PG 2', Effective_Start__c = System.today().addDays(-5), Effective_End__c = System.today(),
                                               Business_Owner__c = contact.Id, Short_Name__c = 'test121121', Active__c = true));
        
        programGroups.add(new Program_Group__c(Name = 'Test PG 3', Effective_Start__c = System.today().addDays(-2), Effective_End__c = System.today(),
                                               Business_Owner__c = contact.Id, Short_Name__c = 'test121112', Active__c = true));
        
        //Insert
        insert programGroups;
        
        //Assert
        System.assert(programGroups.size() > 0);
        
        //List of Perspective
        List<Perspective__c> perspectives = new List<Perspective__c>();
        
        //Add new Perspective record in list
        perspectives.add(new Perspective__c(Name = 'Test Perspective 1', Business_Owner__c = contact.Id, Short_Name__c = '1232Test230', Active__c = true));
        perspectives.add(new Perspective__c(Name = 'Test Perspective 2', Business_Owner__c = contact.Id, Short_Name__c = '1332Test230', Active__c = true));
        perspectives.add(new Perspective__c(Name = 'Test Perspective 3', Business_Owner__c = contact.Id, Short_Name__c = '1222Test230', Active__c = true));
        
        //Insert
        insert perspectives;
        
        //Assert
        System.assert(perspectives.size() > 0);
        
        //List of Program Perspective
        List<Program_Perspective__c> programPerspectives = new List<Program_Perspective__c>();
        
        //Add new Program Perspective in list
        programPerspectives.add(new Program_Perspective__c(Name = 'Test PP 1', Program_Group__c = programGroups[0].Id, Perspective__c = perspectives[0].Id,
                                                           Business_Owner__c = contact.Id, Effective_Start__c = System.today(), Effective_End__c = System.today().addDays(4), Active__c = true, In_use_Plans_Direct__c = 2, In_use_Plans_Indirect__c = 2));
        
        programPerspectives.add(new Program_Perspective__c(Name = 'Test PP 1', Program_Group__c = programGroups[1].Id, Perspective__c = perspectives[1].Id,
                                                           Business_Owner__c = contact.Id, Effective_Start__c = System.today(), Effective_End__c = System.today().addDays(4), Active__c = true));
        
        programPerspectives.add(new Program_Perspective__c(Name = 'Test PP 1', Program_Group__c = programGroups[0].Id, Perspective__c = perspectives[0].Id,
                                                           Business_Owner__c = contact.Id, Effective_Start__c = System.today(), Effective_End__c = System.today().addDays(7), Active__c = true));
        
        //Start testing from here 
        Test.startTest();
        
        try {
            
            //Enabling triggers again
        	Util.BypassAllTriggers = false;
        
            //Insert
            insert programPerspectives;
            
        } catch(Exception e) {
            
            //Assert for result
            System.assert(e.getMessage().contains(Label.DUPLICATE_COMBINATION));        
        }
        
        //Change Program Group and Perspective
        programPerspectives[2].Effective_Start__c = System.today().addDays(5);
        
        //Insert
        insert programPerspectives;
        
        //Stop testing here
        Test.stopTest();
    }
    
    //Test method for validateBeforeDelete method
    static testMethod void myUnitTest1() {
        // TO DO: implement unit test
         
        //Bypass Dupeblocker
        Util.IsTest(true);
        Util.isTesting = true;
        Util.BypassAllTriggers = true;
        
        //Create an institution
        Account account = TestUtilities.CreateNewAccount(false);
        
        //Insert
        insert account;
        
        //Create a Contact
        Contact contact = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'test@test.com', AccountId = account.Id, Employee_User_Record__c = Userinfo.getUserId());
        
        //Insert
        insert contact;
        
        //List of Program Groups
        List<Program_Group__c> programGroups = new List<Program_Group__c>();
        
        //Add new Program Groups in list
        programGroups.add(new Program_Group__c(Name = 'Test PG 1', Effective_Start__c = System.today().addDays(-3), Effective_End__c = System.today(),
                                               Business_Owner__c = contact.Id, Short_Name__c = 'test1211', Active__c = true));
        
        programGroups.add(new Program_Group__c(Name = 'Test PG 2', Effective_Start__c = System.today().addDays(-5), Effective_End__c = System.today(),
                                               Business_Owner__c = contact.Id, Short_Name__c = 'test121121', Active__c = true));
        
        programGroups.add(new Program_Group__c(Name = 'Test PG 3', Effective_Start__c = System.today().addDays(-2), Effective_End__c = System.today(),
                                               Business_Owner__c = contact.Id, Short_Name__c = 'test121112', Active__c = true));
        
        //Insert
        insert programGroups;
        
        //Assert
        System.assert(programGroups.size() > 0);
        
        //List of Perspective
        List<Perspective__c> perspectives = new List<Perspective__c>();
        
        //Add new Perspective record in list
        perspectives.add(new Perspective__c(Name = 'Test Perspective 1', Business_Owner__c = contact.Id, Short_Name__c = '1232Test230', Active__c = true));
        perspectives.add(new Perspective__c(Name = 'Test Perspective 2', Business_Owner__c = contact.Id, Short_Name__c = '1332Test230', Active__c = true));
        perspectives.add(new Perspective__c(Name = 'Test Perspective 3', Business_Owner__c = contact.Id, Short_Name__c = '1222Test230', Active__c = true));
        
        //Insert
        insert perspectives;
        
        //Assert
        System.assert(perspectives.size() > 0);
        
        //List of Program Perspective
        List<Program_Perspective__c> programPerspectives = new List<Program_Perspective__c>();
        
        //Add new Program Perspective in list
        programPerspectives.add(new Program_Perspective__c(Name = 'Test PP 1', Program_Group__c = programGroups[0].Id, Perspective__c = perspectives[0].Id,
                                                           Business_Owner__c = contact.Id, Effective_Start__c = System.today(), Effective_End__c = System.today().addDays(4),
                                                           In_use_Plans_Direct__c = 3, In_use_Plans_Indirect__c = 4, In_use_Staff_Direct__c = 5, Active__c = true));
        
        programPerspectives.add(new Program_Perspective__c(Name = 'Test PP 1', Program_Group__c = programGroups[1].Id, Perspective__c = perspectives[1].Id,
                                                           Business_Owner__c = contact.Id, Effective_Start__c = System.today(), Effective_End__c = System.today().addDays(4), Active__c = true));
        
        programPerspectives.add(new Program_Perspective__c(Name = 'Test PP 1', Program_Group__c = programGroups[0].Id, Perspective__c = perspectives[1].Id,
                                                           Business_Owner__c = contact.Id, Effective_Start__c = System.today(), Effective_End__c = System.today().addDays(4), Active__c = true));
        
        //Enabling triggers again
        Util.BypassAllTriggers = false;
        
        //Insert
        insert programPerspectives;
        
        //Assert
        System.assert(programPerspectives.size() > 0);
        
        //Start testing from here 
        Test.startTest();
        
        //Delete Program Perspective
        delete programPerspectives[1];
        
        //Query through Program Perspective
        List<Program_Perspective__c> proPerspectives = [Select Id From Program_Perspective__c];
        
        //Assert for result
        System.assertEquals(2, proPerspectives.size());
        
        try {
            
            //delete Program Perspective
            delete proPerspectives;
        
        } catch(Exception e) {
            
            //Assert for result
            System.assert(e.getMessage().contains(Label.PROGRAM_PERSPECTIVE_IN_USE));
        }
    }
    
    //Added by - Subhash Garhwal
    //Test method to test updateRPPs methods functionality
    static testmethod void testUpdateRPPs() {
        
        //Bypass Dupeblocker
        Util.IsTest(true);
        Util.isTesting = true;
        Util.BypassAllTriggers = true;
        
        //Create Account
        List<Account> accounts = new List<Account>();
        
        //Add new recrods in list 
        accounts.add(new Account(Name = 'Test Account1'));
        
        //Insert account
        insert accounts;
        
        //Create contact
        List<Contact> contacts = new List<Contact>();
        
        //Add new recrods in list
        contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact 1', Email = 'test@test.com',Employee_User_Record__c = Userinfo.getUserId(), AccountId = accounts[0].Id));
        contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact 2', Email = 'test@test.com',Employee_User_Record__c = Userinfo.getUserId(), AccountId = accounts[0].Id));
    
        //Insert contact
        insert contacts;
        
        //Create team role
        List<Team_Role__c> staffRoles = new List<Team_Role__c>();
        
        //Add new recrods in list 
        staffRoles.add(new Team_Role__c(Name = 'Test 1', Active__c = true, Institution__c = true));
        staffRoles.add(new Team_Role__c(Name = 'Test 2', Active__c = true, Institution__c = true));
        insert staffRoles;
        
        //Create Perspective 
        List<Perspective__c> perspectives = new List<Perspective__c>();
        
        //Add new recrods in list 
        perspectives.add(new Perspective__c(Name = 'Perspective 1'));
        perspectives.add(new Perspective__c(Name = 'Perspective 2'));
        
        //Insert
        insert perspectives;
        
        //Create Program Collection
        List<Program_Group__c> programCollections = new List<Program_Group__c>();
        
        //Add new recrods in list 
        programCollections.add(new Program_Group__c(Name = 'PC 1'));
        programCollections.add(new Program_Group__c(Name = 'PC 2'));
        
        //Insert
        insert programCollections;
        
        //Enabling triggers again
        Util.BypassAllTriggers = false;
        
        // Create program Perspective
        List<Program_Perspective__c> programPerspectives = new List<Program_Perspective__c>();
        
        //Add new recrods in list 
        programPerspectives.add(new Program_Perspective__c(Name = 'pp1' , Active__c = true,Perspective__c = perspectives[0].Id, Program_Group__c = programCollections[0].Id ));
        programPerspectives.add(new Program_Perspective__c(Name = 'pp2' , Active__c = true,Perspective__c = perspectives[1].Id, Program_Group__c = programCollections[1].Id));
        
        //Insert Program Pespective
        insert programPerspectives;
        
        //Create staff Assignment 
        List<Team_Membership__c> staffAssignments = new List<Team_Membership__c>();
        
        //Record Types
        List<RecordType> tmRecordTypes = [SELECT ID FROM RecordType WHERE sObjectType = 'Team_Membership__c' 
                                        	AND IsActive = true 
                       						AND DeveloperName = 'Assigned'];
        System.assert(tmRecordTypes != null);
        
        //Add new recrods in list 
        staffAssignments.add(new Team_Membership__c(Name = 'Test As 1',Institution__c = accounts[0].Id ,
                                                    Staff_member__c = contacts[0].Id,Role__c = staffRoles[0].Id, 
                                                    Start_date__c = System.today().addDays(-3), 
                                                    End_date__c = System.today().addDays(+5),
                                                    RecordTypeId = tmRecordTypes[0].Id));
        staffAssignments.add(new Team_Membership__c(Name = 'Test As 1',Institution__c = accounts[0].Id ,
                                                    Staff_member__c = contacts[1].Id,Role__c = staffRoles[1].Id, 
                                                    Start_date__c = System.today().addDays(-3), 
                                                    End_date__c = System.today().addDays(+5),
                                                    RecordTypeId = tmRecordTypes[0].Id));
        
        //Insert
        insert staffAssignments;
        
        //Create role Program perspective 
        List<Role_Program_Perspective__c> rPPs = new List<Role_Program_Perspective__c>();
        
        //Add new recrods in list 
        rPPs.add(new Role_Program_Perspective__c(Name = 'rpp1',Staff_Assignment__c = staffAssignments[0].Id,Program_Perspective__c = programPerspectives[0].Id));
        rPPs.add(new Role_Program_Perspective__c(Name = 'rpp2',Staff_Assignment__c = staffAssignments[1].Id,Program_Perspective__c = programPerspectives[1].Id));
        
        // Test method start
        Test.startTest();
        
        //Insert role Program perspective
        insert rPPs;
        
        //Query through RPP
        List<Role_Program_Perspective__c> rPPsList = [Select Id, Name From Role_Program_Perspective__c];
        
        //Assert for result
        System.assertEquals('Test Contact 1-Test 1-PC 1-Perspective 1', rPPsList[0].Name);
        System.assertEquals('Test Contact 2-Test 2-PC 2-Perspective 2', rPPsList[1].Name);
        
        //Update 
        programCollections[0].Name = 'PG 1';
        
        //Update
        update programCollections;
        
        //Test method Stop
        Test.stopTest();
    }
    
    //Added by - Subhash Garhwal
    //Test method to test SummarizeRPPs methods functionality
    static testmethod void testSummarizeRPPs() {
        
        //Bypass Dupeblocker
        Util.IsTest(true);
        Util.isTesting = true;
        Util.BypassAllTriggers = true;
        
        //Create Account
        List<Account> accounts = new List<Account>();
        
        //Add new recrods in list 
        accounts.add(new Account(Name = 'Test Account1'));
        
        //Insert account
        insert accounts;
        
        //Create contact
        List<Contact> contacts = new List<Contact>();
        
        //Add new recrods in list
        contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact 1', Email = 'test@test.com',Employee_User_Record__c = Userinfo.getUserId(), AccountId = accounts[0].Id));
        contacts.add(new Contact(FirstName = 'Test', LastName = 'Contact 2', Email = 'test@test.com',Employee_User_Record__c = Userinfo.getUserId(), AccountId = accounts[0].Id));
    
        //Insert contact
        insert contacts;
        
        //Create team role
        List<Team_Role__c> staffRoles = new List<Team_Role__c>();
        
        //Add new recrods in list 
        staffRoles.add(new Team_Role__c(Name = 'Test 1', Active__c = true, Institution__c = true));
        staffRoles.add(new Team_Role__c(Name = 'Test 2', Active__c = true, Institution__c = true));
        insert staffRoles;
        
        //Create Perspective 
        List<Perspective__c> perspectives = new List<Perspective__c>();
        
        //Add new recrods in list 
        perspectives.add(new Perspective__c(Name = 'Perspective 1'));
        perspectives.add(new Perspective__c(Name = 'Perspective 2'));
        
        //Insert
        insert perspectives;
        
        //Enabling trigger here
        Util.BypassAllTriggers = false;
        
        //Create Program Collection
        List<Program_Group__c> programCollections = new List<Program_Group__c>();
        
        //Add new recrods in list 
        programCollections.add(new Program_Group__c(Name = 'PC 1'));
        programCollections.add(new Program_Group__c(Name = 'PC 2'));
        
        //Insert
        insert programCollections;
        
        // Create program Perspective
        List<Program_Perspective__c> programPerspectives = new List<Program_Perspective__c>();
        
        //Add new recrods in list 
        programPerspectives.add(new Program_Perspective__c(Name = 'pp1' , Active__c = true, Perspective__c = perspectives[0].Id, Program_Group__c = programCollections[0].Id ));
        programPerspectives.add(new Program_Perspective__c(Name = 'pp2' , Active__c = true, Perspective__c = perspectives[1].Id, Program_Group__c = programCollections[1].Id));
        
        //Insert Program Pespective
        insert programPerspectives;
        
        //Create staff Assignment 
        List<Team_Membership__c> staffAssignments = new List<Team_Membership__c>();
        
        //Record Types
        List<RecordType> tmRecordTypes = [SELECT ID FROM RecordType WHERE sObjectType = 'Team_Membership__c' 
                                        	AND IsActive = true 
                       						AND DeveloperName = 'Assigned'];
        System.assert(tmRecordTypes != null);
        
        //Add new recrods in list 
        staffAssignments.add(new Team_Membership__c(Name = 'Test As 1',Institution__c = accounts[0].Id, 
                                                    Staff_member__c = contacts[0].Id,Role__c = staffRoles[0].Id, 
                                                    Start_date__c = System.today().addDays(-3), 
                                                    End_date__c = System.today().addDays(+5),
                                                    RecordTypeId = tmRecordTypes[0].Id));
        staffAssignments.add(new Team_Membership__c(Name = 'Test As 1',Institution__c = accounts[0].Id, 
                                                    Staff_member__c = contacts[1].Id,Role__c = staffRoles[1].Id, 
                                                    Start_date__c = System.today().addDays(-3), 
                                                    End_date__c = System.today().addDays(+5),
                                                    RecordTypeId = tmRecordTypes[0].Id));
        
        //Insert
        insert staffAssignments;
        
        //Create role Program perspective 
        List<Role_Program_Perspective__c> rPPs = new List<Role_Program_Perspective__c>();
        
        //Add new recrods in list 
        rPPs.add(new Role_Program_Perspective__c(Name = 'rpp1',Staff_Assignment__c = staffAssignments[0].Id,Program_Perspective__c = programPerspectives[0].Id));
        rPPs.add(new Role_Program_Perspective__c(Name = 'rpp2',Staff_Assignment__c = staffAssignments[1].Id,Program_Perspective__c = programPerspectives[1].Id));
        
        // Test method start
        Test.startTest();
        
        //Insert role Program perspective
        insert rPPs;
        
        //Query through RPP
        List<Role_Program_Perspective__c> rPPsList = [Select Id, Name From Role_Program_Perspective__c];
        
        //Assert for result
        System.assertEquals('Test Contact 1-Test 1-PC 1-Perspective 1', rPPsList[0].Name);
        System.assertEquals('Test Contact 2-Test 2-PC 2-Perspective 2', rPPsList[1].Name);
        
        //Test method Stop
        Test.stopTest();
    }    
    
	//-------------Code Added by Padmesh Soni  08/07/2015   CR-20150729-9114 ----------------
	//V_1.2 - Modified - Rajeev jain - CR-20151120-9402 - Removed the usage of myUnitTest2
	//Test method to check createIncentiveChangeLog method
	/*static testMethod void myUnitTest2() {
        
        //Bypass Dupeblocker
        Util.IsTest(true);
        Util.isTesting = true;
        Util.BypassAllTriggers = true;
 
		//Create an institution
		Account account = TestUtilities.CreateNewAccount(false);
		
		//Insert
		insert account;
		
		//Create a Contact
		Contact contact = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'test@test.com', AccountId = account.Id,
									  Employee_User_Record__c = Userinfo.getUserId());
			
		//Insert
		insert contact;
		
		//List of Program Collection
		List<Program_Group__c> programGroups = new List<Program_Group__c>();
		    
		//Add new Program Groups in list
		programGroups.add(new Program_Group__c(Name = 'Test PG 1', Effective_Start__c = System.today().addDays(-3), Effective_End__c = System.today(),
												Business_Owner__c = contact.Id, Short_Name__c = 'test1211', Active__c = true));
		                                        
		//Insert
		insert programGroups;
		
		//Assert
		System.assert(programGroups.size() > 0);
		
		//List of Perspective
		List<Perspective__c> perspectives = new List<Perspective__c>();
		
		//Add new Perspective record in list
		perspectives.add(new Perspective__c(Name = 'Test Perspective 1', Business_Owner__c = contact.Id, Short_Name__c = '11244test1211', Active__c = true));
		
		//Insert
		insert perspectives;
		
		//Assert for result
		System.assert(perspectives.size() > 0);
        
        //Enabling trigger here
        Util.BypassAllTriggers = false;
		        
		//List of Program Perspective
		List<Program_Perspective__c> programPerspectives = new List<Program_Perspective__c>();
		
		//Add new Program Perspective in list
		programPerspectives.add(new Program_Perspective__c(Name = 'Test CP 1', Program_Group__c = programGroups[0].Id,
														   Perspective__c = perspectives[0].Id, 
														   Business_Owner__c = contact.Id, 
														   Effective_Start__c = System.today(), 
														   Effective_End__c = System.today().addDays(20),
														   Active__c = true));
		
		//Insert
		insert programPerspectives;
		
		//Assert for results
		System.assert(programPerspectives.size() > 0);
		
		//Start testing from here 
		Test.startTest();
		
		//List of Incentive Change Log
		List<Incentive_Change_Log__c> iCG = [SELECT Id, Name, Collection_Perspective__c FROM Incentive_Change_Log__c 
                                             Where Collection_Perspective__c IN : programPerspectives];        
		
		//Assert for results
		System.assertEquals(0, iCG.size());
		
		//Update date field to create ICG record
		programPerspectives[0].Effective_Start__c = System.today().addDays(5);
		
		//Update programPerspectives
		update programPerspectives[0];
		
		//List of Incentive Change Log
		iCG = [SELECT Id, Name, Collection_Perspective__c FROM Incentive_Change_Log__c 
               Where Collection_Perspective__c IN : programPerspectives];        
		
		//Assert for results
		System.assertEquals(1, iCG.size());
		
		//Update program date fields
		programPerspectives[0].Effective_End__c = System.today().addDays(25);
		
		//By pass the triggers here
		Util.BypassAllTriggers = false;
		
		//Update programPerspectives
		update programPerspectives;
		
		//List of Incentive Change Log
		iCG = [SELECT Id, Name, Change_Type__c FROM Incentive_Change_Log__c 
               Where Collection_Perspective__c =: programPerspectives[0].Id];        
		
		//Assert for results
		System.assertEquals(2, iCG.size());
		
		//Update satus field
		programPerspectives[0].Active__c = false;
		
		//By pass the triggers here
		Util.BypassAllTriggers = false;
		
		//Update programPerspective
		update programPerspectives;
		
		//List of Incentive Change Log
		iCG = [SELECT Id, Name, Change_Type__c FROM Incentive_Change_Log__c Where Collection_Perspective__c =: programPerspectives[0].Id];        
		
		//Assert for result
		System.assertEquals(3, iCG.size());
		
		//Stop testing here
		Test.stopTest();
	}*/
}