objects/Institution_Roles__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Institution Roles</relationshipLabel>
        <relationshipName>Institution_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <inlineHelpText>Select the Institution Record Type. This value controls the Roles for the contact being added.</inlineHelpText>
        <label>Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>US Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US HCIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International HCIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician Practice</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <controllingField>Record_Type__c</controllingField>
            <picklistValues>
                <fullName>Accts Receivable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDO - Head of Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEO - Head of Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFO - Head of Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIO - Head of Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Coach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Gate Keeper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMO - Medical Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNO - Head of Nursing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COO - Head of Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CQO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CQO - Head of Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAB: Assoc VP (Provost) of Acad Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAB: Assoc VP of Finance &amp; Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAB: Chief Information Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAB: Community College President</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAB: Dean of Students</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAB: Dir. of Mkting &amp; Online Ed (COE #2)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAB: Director of Facilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAB: Director of Procurement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Institution Role</label>
    <nameField>
        <label>Institution Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Institution Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_InstituteRoleController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
 /*
    Purpose:    This class is  ttest class for InstituteRoleController
                
    Create By:  Simplyforce Technology
    
    Created Date:   10/13/2011
    
    Current Version:    v1.1
    
    Revision Log:       v1.0 - Created
                        v1.1 - Modified By - Abhinav Sharma - 11/21/2014 - CR-20141016-7783
*/
@isTest(seeAllData= false)
private class Test_InstituteRoleController {
    
    //test method
    static testmethod void myUnitTest() { 
    
        //Bypass Dupeblocker
        Util.IsTest(true);
        
        //Bypassing all triggers
        Util.byPassAlltriggers = true;
        
        //fecth the existing record type from data base
        List<RecordType> listRecordType = [Select SobjectType, Name, IsActive, Id, DeveloperName From RecordType
                                            where IsActive = true and SobjectType = 'Account' and DeveloperName ='US_Provider' limit 1];
        
        //check for the list size
        if(listRecordType.size() > 0) {
            
            //create the account and contact sample data
            Account account = new Account(Name = 'TestAccount', RecordTypeId = listRecordType[0].Id);
            insert account;
            
            //insert the contact record
            Contact contact = new Contact(LastName = 'TestLastName', AccountId = account.Id, Record_Type__c = listRecordType[0].Name);
            insert contact;
            
            //add a garbage record
            Contact garbageContact = new Contact(LastName = 'TestLastName', AccountId = account.Id, Record_Type__c = 'Garbage');
            insert garbageContact;
            
            //create a garbeage institute role
            Institution_Roles__c  instRole = new Institution_Roles__c(Role__c = 'CEO', Contact__c = garbageContact.Id, Institution__c = account.Id, Record_Type__c = listRecordType[0].Id);
            insert instRole;
            
            //create a garbeage institute role
            Institution_Roles__c instRoleGarbage = new Institution_Roles__c(Contact__c = garbageContact.Id, Institution__c = account.Id, Record_Type__c = listRecordType[0].Id);
            insert instRoleGarbage;
            
            //set current page parameters
            ApexPages.currentPage().getParameters().put('accId', account.Id);
            ApexPages.currentPage().getParameters().put('recordType', listRecordType[0].Name);
            
            //start test from here 
            Test.startTest();
            
            //Enabling trigger again
            Util.byPassAlltriggers = false;
            
            //instantiate controller
            InstituteRoleController controller = new InstituteRoleController(new ApexPages.StandardController(new Institution_Roles__c()));
            
            //call the delete method
            controller.instituteRoleId = instRole.Id;
            controller.deleteInstituteRole();
            
            //call save method
            controller.save();
            
            //stop test here
            Test.stopTest();
        }
    }
}