objects/Integration__c.object
<CustomObject>
    <label>Integration</label>
    <nameField>
        <label>Integration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Integration_Job__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for individual Integration jobs</description>
    <fields>
        <fullName>Integration_Job_Name__c</fullName>
        <description>Origin:  CR-20130109-2083 - Contract Mgmt / Procurement</description>
        <label>Integration Job Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Integration Job</label>
</CustomObject>

objects/Integration_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Name__c</fullName>
        <label>Integration Name</label>
        <picklist>
            <picklistValues>
                <fullName>Upsert_EmployeeContactUser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivate_User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budget</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Integration_RecordTypeId__c</fullName>
        <label>Integration RecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Integration Mapping</label>
    <nameField>
        <label>Integration Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_IntegrationMappingHelper.cls
@isTest
private class Test_IntegrationMappingHelper {

    static testmethod void testUpdateIntegrationRecType(){
        
        list<RecordType> intRecType = [select Id, DeveloperName from RecordType where SobjectType = 'Integration__c' LIMIT 1];
        Integration_Job__c intjob = new Integration_Job__c();
        intjob.Name = intRecType[0].Id;
        intjob.Integration_Job_Name__c = intRecType[0].DeveloperName;
        insert intjob;
        
        Integration_Mapping__c im = new Integration_Mapping__c();
        im.Integration_Name__c = intJob.Integration_Job_Name__c;
        Id testId ;
        
        test.startTest();
        	insert im;
        	testId = im.Id;
        test.stopTest();
        
        Integration_Mapping__c imResult = [select Id, Integration_RecordTypeId__c from Integration_Mapping__c where Id = :testId];
        system.assertNotEquals(null,imResult.Integration_RecordTypeId__c);
        
    }
    
}