objects/Intranet_Item__c.object
<CustomObject>
    <description>Individual Content Items</description>
    <fields>
        <fullName>Active_Status__c</fullName>
        <label>Active Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Item_Title__c</fullName>
        <label>Item Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ad Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birthdays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Firm App Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Impact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>News Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page Section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poll Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quick Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Talent Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trending - Advisory.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trending - EAB.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trending - Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page Link</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Intranet Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intranet Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_IntranetChatterHelper.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
/** Description     :	Test class for IntranetChatterHelperController
  * 
  * Created Date    :	09/15/2014
  *
  * Created By      :   
  *  
  * Current vision  :	v1.0
  *  
  * Revision Logs   :	v1.0 - Created
  * 				:	V2.0 - Modifled By - Rajeev Jain(09/15/2015) - CR-20141002-7579
  *
  * Coverage        :	100%
  **/  
// ConnectApi methods are not supported in data siloed tests. Please use @IsTest(SeeAllData=true)
// Making true due to getting above mentined error while running test class
@isTest(SeeAllData = true)
private class Test_IntranetChatterHelper {

    static testMethod void testInsertFeedItem() {
        // TO DO: implement unit test
         
        //Create Intranet Item
        Intranet_Item__c intranetItem = new Intranet_Item__c(Name = 'Test-0' , Active_Status__c = 'Active' , Item_Type__c = 'App Link' , Item_Title__c = 'A1');
        insert intranetItem;
        
        //Feed Item Body
        String testFeedBody = 'Hello this is Test feed Body';
        
        //Instance of Feed Item
        FeedItem feedItem;
        
        Test.startTest();
        
        //Insert Feed Item
        feedItem = IntranetChatterHelper.CreateFeedItem(intranetItem.Id, testFeedBody);
        
        //Assert to Check Parent Id
        System.assertEquals(feedItem.ParentId, intranetItem.Id);
        
        //Assert to Check Item Body
        System.assertEquals(feedItem.Body, testFeedBody);
        
        Test.stopTest();
    }
}