objects/Intranet_Container__c.object
<CustomObject>
    <description>Content Block which contains Content Items</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <inlineHelpText>Name used on page component and Content Viewer, if applicable</inlineHelpText>
        <label>Display Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Number__c</fullName>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Top_Parent_Container_Id__c</fullName>
        <description>Used in Boardroom by a query to get all Containers related to a top level Page.</description>
        <formula>IF(NOT(ISBLANK(Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__c)),
  Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__c,
  IF(NOT(ISBLANK(Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__c)),
    Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__c,
    IF(NOT(ISBLANK(Parent_Container__r.Parent_Container__r.Parent_Container__c)),
      Parent_Container__r.Parent_Container__r.Parent_Container__c,
      IF(NOT(ISBLANK(Parent_Container__r.Parent_Container__c)),
        Parent_Container__r.Parent_Container__c,
        IF(NOT(ISBLANK(Parent_Container__c)),
          Parent_Container__c,
          Id
        )
      )
    )
  )
)</formula>
        <inlineHelpText>Top Parent Container, up to 5 levels deep</inlineHelpText>
        <label>Top Parent Container Id</label>
        <type>Text</type>
    </fields>
    <label>Intranet Container</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intranet Containers</pluralLabel>
    <recordTypes>
        <fullName>Header</fullName>
        <active>true</active>
        <description>Contains all header containers and items</description>
        <label>Header</label>
    </recordTypes>
    <recordTypes>
        <fullName>Page</fullName>
        <active>true</active>
        <description>Top-level container for a Page</description>
        <label>Page</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intranet_Defaults__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default values for specific item types</description>
    <fields>
        <fullName>ContentViewerView__c</fullName>
        <label>ContentViewerView</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Intranet_Container__c</fullName>
        <label>Intranet Container</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <inlineHelpText>Default value for Item_Type__c on Intranet_Item__c</inlineHelpText>
        <label>Item Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SearchCategory__c</fullName>
        <inlineHelpText>Search Results Category</inlineHelpText>
        <label>SearchCategory</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Intranet Defaults</label>
</CustomObject>

objects/Intranet_Item__c.object
<CustomObject>
    <description>Individual Content Items</description>
    <fields>
        <fullName>Chatter_Comments_Rollup__c</fullName>
        <label>Chatter Comments</label>
        <summaryFilterItems>
            <field>Intranet_Utilization__c.Click_Type__c</field>
            <operation>equals</operation>
            <value>Comment</value>
        </summaryFilterItems>
        <summaryForeignKey>Intranet_Utilization__c.Intranet_Item__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Chatter_Likes__c</fullName>
        <label>Chatter Likes</label>
        <summaryFilterItems>
            <field>Intranet_Utilization__c.Click_Type__c</field>
            <operation>equals</operation>
            <value>Like</value>
        </summaryFilterItems>
        <summaryForeignKey>Intranet_Utilization__c.Intranet_Item__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Chatter_Shares__c</fullName>
        <label>Chatter Shares</label>
        <summaryFilterItems>
            <field>Intranet_Utilization__c.Click_Type__c</field>
            <operation>equals</operation>
            <value>Share</value>
        </summaryFilterItems>
        <summaryForeignKey>Intranet_Utilization__c.Intranet_Item__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Content_Publish_Date__c</fullName>
        <inlineHelpText>Date the item was originally published</inlineHelpText>
        <label>Content Publish Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Used only for Flexible container items</description>
        <formula>CASE(TEXT(Item_Type__c),
&apos;Ad Item&apos;,$Label.Intranet_DisplayName_Ad,
&apos;Talent Item&apos;,$Label.Intranet_DisplayName_Talent,
&apos;Job Item&apos;,$Label.Intranet_DisplayName_Job,
&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name used on page component and Content Viewer, if applicable</inlineHelpText>
        <label>Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date_Time__c</fullName>
        <label>Event Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>ABC Office Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABC Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Item_Title__c</fullName>
        <label>Item Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ad Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birthdays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Firm App Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Impact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>News Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page Section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poll Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quick Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Talent Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trending - Advisory.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trending - EAB.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trending - Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page Link</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Link_URL_Validated__c</fullName>
        <description>Created for CR-20150219-8692</description>
        <label>Link URL (Validated)</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Link_URL__c</fullName>
        <label>Link URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Office_Name__c</fullName>
        <label>Office Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permalink_Validated__c</fullName>
        <description>Created for CR-20150219-8692</description>
        <label>Permalink (Validated)</label>
        <type>Url</type>
    </fields>
    <label>Intranet Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intranet Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intranet_Schedule__c.object
<CustomObject>
    <description>Used to determine when and to whom a Content Item is visible in a specific Container</description>
    <fields>
        <fullName>Intranet_Container__c</fullName>
        <label>Intranet Container</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Intranet_Container__c.Content_Types_Allowed_Text__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Intranet_Container__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <infoMessage>Initial Filter includes only Active containers where the Content Types Allowed have been defined.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Intranet_Container__c</referenceTo>
        <relationshipLabel>Intranet Schedules</relationshipLabel>
        <relationshipName>Intranet_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intranet_Item__c</fullName>
        <label>Intranet Item</label>
        <referenceTo>Intranet_Item__c</referenceTo>
        <relationshipLabel>Intranet Schedules</relationshipLabel>
        <relationshipName>Intranet_Schedules</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Intranet_Item__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Settings - Office</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Intranet_Item__c</referenceTo>
        <relationshipLabel>Intranet Schedules (Office)</relationshipLabel>
        <relationshipName>Intranet_Schedules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intranet Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intranet Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IntranetContentInfo.cls
public virtual class IntranetContentInfo implements Comparable {

    public Integer RowNumber {get; set;}
    public String Id {get; set;}
    public String ItemTitle {get; set;}
    public String ItemType {get; set;}
    public String Permalink {get; set;}
    public Intranet_Container__c topParentContainer { get; set; }
    public String ScheduleReferenceNumber { get; set; }

    public Decimal ChatterLikes {get; set;}
    public Decimal ChatterComments {get; set;}
    //public Decimal ChatterShares {get; set;}

    public String SortOrder {get; set;}
    public Double SortOrderNumber {get; set;}
    public Boolean SortAscendingly { get; set; }

    public List<FieldInfo> Properties { get; set; }

    public string Topics {get; set;}

    public IntranetContentInfo() {

    }
    public IntranetContentInfo(Intranet_Item__c item, Intranet_Schedule__c schedule, Intranet_Container__c container, Schema.FieldSet fieldset,
                               Map<String, Schema.SObjectField> fieldMap, SObjectField sortField, boolean ascending) {

        Id = item.Id;
        ItemTitle = item.Item_Title__c;
        ItemType = item.Item_Type__c;
        ChatterLikes = item.Chatter_Likes__c;
        ChatterComments = item.Chatter_Comments_Rollup__c;
        //EventStartDateTime = item.Event_Start_Date_Time__c;
        //ChatterShares = item.Chatter_Shares__c;
        topParentContainer = container;
        if (schedule != null) ScheduleReferenceNumber = schedule.Intranet_Container__r.Reference_Number__c;

        Permalink = item.Permalink_Validated__c;

        Intranet_Defaults__c intranetDefault;
        if(!String.isBlank(item.Event_Type__c))
            intranetDefault = IntranetHomeUtility.LookupIntranetDefaultByName(item.Event_Type__c);
        if(intranetDefault == null)
            intranetDefault = IntranetHomeUtility.LookupIntranetDefault(itemType);
        if (intranetDefault != null && intranetDefault.SearchCategory__c != 'Exclude' && intranetDefault.ContentViewerView__c != null) {
            if(intranetDefault.ContentViewerView__c == 'Page' && ItemType == 'Page Section') {
                if(schedule != null && schedule.Intranet_Container__r.Top_Parent_Container_Id__c != null) {
                    Permalink = '/apex/Boardroom_Internal_Home_Page?TopContainerId=' + schedule.Intranet_Container__r.Top_Parent_Container_Id__c;
                    if (ScheduleReferenceNumber != null)
                        Permalink = Permalink + '#' + ScheduleReferenceNumber;
                }
                
            } else if(Permalink == null) {
                if(intranetDefault.ContentViewerView__c == 'Link_URL__c') {
                    Permalink = item.Link_URL_Validated__c;

                } else if (intranetDefault.ContentViewerView__c.contains('mode=calendar')) {
                    Permalink = '/apex/IntranetContentViewer?' + intranetDefault.ContentViewerView__c + '&SearchContentId=' +  Id + '&SearchContentType=' +
                        ItemType + '&SearchStartDate=' + EncodingUtil.urlEncode(item.Event_Start_Date_Time__c.format('MM/dd/yyyy'), 'UTF-8');

                } else {
                    Permalink = '/apex/IntranetContentViewer?' + intranetDefault.ContentViewerView__c +
                                '&SearchContentId=' +  Id + '&SearchContentType=' +  ItemType;

                }
            }
        }

        SortAscendingly = ascending == null ? true : ascending;
        if (sortField != null) {
            String sortType = sortField.getDescribe().getType().name();
            object o = item.get(sortField);
            if (o == null) {
                SortOrder = '';
            } else {
                if (sortType == 'DOUBLE') {
                    SortOrderNumber = (o != null) ? double.valueOf(o) : 0;
                } else if (sortType == 'DATE' || sortType == 'DATETIME') {
                    SortOrderNumber = (o != null) ? Datetime.valueOf(o).getTime() : 0;
                } else {
                    SortOrder = (o != null) ? string.valueOf(o) : '';
                }
            }
        } else {
            SortOrder = '';
        }

        Properties = new List<FieldInfo>();

        // Add Page Name for the page search
        if (ItemType == 'Page Section') {
            Properties.add(new FieldInfo('Page', 'STRING', container==null? '' : container.Display_Name__c));
        }

        if (fieldset != null) {
            boolean firstChatter = true;
            for (Schema.FieldSetMember member : fieldset.getFields()) {
                Schema.SObjectField field = fieldMap.get(member.FieldPath);
                DescribeFieldResult fieldDescriber = field.getDescribe();
                Object itemValue = item.get(field);

                if (member.FieldPath == 'Chatter_Likes__c' || member.FieldPath == 'Chatter_Comments_Rollup__c') {
                    if (firstChatter) {
                        firstChatter = false;
                        Properties.add(new FieldInfo('Social',
                                                     'STRING',
                                                     ChatterLikes + ',' + ChatterComments));
                    }
                    continue;
                }

                if (member.FieldPath == 'Event_Start_Date_Time__c') {
                    Datetime myDatetime = item.Event_Start_Date_Time__c;
                    //String newDate = myDatetime == null ? '' : myDatetime.format('M/d/yyyy h:mm a', 'America/New_York');
                    String newDate = (myDatetime == null ? '' : (String.valueOf(myDatetime.month()) + '/' + String.valueOf(myDatetime.day()) + '/' + String.valueOf(myDatetime.year())));
                    
                    Properties.add(new FieldInfo('Event Date',
                                                 'STRING',
                                                 newDate));
                    continue;
                }

                // Pull in Office_Name__c from schedule
                if (member.FieldPath == 'Office_Name__c') {
                    String officeName = item.Office_Name__c;
                    if (schedule != null && schedule.Office__c != null) {
                        officeName = IntranetHomeUtility.LookupOfficeNameById(schedule.Office__c);
                    }
                    if (officeName == null) officeName = '';

                    Properties.add(new FieldInfo('Office',
                                                 'STRING',
                                                 officeName));
                    continue;
                }

                if (member.FieldPath == 'Item_Title__c') {
                    Properties.add(new FieldInfo('Title',
                                                 fieldDescriber.getType().name(),
                                                 itemValue == null ? '' : string.valueOf(itemValue)));
                    continue;
                }

                if (member.FieldPath == 'Item_Type__c') {
                    Properties.add(new FieldInfo('Item',
                                                 fieldDescriber.getType().name(),
                                                 itemValue == null ? '' : string.valueOf(itemValue)));
                    continue;
                }
                
                if(member.FieldPath == 'Content_Publish_Date__c') {
                    DateTime myDatetime = item.Content_Publish_Date__c;
                    String newDate = (myDatetime == null ? '' : (String.valueOf(myDatetime.month()) + '/' + String.valueOf(myDatetime.day()) + '/' + String.valueOf(myDatetime.year())));
                    
                    Properties.add(new FieldInfo('Publish Date',
                                                 fieldDescriber.getType().name(),
                                                 itemValue == null ? '' : newDate));
                    continue;
                }
				
                Properties.add(new FieldInfo(fieldDescriber.getLabel(),
                                             fieldDescriber.getType().name(),
                                             itemValue == null ? '' : string.valueOf(itemValue)));
            }
        }

        List<String> topics = new List<String>();
        ConnectApi.TopicPage page = ConnectApi.Topics.getTopics('Internal', Id);
        for (ConnectApi.Topic t : page.topics) {
            topics.add(t.Name);
        }
        this.Topics = string.join(topics, ', ');
        if (this.Topics == null || this.Topics == '') this.Topics = ' ';
    }

    public Integer compareTo(Object compareTo) {
        if (compareTo == null) return SortAscendingly ? 1 : -1;
        IntranetContentInfo compareToIContent = (IntranetContentInfo)compareTo;
        if (compareToIContent == null) return SortAscendingly ? 1 : -1;

        if (SortOrder == null) {
            if ( SortOrderNumber == compareToIContent.SortOrderNumber ) return 0;
            if ( SortOrderNumber > compareToIContent.SortOrderNumber ) return SortAscendingly ? 1 : -1;
            return SortAscendingly ? -1 : 1;
        } else {
            if ( SortOrder == compareToIContent.SortOrder ) return 0;
            if ( SortOrder > compareToIContent.SortOrder ) return SortAscendingly ? 1 : -1;
            return SortAscendingly ? -1 : 1;
        }
    }

    public string ToString(string indent) {
        return indent + 'ContentInfo: (Id=' + this.Id + ' title=' + this.ItemTitle + ', type=' + this.ItemType + ', sortOrder=' + this.sortOrder + ')<br>';
    }

    public IntranetContentInfo DuplicateToHeader() {
        IntranetContentInfo header = new IntranetContentInfo();
        header.Properties = new List<FieldInfo>();
        for (FieldInfo fi : this.Properties) {
            header.Properties.add(new FieldInfo(fi.FieldLabel, fi.FieldType, fi.FieldLabel));
        }
        return header;
    }

    public class FieldInfo {
        public string FieldLabel { get; private set;}
        public string FieldType { get; private set; }
        public string FieldValue { get; private set; }

        public FieldInfo(string flabel, string ftype, string fvalue) {
            this.FieldLabel = flabel;
            this.FieldType = ftype;
            this.FieldValue = fvalue;

        }
    }
}