objects/Intranet_Container__c.object
<CustomObject>
    <description>Content Block which contains Content Items</description>
    <fields>
        <fullName>Footer_Container__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Footer Container</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Intranet_Container__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Footer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Intranet_Container__c</referenceTo>
        <relationshipLabel>Pages with Footer</relationshipLabel>
        <relationshipName>Intranet_Containers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Header_Container__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Header Container</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Intranet_Container__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Header</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Intranet_Container__c</referenceTo>
        <relationshipLabel>Pages with Header</relationshipLabel>
        <relationshipName>Intranet_Containers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intranet Container</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intranet Containers</pluralLabel>
    <recordTypes>
        <fullName>Header</fullName>
        <active>true</active>
        <description>Contains all header containers and items</description>
        <label>Header</label>
    </recordTypes>
    <recordTypes>
        <fullName>Page</fullName>
        <active>true</active>
        <description>Top-level container for a Page</description>
        <label>Page</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IntranetFixedController.cls
/**
    Purpose:    This controller is to control the component block items displayed on Boardroom Page.
                
    Created By:  Colin McGloin
    
    Created Date:   7/21/2014
    
    Current Version:    v1.0
    
    Revision Log:       
 **/

public class IntranetFixedController {
    
    	public Id BoardroomHeader { get; set; }
        public Id BoardroomBody { get; set; }
    	public String QuickLinks { get; set; }
    	public Intranet_Container__c ic;
    
    	//public IntranetType.FixedContainer itemType {get; set;}
    	public IntranetContainer items {get; set;}
    
    public IntranetFixedController() {
        //if(ic == null){
        //    GetPageHeader();
        //}
        
		//sitemType = new IntranetType.FixedContainer(items);
		
    }
 
 /*   
    public IntranetType.FooterContainer BoardroomFooter{
        get{
            return IntranetHomeUtility.getFooterContent(ic.Footer_Container__c);
        }
        set;
    }
    
    public IntranetType.Container BodyCont{
        get{
            return IntranetHomeUtility.getContainers(ic.Name);
        }
        set;
    }
    
	//class to search for Header  
    public void GetPageHeader() {
        
        ic = [SELECT Id, Name, Header_Container__c, Footer_Container__c FROM Intranet_Container__c WHERE Id = :Label.IntranetMainPage];
        BoardroomBody = ic.Id;
		system.debug('IntranetFixedController.GetPageHeader - ic:' + ic);
		        
    }
    
    public void GetQuickLinks() {
        
        ic = [SELECT Id, Name FROM Intranet_Container__c WHERE Name = 'QuickLinks'];
            QuickLinks = ic.Id;
        system.debug('IntranetFixedController.GetQuickLinks - ic:' + ic);
    }
    */
}