objects/Intranet_Container__c.object
<CustomObject>
    <description>Content Block which contains Content Items</description>
    <fields>
        <fullName>Container_Level__c</fullName>
        <formula>IF(RecordType.Name = &apos;Header&apos;,
  &apos;Header&apos;,
  IF(RecordType.Name = &apos;Footer&apos;,
    &apos;Footer&apos;,
    IF(AND(RecordType.Name = &apos;Page&apos;, ISBLANK(Parent_Container__c)),
      &apos;MainPage&apos;,
      IF(AND(RecordType.Name = &apos;Page&apos;, NOT(ISBLANK(Parent_Container__c))),
        &apos;PageBlock&apos;,
        IF(AND(RecordType.Name != &apos;Page&apos;, ISBLANK(Parent_Container__c)),
          &apos;Orphan&apos;,
          &apos;Child&apos;)
      )
    )
  )
)</formula>
        <inlineHelpText>Type of Container by Level</inlineHelpText>
        <label>Container Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <label>Container Type</label>
        <picklist>
            <picklistValues>
                <fullName>ABC Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABC Today</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ABC TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Firm Initiative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Header</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Menu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>News Carousel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page Actions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page Bookmarks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page Section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poll</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QuickLinks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SubContainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Status</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Content_Types_Allowed__c</fullName>
        <label>Content Types Allowed</label>
        <picklist>
            <picklistValues>
                <fullName>Ad Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birthdays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Firm App Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Image Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Impact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>News Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page Section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poll Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quick Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Talent Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trending - Advisory.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trending - EAB.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trending - Ideas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page Link</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Default_Content_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Content to load when no other content is defined for the current day or user</inlineHelpText>
        <label>Default Content Item</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Intranet_Item__c.Active_Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>Intranet_Item__c.Item_Type__c</field>
                <operation>notEqual</operation>
                <value>Poll Item, ABC Trending Item, EAB Trending Item, Ideas Trending Item</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Intranet_Item__c</referenceTo>
        <relationshipLabel>Default for Containers</relationshipLabel>
        <relationshipName>Intranet_Containers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <inlineHelpText>Name used on page component and Content Viewer, if applicable</inlineHelpText>
        <label>Display Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_SubContainers__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Includes Tabs or other sub-containers</inlineHelpText>
        <label>zzzHas Subcontainers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <inlineHelpText>Overall Height in pixels of Container</inlineHelpText>
        <label>Height</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Content_Items__c</fullName>
        <label>Max Content Items</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Visible_Screen__c</fullName>
        <label>Minimum Visible Screen</label>
        <picklist>
            <picklistValues>
                <fullName>Desktop (1200 pixels)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laptop (992 pixels)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet  (768 pixels)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone (&lt;768 pixels)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Container__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Container</label>
        <referenceTo>Intranet_Container__c</referenceTo>
        <relationshipLabel>Sub Containers</relationshipLabel>
        <relationshipName>Intranet_Containers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Number__c</fullName>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Show_Expand_Link__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Expand Link</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Top_Parent_Container_Id__c</fullName>
        <description>Used in Boardroom by a query to get all Containers related to a top level Page.</description>
        <formula>IF(NOT(ISBLANK(Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__c)),
  Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__c,
  IF(NOT(ISBLANK(Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__c)),
    Parent_Container__r.Parent_Container__r.Parent_Container__r.Parent_Container__c,
    IF(NOT(ISBLANK(Parent_Container__r.Parent_Container__r.Parent_Container__c)),
      Parent_Container__r.Parent_Container__r.Parent_Container__c,
      IF(NOT(ISBLANK(Parent_Container__r.Parent_Container__c)),
        Parent_Container__r.Parent_Container__c,
        IF(NOT(ISBLANK(Parent_Container__c)),
          Parent_Container__c,
          Id
        )
      )
    )
  )
)</formula>
        <inlineHelpText>Top Parent Container, up to 5 levels deep</inlineHelpText>
        <label>Top Parent Container Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <inlineHelpText>Overall Width in pixels of Container</inlineHelpText>
        <label>Width</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Intranet Container</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intranet Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intranet_Item__c.object
<CustomObject>
    <description>Individual Content Items</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Used only for Flexible container items</description>
        <formula>CASE(TEXT(Item_Type__c),
&apos;Ad Item&apos;,$Label.Intranet_DisplayName_Ad,
&apos;Talent Item&apos;,$Label.Intranet_DisplayName_Talent,
&apos;Job Item&apos;,$Label.Intranet_DisplayName_Job,
&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name used on page component and Content Viewer, if applicable</inlineHelpText>
        <label>Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Expand_Link__c</fullName>
        <description>Used only for Flexible container items</description>
        <formula>IF(ISPICKVAL(Item_Type__c,&quot;Talent Item&quot;) || ISPICKVAL(Item_Type__c,&quot;Job Item&quot;),
TRUE, FALSE)</formula>
        <inlineHelpText>Determines if the link for View More, etc is visible</inlineHelpText>
        <label>Show Expand Link</label>
        <type>Checkbox</type>
    </fields>
    <label>Intranet Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intranet Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Intranet_Schedule__c.object
<CustomObject>
    <description>Used to determine when and to whom a Content Item is visible in a specific Container</description>
    <fields>
        <fullName>Intranet_Container__c</fullName>
        <label>Intranet Container</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Intranet_Container__c.Content_Types_Allowed_Text__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Intranet_Container__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <infoMessage>Initial Filter includes only Active containers where the Content Types Allowed have been defined.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Intranet_Container__c</referenceTo>
        <relationshipLabel>Intranet Schedules</relationshipLabel>
        <relationshipName>Intranet_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Intranet Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intranet Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IntranetPreviewController.cls
public class IntranetPreviewController {

    public IntranetContainer iContainer {get; set;}
    //public list<IntranetContent> iRelatedContent {get; set;}
    
    Id samplePageId = 'a00M0000003Eoqt';
    
    public IntranetPreviewController(){
        if(iContainer == null){
            //SelectContainer();
        }
    }
	/*
    public void SelectContainer(){
        
        Intranet_Container__c ic;
        
        ic = [select Id, Name, Container_Type__c, Container_Level__c, Parent_Container__c, Status__c, Display_Name__c, Default_Content_Item__c,
                      Show_Expand_Link__c, Top_Parent_Container_Id__c, Height__c, Width__c, Has_SubContainers__c, Max_Content_Items__c, Reference_Number__c,
                        Content_Types_Allowed__c, Minimum_Visible_Screen__c, Position__c, Screen_Priority__c, Show_Feedback_Link__c
                      from Intranet_Container__c
                     where id = :samplePageId];
        system.debug('IntranetPreviewController.BuildContainer - ic: '+ic);
        
        iContainer = new IntranetContainer(ic);
        system.debug('IntranetPreviewController.BuildContainer - iContainer: '+iContainer);
        
        map<Id,Intranet_Schedule__c> iScheds = new map<Id,Intranet_Schedule__c>([select Id, Name, Intranet_Container__c, Intranet_Item__c, Active_Status__c,
                                                                               Approval_Status__c
                                                                               from Intranet_Schedule__c
                                                                               where Intranet_Container__c = :ic.Id]);
        system.debug('IntranetPreviewController.BuildContainer - iScheds: '+iScheds);
        
        Set<Id> ItemIds = new set<Id>();
        for(Intranet_Schedule__c x : iScheds.values()){
            ItemIds.add(x.Intranet_Item__c); 
        }
        system.debug('IntranetPreviewController.BuildContainer - itemIds: '+itemIds);
        
        map<Id,Intranet_Item__c> iItems = new map<Id,Intranet_Item__c>([select Id, Name, Item_Title__c, Sort_Order__c, Active_Status__c//, //Link_Location__c
                                                                       from Intranet_Item__c
                                                                       where Id in :itemIds]);
        system.debug('IntranetPreviewController.BuildContainer - iItems: '+iItems);
        
        //for(Intranet_Schedule__c schedItem : iScheds.values()){
        //    IntranetContent i = new IntranetContent(SchedItem,iItems.get(SchedItem.Intranet_Item__c));
        //    iContainer.RelatedContent.add(i);
        //}
        system.debug('IntranetPreviewController.BuildContainer - iContainer(2): '+iContainer);
    }
    */
}