objects/IS_System_Component__c.object
<CustomObject>
    <description>Represents a part of the system metadata, such as a custom object, a workflow, or an Apex class</description>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Label__c</fullName>
        <label>Object Label</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <picklist>
            <picklistValues>
                <fullName>Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apex Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apex Sharing Reason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apex Trigger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assignment Rule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auth Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto-Response Rule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button/Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compact Layout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Console Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Field</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Label</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Metadata Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Object</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Permission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Report Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Setting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dashboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Data Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flow Definition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flow Trigger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Folder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Page Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Page Component</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SOX_Object__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this a SOX controlled object?</inlineHelpText>
        <label>SOX Object</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salesforce_Object_Id__c</fullName>
        <externalId>true</externalId>
        <label>Salesforce Object Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>IS System Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IS System Components</pluralLabel>
    <recordTypes>
        <fullName>Code</fullName>
        <active>true</active>
        <description>Salesforce: A component updated by coding, such as an Apex trigger or Visualforce page</description>
        <label>Code</label>
    </recordTypes>
    <recordTypes>
        <fullName>Configuration</fullName>
        <active>true</active>
        <description>Salesforce: A component updated by configuration, such as a workflow, custom object, field, or profile</description>
        <label>Configuration</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/IS_System_Modification__c.object
<CustomObject>
    <description>Represents a change that has/will occur in the system on an IS System Component</description>
    <fields>
        <fullName>Change_Request__c</fullName>
        <label>Change Request</label>
        <referenceTo>SFDC_Change_Request__c</referenceTo>
        <relationshipLabel>IS System Modifications</relationshipLabel>
        <relationshipName>SFDC_Modifications6</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IS_System_Component__c</fullName>
        <label>IS System Component</label>
        <referenceTo>IS_System_Component__c</referenceTo>
        <relationshipLabel>IS System Modifications</relationshipLabel>
        <relationshipName>IS_System_Modifications7</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Created for CR-5406.</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manual_Step__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This indicates a modification that cannot, or should not, be moved over automatically.  Instead, it will be done manually, after the auto-deployment.</inlineHelpText>
        <label>z1Manual Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <formula>IF(NOT(ISBLANK(API_Name__c)),API_Name__c,IF(NOT(ISBLANK(API_Name_Label__c)),API_Name_Label__c,IS_System_Component__r.Item_API_Name__c))</formula>
        <label>Object API Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Label__c</fullName>
        <formula>IF(NOT(ISBLANK(Label__c)),Label__c,IF(NOT(ISBLANK(API_Name_Label__c)),API_Name_Label__c,IS_System_Component__r.Object_Label__c))</formula>
        <label>Object Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <formula>TEXT(IS_System_Component__r.Object_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Object Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <formula>Change_Request__r.Release__r.Name</formula>
        <label>Release</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SOX_Object__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Updated via trigger from the IS System Component field</inlineHelpText>
        <label>SOX Object</label>
        <type>Checkbox</type>
    </fields>
    <label>IS System Modification</label>
    <nameField>
        <displayFormat>SFMOD-{YY}{MM}-{0}</displayFormat>
        <label>SFDC Modification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IS System Modifications</pluralLabel>
    <recordTypes>
        <fullName>Coding</fullName>
        <active>false</active>
        <label>z1Coding</label>
    </recordTypes>
    <recordTypes>
        <fullName>Deployed</fullName>
        <active>true</active>
        <description>A change that has been deployed to the production environment and is now read-only</description>
        <label>Deployed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Change_Request__c.object
<CustomObject>
    <description>For tracking and working internal Change Requests to IS systems.</description>
    <fields>
        <fullName>Coding_Actual_Hrs__c</fullName>
        <label>zCoding: Actual Hrs</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Coding_Estimated_Hrs__c</fullName>
        <label>Coding: Estimated Hrs</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>SFDC Release Cycle this Change Request scheduled for.</inlineHelpText>
        <label>Release</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5))</booleanFilter>
            <filterItems>
                <field>SFDC_Release__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Deployed</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Level II, Level III</value>
            </filterItems>
            <filterItems>
                <field>SFDC_Release__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>eTech Dev</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>App Update</value>
            </filterItems>
            <filterItems>
                <field>SFDC_Release__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>App Release</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>SFDC_Release__c</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Release_Date__c</fullName>
        <formula>Release__r.Target_Release_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Change Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Release__c.object
<CustomObject>
    <fields>
        <fullName>Coding_Estimated_Hrs__c</fullName>
        <label>Coding: Estimated Hrs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Change_Requests__c</fullName>
        <label>No. of Change Requests</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Manual_Setup_Mods__c</fullName>
        <label>No. of Manual Setup Mods</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Modifications__c</fullName>
        <label>No. of Modifications</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Release_Date__c</fullName>
        <inlineHelpText>Date the change request items associated with this list are scheduled to be available to users in Production.</inlineHelpText>
        <label>Target Release Date</label>
        <type>Date</type>
    </fields>
    <label>SFDC Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFDC Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Request_Comment__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Analysis/Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Import/Updates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Troubleshooting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SFDC_Change_Request__c</fullName>
        <label>SFDC Change Request</label>
        <referenceTo>SFDC_Change_Request__c</referenceTo>
        <relationshipName>SFDC_Request_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <inlineHelpText>Enter the time spend on this activity in quarter hour increments.</inlineHelpText>
        <label>Time (Hours)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>IS Dev Activity</label>
    <nameField>
        <displayFormat>{YY}{MM}{DD}{0}</displayFormat>
        <label>Comment#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IS Dev Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestSFDCChangeRequestHelper.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData=false)
private class TestSFDCChangeRequestHelper {
/*
  Purpose      :   Test class for Trigger_SFDC_ChangeRequest
        
  Create By    :   Simplyforce Technology
  
  Created Date  :   05/29/2012
  
  Current Version  :   V1.0
  
  Revision Log  :  V1.0 - Created
                   V1.1 - Ajit Surana - Added new method (test_rollUpStorySizeDataOnSFDCRelease) - 04/18/2014 - CR-20140303-4690
                   V1.2 - Bhavi Sharma - 05/02/2014 - updated myUnitTest - CR-20140225-4635
                   V1.3 - Abhinav Sharma - 03/10/2015 - CR-20140508-5406            
  Coverage    :  100%
*/

    //Test 
    static testmethod void myUnitTest() {
        
        //System Administratot User
        User sysAdmin = [SELECT Name, Id FROM User 
                            WHERE Profile.Name = 'System Administrator' AND IsActive = true 
                            AND Name != 'Salesforce Administrator' AND FirstName != 'Salesforce' LIMIT 1];
        
        system.runAs(sysAdmin) {
        
            //Insert release record
            SFDC_Release__c release = new SFDC_Release__c (name = 'Test',  Target_Release_Date__c = Date.today());
            insert release;
            
            //Create a list of data to be inserted
            List<SFDC_Change_Request__c> changeRequests = new List<SFDC_Change_Request__c>();
            
            //Create records in list
            for(Integer i = 0; i < 200; i++) {
                
                //Insert data in change request
                changeRequests.add(new SFDC_Change_Request__c (Title__c = 'Test-' + i, Release__c = release.Id));
            }
            
            //Start Test from here 
            Test.startTest();
            
            //Insert changeRequest
            insert changeRequests;
            
            //Insert SFDC Modifications
            List<IS_System_Modification__c> modifications = new List<IS_System_Modification__c>();
            
            //create a component
            IS_System_Component__c component1 = new IS_System_Component__c(Name = 'will auto-populate',
                                                                           Object_Label__c = 'Account',
                                                                           Object_API_Name__c = 'Account',
                                                                           Object_Type__c = 'Object',
                                                                           Salesforce_Object_Id__c = '01I4B0000000007AAA',
                                                                           SOX_Object__c = FALSE);
            insert component1;
            
            //Loop through the change requests and create the modifications for each
            for(SFDC_Change_Request__c cR : changeRequests) {
                
                //add modification record in list
                modifications.add(new IS_System_Modification__c (Change_Request__c = cR.Id, Manual_Step__c = true, Label__c = 'Test', IS_System_Component__c = component1.Id));
            }
            
            //Insert modification data
            insert modifications;
            
            //Insert CRM Activities
            List<SFDC_Request_Comment__c> comments = new List<SFDC_Request_Comment__c>();
            
            //Loop through the change requests and create the comments for each
            for(SFDC_Change_Request__c cR : changeRequests) {
                
                //add modification record in list
                comments.add(new SFDC_Request_Comment__c(SFDC_Change_Request__c = cR.Id, Activity_Type__c = 'Analysis/Design', Time__c = 1));
            }
            
            //Insert comments data
            insert comments;
            
            //Assert for the result
            release = [Select No_of_Change_Requests__c, No_of_Modifications__c, No_of_Manual_Setup_Mods__c, Coding_Estimated_Hrs__c, Coding_Actual_Hrs__c,
                            Config_Estimated_Hrs__c, Config_Actual_Hrs__c, Design_Estimated_Hrs__c, Design_Actual_Hrs__c, IS_QA_Estimated_Hrs__c, 
                            IS_QA_Actual_Hrs__c, User_Documentation_Actual_Hrs__c from SFDC_Release__c where Id =: release.Id];
            
            System.assertEquals(changeRequests.size(), release.No_of_Change_Requests__c);
            System.assertEquals(modifications.size(), release.No_of_Modifications__c);
            System.assertEquals(modifications.size(), release.No_of_Manual_Setup_Mods__c);
            System.assertEquals(null, release.Coding_Estimated_Hrs__c);
            System.assertEquals(0, release.Coding_Actual_Hrs__c);
            System.assertEquals(null, release.Config_Estimated_Hrs__c);
            System.assertEquals(0, release.Config_Actual_Hrs__c);
            System.assertEquals(200, release.Design_Estimated_Hrs__c);
            System.assertEquals(200, release.Design_Actual_Hrs__c);
            System.assertEquals(null, release.IS_QA_Estimated_Hrs__c);
            System.assertEquals(0, release.IS_QA_Actual_Hrs__c);
            System.assertEquals(0, release.User_Documentation_Actual_Hrs__c);
            
            //Loop through the change requests and Update the fields 
            for(SFDC_Change_Request__c cR : changeRequests) {
                
                //Update the CR data
                cR.Coding_Estimated_Hrs__c = 1;
                cR.Config_Estimated_Hrs__c = 1;
                cR.Design_Estimated__c = 1;
                cR.IS_QA_Estimated_Hrs__c = 1;
                cR.SOX_Certification_Required__c = Constants.YES;
            }
            
            //Update data
            update changeRequests;
            
            comments = new List<SFDC_Request_Comment__c>();
            
            //Assert for the results
            //Loop through the change requests and create the comments for each
            for(SFDC_Change_Request__c cR : changeRequests) {
                
                //add modification record in list
                comments.add(new SFDC_Request_Comment__c(SFDC_Change_Request__c = cR.Id, Activity_Type__c = 'Analysis/Design', Time__c = 1));
                comments.add(new SFDC_Request_Comment__c(SFDC_Change_Request__c = cR.Id, Activity_Type__c = 'Coding', Time__c = 1));
                comments.add(new SFDC_Request_Comment__c(SFDC_Change_Request__c = cR.Id, Activity_Type__c = 'Configuration', Time__c = 1));
                comments.add(new SFDC_Request_Comment__c(SFDC_Change_Request__c = cR.Id, Activity_Type__c = 'QA', Time__c = 1));
                comments.add(new SFDC_Request_Comment__c(SFDC_Change_Request__c = cR.Id, Activity_Type__c = 'User Documentation', Time__c = 1));
                
            }
            
            //Insert comments data
            insert comments;
            
            //Assert for the result
            release = [Select No_of_Change_Requests__c, No_of_Modifications__c, No_of_Manual_Setup_Mods__c, Coding_Estimated_Hrs__c, Coding_Actual_Hrs__c,
                            Config_Estimated_Hrs__c, Config_Actual_Hrs__c, Design_Estimated_Hrs__c, Design_Actual_Hrs__c, IS_QA_Estimated_Hrs__c, 
                            IS_QA_Actual_Hrs__c, User_Documentation_Actual_Hrs__c from SFDC_Release__c where Id =: release.Id];
            
            System.assertEquals(200, release.Coding_Estimated_Hrs__c);
            System.assertEquals(200, release.Coding_Actual_Hrs__c);
            System.assertEquals(200, release.Config_Estimated_Hrs__c);
            System.assertEquals(200, release.Config_Actual_Hrs__c);
            System.assertEquals(200, release.Design_Estimated_Hrs__c);
            System.assertEquals(400, release.Design_Actual_Hrs__c);
            System.assertEquals(200, release.IS_QA_Estimated_Hrs__c);
            System.assertEquals(200, release.IS_QA_Actual_Hrs__c);
            System.assertEquals(200, release.User_Documentation_Actual_Hrs__c);
            
            //Loop through the change requests and blankout Release            
            for(SFDC_Change_Request__c cR : changeRequests) {
                
                //Blank out Release
                cR.Release__c = null;
                cR.Release_Change_Reason__c = 'Test';
            }
            
            //Update
            update changeRequests;
            
            //Assert for the result
            release = [Select No_of_Change_Requests__c, No_of_Modifications__c, No_of_Manual_Setup_Mods__c, Coding_Estimated_Hrs__c, Coding_Actual_Hrs__c,
                            Config_Estimated_Hrs__c, Config_Actual_Hrs__c, Design_Estimated_Hrs__c, Design_Actual_Hrs__c, IS_QA_Estimated_Hrs__c, 
                            IS_QA_Actual_Hrs__c, User_Documentation_Actual_Hrs__c from SFDC_Release__c where Id =: release.Id];
            
            System.assertEquals(0, release.Coding_Estimated_Hrs__c);
            System.assertEquals(0, release.Coding_Actual_Hrs__c);
            System.assertEquals(0, release.Config_Estimated_Hrs__c);
            System.assertEquals(0, release.Config_Actual_Hrs__c);
            System.assertEquals(0, release.Design_Estimated_Hrs__c);
            System.assertEquals(0, release.Design_Actual_Hrs__c);
            System.assertEquals(0, release.IS_QA_Estimated_Hrs__c);
            System.assertEquals(0, release.IS_QA_Actual_Hrs__c);
            System.assertEquals(0, release.User_Documentation_Actual_Hrs__c);
            
            //Loop through the change requests and populate Release back
            for(SFDC_Change_Request__c cR : changeRequests) {
                
                //Blank out Release
                cR.Release__c = release.Id;
                cR.Release_Change_Reason__c = 'Test1';
            }
            
            update changeRequests;
            
            //Assert for the result
            release = [Select No_of_Change_Requests__c, No_of_Modifications__c, No_of_Manual_Setup_Mods__c, Coding_Estimated_Hrs__c, Coding_Actual_Hrs__c,
                            Config_Estimated_Hrs__c, Config_Actual_Hrs__c, Design_Estimated_Hrs__c, Design_Actual_Hrs__c, IS_QA_Estimated_Hrs__c, 
                            IS_QA_Actual_Hrs__c, User_Documentation_Actual_Hrs__c from SFDC_Release__c where Id =: release.Id];
            
            System.assertEquals(200, release.Coding_Estimated_Hrs__c);
            System.assertEquals(200, release.Coding_Actual_Hrs__c);
            System.assertEquals(200, release.Config_Estimated_Hrs__c);
            System.assertEquals(200, release.Config_Actual_Hrs__c);
            System.assertEquals(200, release.Design_Estimated_Hrs__c);
            System.assertEquals(400, release.Design_Actual_Hrs__c);
            System.assertEquals(200, release.IS_QA_Estimated_Hrs__c);
            System.assertEquals(200, release.IS_QA_Actual_Hrs__c);
            System.assertEquals(200, release.User_Documentation_Actual_Hrs__c);
            
            //Delete the change requests
            delete changeRequests;
            
            //Assert for the result
            release = [Select No_of_Change_Requests__c, No_of_Modifications__c, No_of_Manual_Setup_Mods__c, Coding_Estimated_Hrs__c, Coding_Actual_Hrs__c,
                            Config_Estimated_Hrs__c, Config_Actual_Hrs__c, Design_Estimated_Hrs__c, Design_Actual_Hrs__c, IS_QA_Estimated_Hrs__c, 
                            IS_QA_Actual_Hrs__c, User_Documentation_Actual_Hrs__c from SFDC_Release__c where Id =: release.Id];
            
            System.assertEquals(0, release.No_of_Change_Requests__c);
            
            //Undelete the record
            undelete changeRequests;
            
            //Assert for the result
            release = [Select No_of_Change_Requests__c, No_of_Modifications__c, No_of_Manual_Setup_Mods__c, Coding_Estimated_Hrs__c, Coding_Actual_Hrs__c,
                            Config_Estimated_Hrs__c, Config_Actual_Hrs__c, Design_Estimated_Hrs__c, Design_Actual_Hrs__c, IS_QA_Estimated_Hrs__c, 
                            IS_QA_Actual_Hrs__c, User_Documentation_Actual_Hrs__c from SFDC_Release__c where Id =: release.Id];
            
            System.assertEquals(changeRequests.size(), release.No_of_Change_Requests__c);
            
            //Stop test here
            Test.stopTest();
        
        }
    }
    
    //Added by Ajit Surana - 04/18/2014 - CR-20140303-4690
    //Test method assign a value to each CR based on the Story Size field. Add all values together & populate this on release object.
    static testMethod void test_rollUpStorySizeDataOnSFDCRelease(){
        
        //Insert release record
        List<SFDC_Release__c> releaseList = new List<SFDC_Release__c> ();
        
        releaseList.add(new SFDC_Release__c(Name = 'Release 1.0', Target_Release_Date__c = Date.today()));
        releaseList.add(new SFDC_Release__c (Name = 'Release 2.0', Target_Release_Date__c = Date.today()));
        insert releaseList;  
        
        //Insert test 
        IS_System__c testISRecord = new IS_System__c (Name = 'IS Record');
        insert testISRecord;
        
        Id employeeRTId = Util.RecordTypeId('Contact', 'Employee');
        
        //Insert a test contact
        Contact contact = new Contact(LastName = 'TestContact', Email = 'test@test.com', Employee_User_Record__c = UserInfo.getUserId(),
                                    RecordTypeId = employeeRTId);
        insert contact;
       
        //Insert Change Request record
        List<SFDC_Change_Request__c> changeRequestList = new List<SFDC_Change_Request__c> ();
        
        changeRequestList.add(new SFDC_Change_Request__c(Title__c = 'Test CR 1.1', IS_System__c = testISRecord.Id, Priority__c = 'A-Critical', Status__c = '03-Approved', Users_Affected__c = 'All',
                                Requested_By2__c = contact.Id, Business_Operations_Contact2__c = contact.Id , Request_Description__c = 'Testing', 
                                Business_Justification__c = 'Test'));
        changeRequestList.add(new SFDC_Change_Request__c(Title__c = 'Test CR 1.1', IS_System__c = testISRecord.Id, Priority__c = 'A-Critical', Status__c = '03-Approved', Users_Affected__c = 'All',
                                Requested_By2__c = contact.Id, Business_Operations_Contact2__c = contact.Id , Request_Description__c = 'Testing', 
                                Business_Justification__c = 'Test'));
        changeRequestList.add(new SFDC_Change_Request__c (Title__c = 'Test CR 1.1', IS_System__c = testISRecord.Id, Priority__c = 'A-Critical', Status__c = '03-Approved', Users_Affected__c = 'All',
                                Requested_By2__c = contact.Id, Business_Operations_Contact2__c = contact.Id , Request_Description__c = 'Testing', 
                                Business_Justification__c = 'Test'));
        changeRequestList.add(new SFDC_Change_Request__c(Title__c = 'Test CR 1.1', IS_System__c = testISRecord.Id, Priority__c = 'A-Critical', Status__c = '03-Approved', Users_Affected__c = 'All',
                                Requested_By2__c = contact.Id, Business_Operations_Contact2__c = contact.Id , Request_Description__c = 'Testing', 
                                Business_Justification__c = 'Test'));
        
        //Start Test from here 
        Test.startTest();
        
        insert changeRequestList;
        
        //Assert for list size
        System.assert(changeRequestList.size()>0);
        
        //Move two CR's to first Release with both Story Size field & Release Change Reason field populated
        changeRequestList[0].Release__c = releaseList[0].Id;
        changeRequestList[0].Story_Size__c = 'S';
        changeRequestList[0].Release_Change_Reason__c = 'Updating record';
        
        changeRequestList[1].Release__c = releaseList[0].Id;
        changeRequestList[1].Story_Size__c = 'M';
        changeRequestList[1].Release_Change_Reason__c = 'Testing record';
        
        changeRequestList[2].Release__c = releaseList[1].Id;
        changeRequestList[2].Story_Size__c = 'XS';
        changeRequestList[2].Release_Change_Reason__c = 'Updating record';
        
        changeRequestList[3].Release__c = releaseList[1].Id;
        changeRequestList[3].Story_Size__c = 'L';
        changeRequestList[3].Release_Change_Reason__c = 'Testing record';
        
        //Update Change Request List
        update changeRequestList;
        
        //Query to retreive SFDC Release records associated with above Change Request records
        List<SFDC_Release__c> release = [Select Id, Story_Points__c from SFDC_Release__c where Id=: releaseList[0].Id];
        
        //Assert for the result 
        System.assert(release.size()>0);
        System.assertEquals(5, release[0].Story_Points__c);
        
        //Move first 2 CR's to secon Release so that Story Size on Release 1.0 is blank
        changeRequestList[2].Release__c = releaseList[0].Id;
        changeRequestList[2].Release_Change_Reason__c = 'Reviewing';
        
        //Update list
        update changeRequestList;
        
        //Query to retreive SFDC Release records
        release = [Select Id, Story_Points__c from SFDC_Release__c where Id=: releaseList[0].Id];
        
        //Assert for the result 
        System.assert(release.size()>0);
        System.assertEquals(6, release[0].Story_Points__c);
        
        //Now remove first 2 CR's from first Release so that its Story_Points__c field value gets updated
        delete changeRequestList[0];
        delete changeRequestList[1];
        
        //Query to retreive SFDC Release records
        release = [Select Id, Story_Points__c from SFDC_Release__c where Id=: releaseList[0].Id];
        
        //Assert for the result 
        System.assert(release.size()>0);
        System.assertEquals(1, release[0].Story_Points__c);
        
        //Now remove any 2 CR's from first Release so that its Story_Points__c field value updated to 0
        delete changeRequestList[2];
        
        //Query to retreive SFDC Release records
        release = [Select Id, Story_Points__c from SFDC_Release__c where Id=: releaseList[0].Id];
        
        //Assert for the result 
        System.assert(release.size()>0);
        System.assertEquals(0, release[0].Story_Points__c);
        
        //Stop Test from here 
        Test.stopTest();
        
    }
}