objects/IS_Use_Case__c.object
<CustomObject>
    <description>Describes a set of steps to complete an action.  Use Cases are linked to IS Functions and describe how the function is used.</description>
    <fields>
        <fullName>Latest_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to associate the new version of a use case with the old one</description>
        <inlineHelpText>When a Use Case is updated, link to the new version here.</inlineHelpText>
        <label>Latest Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>IS_Use_Case__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Use Case</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>IS_Use_Case__c</referenceTo>
        <relationshipLabel>Use Case Version History</relationshipLabel>
        <relationshipName>IS_Use_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active = In use today
Inactive = Superseded or No longer used
Design = In design
Development = In development
Beta = In QA / UAT</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Update_Type__c</fullName>
        <inlineHelpText>An archived version is created for Major and Minor edits.</inlineHelpText>
        <label>Update Type</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Revision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Use_Case_Reference_Text__c</fullName>
        <label>Use Case Reference Text</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_Case_Reference_Unique__c</fullName>
        <description>Used to verify that a duplicate number for the same IS System Junction is not created</description>
        <label>Use Case Reference Unique</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Use_Case_Reference_Version__c</fullName>
        <label>Use Case Reference Version</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_Case_Reference__c</fullName>
        <formula>&quot;UC-&quot; &amp; RIGHT(IS_System_Junction__r.System_Junction_Number__c ,LEN(IS_System_Junction__r.System_Junction_Number__c)-3) &amp; &quot;-&quot; &amp; TEXT(Use_Case_Number__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Combination of System Number, Process Number, and Use Case Number</inlineHelpText>
        <label>Use Case Reference</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Number__c</fullName>
        <defaultValue>&quot;0.00.00&quot;</defaultValue>
        <description>Updated via code based on Update Type.  Ex format 1.01.001</description>
        <inlineHelpText>Whole number units indicate major updates, such as replacement.  Decimal numbers indicate minor record edits</inlineHelpText>
        <label>Version Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Versioned_Status__c</fullName>
        <description>Used in workflow and validation formulas</description>
        <formula>OR (
  ISPICKVAL( Status__c , &quot;Active&quot;),
  ISPICKVAL( Status__c , &quot;Beta&quot;),
  ISPICKVAL( Status__c , &quot;Development&quot;)
)</formula>
        <label>Versioned Status</label>
        <type>Checkbox</type>
    </fields>
    <label>IS Use Case</label>
    <nameField>
        <displayFormat>UC-{00000}</displayFormat>
        <label>IS Use Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IS Use Cases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ISUseCaseHelper.cls
/**
 * 
 * Desription      :   	helper class for the IS Use Case object
 * 
 * Revision Logs   :   	v1.0 - Victor Hanson - 10/30/2015 - Created
 * 
 * 
 **/
public class ISUseCaseHelper {
    
    //record type ids for the IS Use Case object
    public final static Id IS_UC_RT_USE_CASE = Schema.SObjectType.IS_Use_Case__c.getRecordTypeInfosByName().get('Use Case').getRecordTypeId();
    public final static Id IS_UC_RT_VERSION_HISTORY = Schema.SObjectType.IS_Use_Case__c.getRecordTypeInfosByName().get('Version History').getRecordTypeId();
    
    /**
     * @description: create a cloned version of the old record when update type is "major" or "minor"
     **/
    public static void cloneOldUC(list<IS_Use_Case__c> useCases, map<Id, IS_Use_Case__c> oldMapUseCases) {
        list<IS_Use_Case__c> useCasesToClone = new list<IS_Use_Case__c>();
        for (IS_Use_Case__c uc : useCases) {
            IS_Use_Case__c oldUC = oldMapUseCases.get(uc.Id);
            if (uc.Versioned_Status__c && 
                uc.Update_Type__c != null && 
                (uc.Update_Type__c.equalsIgnoreCase(Label.UC_Update_Type_Major) ||
                 uc.Update_Type__c.equalsIgnoreCase(Label.UC_Update_Type_Minor))) 
            {
                //add the cloned version of the old UC to our list
                IS_Use_Case__c clonedUC = oldUC.clone();
                clonedUC.Latest_Version__c = uc.Id;
                clonedUC.RecordTypeId = IS_UC_RT_VERSION_HISTORY;
                clonedUC.Use_Case_Reference_Text__c = uc.Use_Case_Reference__c;
                clonedUC.Use_Case_Reference_Unique__c = null;
                clonedUC.Use_Case_Reference_Version__c = uc.Use_Case_Reference__c + '--' + uc.Version_Number__c;
                clonedUC.Status__c = 'Inactive';
                useCasesToClone.add(clonedUC);
            }
        }
        if (useCasesToClone.size() > 0) insert useCasesToClone;
    }
    
    /**
    * @description: update the version number based on the update type
    **/
    public static void incrementVersionNumber(list<IS_Use_Case__c> useCases) {
        for (IS_Use_Case__c uc : useCases) {
            
            if (uc.Versioned_Status__c) {
                //update the version number
                uc.Version_Number__c = getVersionNumber(uc);
                
                //change the update type back to a blank value
                //uc.Update_Type__c = null;
            }
        }
    }
    
    /**
     * @description: return the version number from a use case based on the update type
     **/
    public static string getVersionNumber(IS_Use_Case__c uc) {
        //split the version number
        list<string> versions = uc.Version_Number__c.split('\\.');
        if (versions.size() < 3) throw new customException('Version number should be in the format #.##.##');
        
        integer major = integer.valueOf(versions[0]);
        integer minor = integer.valueOf(versions[1]);
        integer revision = integer.valueOf(versions[2]);
        
        if (uc.Update_Type__c != null) {
            if (uc.Update_Type__c.equalsIgnoreCase(Label.UC_Update_Type_Major)) major += 1;
            else if (uc.Update_Type__c.equalsIgnoreCase(Label.UC_Update_Type_Minor)) minor += 1;
            else if (uc.Update_Type__c.equalsIgnoreCase(Label.UC_Update_Type_Revision)) revision += 1;
        }
        //concatenate the various version types to populate the version number
        return major + '.' + lPad(minor, 2) + '.' + lPad(revision, 2);
    }
    
    /**
     * @description: leftPads the value with the specified number of zeros
     **/
    public static string lPad(integer val, integer numChars) {
        string valStr = string.valueOf(val);
        if (valStr.length() < numChars) valStr = valStr.leftPad(numChars, '0');
        return valStr;
    }
}