objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Reference_Status__c</fullName>
        <inlineHelpText>Indicate whether Institution serves as Referece for Product or has Ambassador Contact present.</inlineHelpText>
        <label>Reference Status</label>
        <picklist>
            <picklistValues>
                <fullName>Reference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambassador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reference__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>Reference_Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dedicated_Advisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dedicated Advisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Type__c</fullName>
        <label>Member Type</label>
        <picklist>
            <picklistValues>
                <fullName>NASA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Membership</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Membership must be related to the Contact&apos;s Institution.</errorMessage>
            <filterItems>
                <field>Membership__c.Account_Name__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Institution__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Membership__c</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>Reference_Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NASA_Associate_Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NASA Associate Principal</label>
        <referenceTo>User</referenceTo>
        <relationshipName>References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NASA_Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NASA Principal</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Modules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Modules4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Module__c</fullName>
        <label>Reference Module</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Status__c</fullName>
        <label>Reference Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vetted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Referenceable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reference</label>
    <nameField>
        <displayFormat>Ref-{000000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Reference_Request_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Reference Request Contacts</relationshipLabel>
        <relationshipName>Reference_Request_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contact.Reference_Program_Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reference Request Contacts</relationshipLabel>
        <relationshipName>Reference_Request_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference Lead from the related Reference Request.</description>
        <label>Reference Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Reference Request Contacts (Reference Lead)</relationshipLabel>
        <relationshipName>Reference_Request_Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Modules__c</fullName>
        <label>Reference Modules</label>
        <type>TextArea</type>
    </fields>
    <label>Reference Request Contact</label>
    <nameField>
        <displayFormat>RRC-{0000}</displayFormat>
        <label>Reference Request Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Request Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Batch_SetReferenceDefaults.cls
/**
*  Description     :    Batch class to update few fields on Reference records(Dedicated_Advisor__c, NASA_Principal__c, NASA_Associate_Principal__c) 
*
*  Created By      :    Rajeev Jain      
* 
*  Created Date    :    09/05/2016   
* 
*  Revision Logs   :    V_1.0 - Created - Release 53 - CR-20160809-10096 
*                      
**/
global class Batch_SetReferenceDefaults implements Database.Batchable<SObject>, Database.Stateful {
    
    //Debug Log
    global String debugLog;
    public String queryStr = null;
    
    //Batch Constructor
    global Batch_SetReferenceDefaults() {
        
        //Inititlize debug Log
        debugLog = '';
        
        //Checking for the null value and accordingly setting the defaults
        if(queryStr == null) {
        	
			//Constructing query string for fetching records from the database
            queryStr = 'SELECT Id, Membership__c, Dedicated_Advisor__c, RecordTypeId, Reference_Module__c, Reference_Lead__c,' +
            			' Member_Type__c, Contact_Name__c, Institution__c, NASA_Principal__c, NASA_Associate_Principal__c' +
						' FROM Reference__c WHERE' +
                		' (Reference_Status__c = \'Pending Approval\' OR Reference_Status__c = \'Scheduled\' OR Reference_Status__c = \'Vetted\')';     
            
            //Debugging for the query string
            System.debug('@@@@ Query string in constructor ' + queryStr);
        }            
    }
    
    // Start(Database.BatchableContext) method of the Database.Batchable class
    global Database.queryLocator start(Database.BatchableContext ctx) {
                         
        //Debug log helpful in analysis
        System.debug('******** Batch Process for Reference Updates Started ******* ');
        
        //Query all reference records which are in specific status
        return Database.getQueryLocator(queryStr);       
    }
    
    // Execute(Database.BatchableContext, list<Sobject>) method of the Database.Batchable class
    global void execute(Database.BatchableContext ctx, list<Sobject> scope){
        
        try{
            
            //List to Hold the Reference Request Records which are needs to update
            List<Reference__c> referenceRequests = new List<Reference__c>();
            
            //String variable to hold the error message string in case of any failure
            String logMessage = '';
            
            //Call the Reference Trigger Helper class method
            ReferenceTriggerHelper.setReferenceDefaults((List<Reference__c>)scope);
            
            //Set to hold the contact records IDs associated to reference record via "Contact Name"
            Set<Id> setContactsIds = new Set<Id>();
            
            //Now check if specific fields are not null then update those records
            //Loop over references
            for(Reference__c ref : (List<Reference__c>)scope) {
                referenceRequests.add(ref);
                if(ref.Contact_Name__c != null)
                	setContactsIds.add(ref.Contact_Name__c);
            }
                
            //Check the size of the list 
            if(referenceRequests.size() > 0) {
                
                //ByPass All Triggers
                Util.byPassAllTriggers = true;
                
                //Error recording and updating records
                logMessage = Util.createLog(Database.update(referenceRequests, false));
                
                //Enabling triggers
                Util.byPassAllTriggers = false;
                
                //Checking set for it's size
                if(setContactsIds.size() > 0) {
                    
                    //List of reference request contacts to be updated
                    List<Reference_Request_Contact__c> listOfReferenceRequestContacts = new List<Reference_Request_Contact__c>(); 
                    
                    //Retrieving "Reference Request Contact" records associated with current scope based reference records
                    for(Reference_Request_Contact__c rrC : [SELECT ID, Reference_Contact__c, Reference_Modules__c, Approver__c 
                                                            FROM Reference_Request_Contact__c
                                                            WHERE Reference_Contact__c != null
                                                            AND Reference_Contact__c IN : setContactsIds
                                                           ]) {
                    	listOfReferenceRequestContacts.add(rrC);                                           
                    }
                    
                    //Checking list for it's size
                    if(listOfReferenceRequestContacts.size() > 0) {
                        
                        //ByPass All Triggers
                		Util.byPassAllTriggers = true;
                        
                        //Populating "approver" field value on the list based RRC records
                        ReferenceRequestContactHelper.populateApprover(listOfReferenceRequestContacts);
                        
                        //Error recording and updating records
                        logMessage += Util.createLog(Database.update(listOfReferenceRequestContacts, false));
                        
                        //Checking errors log messages string for blank value and append 
                        //it to final error message string only and only if it have proper value with it
                        if(logMessage != '') 
                            debugLog += logMessage;
                        
                        //Enabling triggers
                		Util.byPassAllTriggers = false;
                    }
                }
            }
        }catch(Exception e){
            debugLog += e + '';
        }
    }
    
    //Handles errors if found any
    global void finish(Database.BatchableContext ctx) {
        
        //Debug log helpful in analysis
        System.debug('******** Batch Process for Reference Updates Completed ******* ');
        
        //Create final email message
        if(debugLog != '') {
            
            //Send log to admin
            Util.sendBatchStatus(ctx.getJobId(), 'Batch_SetReferenceDefaults', debugLog, Label.Salesforce_Admin_Email);
        }
    }
}