objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CR-3485-This field is used in an integration with Eloqua. Please research with the appropriate stakeholders/liaisons before altering it&apos;s meaning, usage, field type or other field characteristics. Do not delete or change the current API name.</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reference_Request__c.object
<CustomObject>
    <description>This object is used to track the request for a reference or references.</description>
    <fields>
        <fullName>Date_Needed_By__c</fullName>
        <description>Date by which the reference recommendations are needed</description>
        <label>Date Needed By</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_References_Needed__c</fullName>
        <label>Number of References Needed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reference_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Reference Requests (Reference Lead)</relationshipLabel>
        <relationshipName>Reference_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Modules__c</fullName>
        <label>Reference Module(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Type_Needed__c</fullName>
        <label>Reference Type Needed</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Site Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Conference</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requesting_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requesting Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reference Requests</relationshipLabel>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requesting_Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requesting Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reference Requests</relationshipLabel>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Membership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Membership</label>
        <referenceTo>Membership__c</referenceTo>
        <relationshipLabel>Reference Requests</relationshipLabel>
        <relationshipName>Reference_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Reference Requests (Submitted By)</relationshipLabel>
        <relationshipName>Reference_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Request</label>
    <nameField>
        <displayFormat>RefReq-{00000000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Reference_Request_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Reason__c</fullName>
        <label>Approval Reason</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delayed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference_Attributes__c</fullName>
        <label>Reference Attributes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reference_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contact.Reference_Program_Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reference Request Contacts</relationshipLabel>
        <relationshipName>Reference_Request_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Institution__c</fullName>
        <formula>Reference_Contact__r.Account.Name</formula>
        <label>Reference Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference Lead from the related Reference Request.</description>
        <label>Reference Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Reference Request Contacts (Reference Lead)</relationshipLabel>
        <relationshipName>Reference_Request_Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Modules__c</fullName>
        <label>Reference Modules</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reference_Request_Source__c</fullName>
        <formula>Reference_Request__r.Source__c</formula>
        <label>Reference Request Source</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Request</label>
        <referenceTo>Reference_Request__c</referenceTo>
        <relationshipLabel>Reference Request Contacts</relationshipLabel>
        <relationshipName>Reference_Request_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Reference Request Contacts (Submitted by)</relationshipLabel>
        <relationshipName>Reference_Request_Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reference Request Contact</label>
    <nameField>
        <displayFormat>RRC-{0000}</displayFormat>
        <label>Reference Request Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Request Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_ApprovalOverrideController.cls
/**
 *  Purpose         :   Test code for the ApprovalOverrideController class
 * 
 *  Created By      :   Victor Hanson
 * 
 *  Created Date    :   1/13/2016
 * 
 * Revision Logs    :   V_1.0 - Created
 *
 **/ 
@isTest
public class Test_ApprovalOverrideController {
    
    //setup test data
    @testSetup static void setup() {
        //setup the program collection test data
        Test_ReferenceRequestController.setupTestData();
        
        util.BypassAllTriggers = true;
        //create the requesting contact record
        Contact reqContact = TestUtilities.CreateNewContact(false);
        reqContact.lastName = 'reqContact';
        reqContact.recordTypeId = Test_ReferenceRequestController.CONTACT_EXTERNAL_RT_ID;
        insert reqContact;
        util.BypassAllTriggers = false;
        
        //get the existing ambassador contact, which was created in testSetup
        Contact ambassadorContact = [SELECT Id FROM Contact WHERE LastName = 'Ambassador'];
        
        //create the membership related to the institution
        util.BypassAllTriggers = true;
        Membership__c mem = new Membership__c(Account_Name__c = reqContact.AccountId);
        insert mem;
        util.BypassAllTriggers = false;
        
    test.startTest();
        //create the Reference Request
        Reference_Request__c req = new Reference_Request__c(Request_Status__c = 'New',
                                                            Reference_Modules__c = 'CCC',
                                                            Requesting_Contact__c = reqContact.Id,
                                                            Requesting_Institution__c = reqContact.AccountId,
                                                            Source_Membership__c = mem.Id,
                                                            Date_Needed_By__c = Date.today(),
                                                            Number_of_References_Needed__c = 1,
                                                            Reference_Type_Needed__c = 'Individual',
                                                            Submitted_By__c = userInfo.getUserId());
        insert req;
        
        //create the Reference Request Contact
        Reference_Request_Contact__c rrc = new Reference_Request_Contact__c(Reference_Contact__c = ambassadorContact.Id,
                                                                            Reference_Request__c = req.Id,
                                                                            Reference_Modules__c = 'CCC',
                                                                            Approval_Status__c = 'Pending',
                                                                            Reference_Lead__c = userInfo.getUserId());
        insert rrc;
        
        //submit all reference request contacts for approval
        ReferenceRequestContactHelper.submitForApproval(new set<Id>{rrc.Id});
    test.stopTest();
    }
    
    /**
     * 
     * @description: Approve a reference request contact record.  Verify the comments and approval status are reflected on the record
     * 
     **/
    static testMethod void testApproved() {
        //get the reference request contact that was created in the testSetup method
        Reference_Request_Contact__c rrc = [SELECT Id, Reference_Modules__c, Reference_Attributes__c FROM Reference_Request_Contact__c];
        
        //verify there is an approval pending
        Id pendingApprovalId = ApprovalOverrideController.getWorkItemId(rrc.Id);
        system.assertNotEquals(null, pendingApprovalId, 'The Reference Request Contact should have a pending approval');
        
        //set the page reference
        PageReference pageRef = Page.ApprovalOverride;
        test.setCurrentPage(pageRef);
        
        string APPROVAL_INSTRUCTIONS = 'Approving this request will update the Status to Approved and notify the Reference Lead.';
        string approvalComments = 'approved!!';
        boolean isApproved = true;
        
        //Set currentpage parameters
        ApexPages.currentPage().getParameters().put('recordId', rrc.Id);
        ApexPages.currentPage().getParameters().put('objLabel', 'Reference Request Contact');
        ApexPages.currentPage().getParameters().put('fields', 'Submitted_By__r.Name,Reference_Request_Source__c,Reference_Institution__c,Reference_Contact__r.Name,Reference_Modules__c,Reference_Attributes__c');
        ApexPages.currentPage().getParameters().put('commentField', 'Approval_Reason__c');
        ApexPages.currentPage().getParameters().put('instructions', APPROVAL_INSTRUCTIONS);
        
        //instantiate the controller
        ApprovalOverrideController controller = new ApprovalOverrideController();
        system.assertEquals(6, controller.fieldValueMap.size());
        
        for (ApprovalOverrideController.fld field : controller.flds) {
            if (field.label == 'Reference Modules') system.assertEquals(rrc.Reference_Modules__c, field.value);
        }
        
        //approve
        ApprovalOverrideController.getApprovalResult(rrc.Id, isApproved, approvalComments, 'Approval_Reason__c');
        
        //get the reference request contact
        rrc = [SELECT Id, Approval_Reason__c, Approval_Status__c FROM Reference_Request_Contact__c WHERE Id = :rrc.Id];
        //verify the approval comments populated correctly
        system.assertEquals(approvalComments, rrc.Approval_Reason__c);
        system.assertEquals('Approved', rrc.Approval_Status__c, 'Approval Status should be "Approved" when the reference request contact is approved.');
    }
    
    /**
     * 
     * @description: Reject the approval of a reference request contact record.  Verify the comments and approval status are reflected on the record
     * 
     **/
    static testMethod void testRejected() {
        //get the reference request contact that was created in the testSetup method
        Reference_Request_Contact__c rrc = [SELECT Id, Reference_Modules__c, Reference_Attributes__c FROM Reference_Request_Contact__c];
        
        //verify there is an approval pending
        Id pendingApprovalId = ApprovalOverrideController.getWorkItemId(rrc.Id);
        system.assertNotEquals(null, pendingApprovalId, 'The Reference Request Contact should have a pending approval');
        
        //set the page reference
        PageReference pageRef = Page.ApprovalOverride;
        test.setCurrentPage(pageRef);
        
        string APPROVAL_INSTRUCTIONS = 'Approving this request will update the Status to Approved and notify the Reference Lead.';
        string approvalComments = 'Rejected!';
        boolean isApproved = false;
        
        //Set currentpage parameters
        ApexPages.currentPage().getParameters().put('recordId', rrc.Id);
        ApexPages.currentPage().getParameters().put('objLabel', 'Reference Request Contact');
        ApexPages.currentPage().getParameters().put('fields', 'Submitted_By__r.Name,Reference_Request_Source__c,Reference_Institution__c,Reference_Contact__r.Name,Reference_Modules__c,Reference_Attributes__c');
        ApexPages.currentPage().getParameters().put('commentField', 'Approval_Reason__c');
        ApexPages.currentPage().getParameters().put('instructions', APPROVAL_INSTRUCTIONS);
        
        //instantiate the controller
        ApprovalOverrideController controller = new ApprovalOverrideController();
        system.assertEquals(6, controller.fieldValueMap.size());
        
        for (ApprovalOverrideController.fld field : controller.flds) {
            if (field.label == 'Reference Modules') system.assertEquals(rrc.Reference_Modules__c, field.value);
        }
        
        //reject the approval request
        ApprovalOverrideController.getApprovalResult(rrc.Id, isApproved, approvalComments, 'Approval_Reason__c');
        
        //get the reference request contact
        rrc = [SELECT Id, Approval_Reason__c, Approval_Status__c FROM Reference_Request_Contact__c WHERE Id = :rrc.Id];
        //verify the approval comments populated correctly
        system.assertEquals(approvalComments, rrc.Approval_Reason__c);
        system.assertEquals('Denied', rrc.Approval_Status__c, 'Approval Status should be "Denied" when the reference request contact is rejected.');
    }
    
}