objects/My_Relationships__c.object
<CustomObject>
    <description>A Contact may have Staff Relationships where s/he is the From and others where s/he is the To in the relationship. This is done through two lookups to Contact, which would natively result in two related lists (one for each lookup) on the Contact page layout. This makes navigation and understanding more complicated for the end-user.
To simplify this perspective, a new object will be created to represent all relationships for a given Contact, with indicators of the From and To in one related list. This object is read-only, and is manipulated entirely under program control.</description>
    <fields>
        <fullName>Relationship_Type__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; +  Staff_Relationship__r.Relationship__r.Id, Staff_Relationship__r.Relationship__r.Name, &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Relationship Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Relationship</label>
        <referenceTo>Staff_Relationship__c</referenceTo>
        <relationshipName>My_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>My Relationships</label>
    <nameField>
        <label>My Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Relationship_Type__c.object
<CustomObject>
    <description>This object holds the definitions of the different types of relationship that can be established between two Contacts.</description>
    <fields>
        <fullName>Name_When_From__c</fullName>
        <inlineHelpText>What do you call the relationship from the perspective of each party? For example, in a &quot;Management&quot; relationship, the From is &quot;Manager&quot; and the To is &quot;Staff&quot;.</inlineHelpText>
        <label>Name When From</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_When_To__c</fullName>
        <inlineHelpText>What do you call the relationship from the perspective of each party? For example, in a &quot;Management&quot; relationship, the From is &quot;Manager&quot; and the To is &quot;Staff&quot;.</inlineHelpText>
        <label>Name When To</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Staff_Relationship__c.object
<CustomObject>
    <description>One staff member may be related to one or many other staff members for a variety of reasons. In each case, the nature of that relationship is recorded here, and is typified by the two people in the relationship, the nature of the relationship, and the effective dates.</description>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Relationship_Type__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Staff Relationships</relationshipLabel>
        <relationshipName>Staff_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff Relationship</label>
    <nameField>
        <label>Staff Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Relationships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RelationshipTypeTriggerHelper.cls
/**
 *  Description     :   Helper class for Trigger_RelationshipType trigger.
 *
 *  Created By      :   Subhash Garhwal 
 *
 *  Created Date    :   9/29/2015
 *
 *  Revision Logs   :   V_1.0 - Created - CR-20150825-9182
 *                    
 **/
public without sharing class RelationshipTypeTriggerHelper {

	/**
     *  @description    :	This method is used to update the child staff relationship and My relationship records.
     *  
     *  @args           :   List<Relationship_Type__c>, Map<Id, Relationship_Type__c>
     *
     *  @return         :   void
     *
     **/
     public static void cascadeChanges(List<Relationship_Type__c> NewRelationshipTypes, Map<Id, Relationship_Type__c> mapOldRelationshipTypes){
     	
     	//Set To Hold relationship Type Id
     	Set<Id> setRTIds = new Set<Id>();
     	
     	//Loop Through RelationshipType
     	for(Relationship_Type__c rT : NewRelationshipTypes){
     		
     		//Check For apporiate condition and add Id in set
     		if(mapOldRelationshipTypes != null && (rT.Name != mapOldRelationshipTypes.get(rT.Id).Name || rT.Name_When_From__c != mapOldRelationshipTypes.get(rT.Id).Name_When_From__c
     			|| rT.Name_When_To__c != mapOldRelationshipTypes.get(rT.Id).Name_When_To__c))
     			setRTIds.add(rT.Id);
     	}
     	
     	//Check size
     	if(setRTIds.size() > 0){
	     	
	     	//Update Staff Relationship or My Relationship
	     	update [Select Id, Relationship__c From Staff_Relationship__c Where Relationship__c IN: setRTIds];
	     	update [Select Id, Staff_Relationship__r.Relationship__c From My_Relationships__c Where Staff_Relationship__r.Relationship__c IN : setRTIds];
     	}
     }
}