objects/NBB__c.object
<CustomObject>
    <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
    <fields>
        <fullName>ATL_Date__c</fullName>
        <defaultValue>Today ()</defaultValue>
        <label>ATL Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Binder_Date__c</fullName>
        <defaultValue>Today ()</defaultValue>
        <label>Binder Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Marketer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>NBB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NA_Date__c</fullName>
        <defaultValue>Today ()</defaultValue>
        <label>NA Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NBB_Type__c</fullName>
        <label>NBB Type</label>
        <picklist>
            <picklistValues>
                <fullName>Base Fee</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Future Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Year Recognizable NBB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incentive Kicker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optilink Guaranteed Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Posted Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shadow Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Un-Posted Risk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NBB__c</fullName>
        <label>NBB</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>NBB</relationshipLabel>
        <relationshipName>NBB1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Acronym__c</fullName>
        <formula>Program__r.Program_Acronym__c</formula>
        <label>Program Acronym</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>NBB</relationshipLabel>
        <relationshipName>NBB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SA_EA_Date__c</fullName>
        <defaultValue>Today ()</defaultValue>
        <label>SA/EA Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Role__c</fullName>
        <description>Sifter #133-We need to add an &quot;RCP&quot; tag to the Sales Segment in the NBB object (the same way we tag EA revenue) to be able to track RC principal revenue correctly.</description>
        <label>Sales Role</label>
        <picklist>
            <picklistValues>
                <fullName>Rev Cycle Principal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solutions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Shadow_Credit_Type__c</fullName>
        <label>Shadow Credit Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <defaultValue>1.00</defaultValue>
        <label>Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upsell__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Upsell</label>
        <type>Checkbox</type>
    </fields>
    <label>NBB</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NBB</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
    <fields>
        <fullName>Program_Acronym__c</fullName>
        <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
        <label>Program Acronym</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassNBBUpsertController.cls
/**
 *  Description     :   Controller class to have logic of VF page that will apply the logic to process the NBB records
 *
 *  Created By      :   
 *
 *  Created Date    :   12/12/2015
 *
 *  Current Version :   V_1.0
 *
 *  Revision Logs   :   V_1.0 - Created
 *
 **/
public with sharing class MassNBBUpsertController {
    
    //Useful variables 
    Opportunity opportunity;
    public List<NBB__c> nbbList {get; set;}
    
    //Constructor
    public MassNBBUpsertController(Apexpages.StandardController sc) { 
        
        //Memory Allocation
        nbbList = new List<NBB__c>();
        
        //Get URL parameter
        String opportunityId = ApexPages.currentPage().getParameters().get('oppoutunityId');
        
        List<Opportunity> opps = [Select Id, Name, Account.Name, Marketer__c, Program__c, Program_Acronym__c from Opportunity where Id =: opportunityId];
        
        if(opps.size() > 0)
            opportunity = opps[0];
        
        //Pull the existing NBB records if any
        nbbList = [Select Id, Name, Opportunity__c, Marketer__c, Program__c, Unit__c, NBB__c, NBB_Type__c, Comments__c, Sales_Role__c, Upsell__c, Shadow_Credit_Type__c, Binder_Date__c, NA_Date__c, ATL_Date__c, SA_EA_Date__c from NBB__c where Opportunity__c =: opportunity.Id];
        
        // Loop to add 10 new default rows for add NBB records in list
        for(Integer i=1 ; i<=10 ; i++){
    
            nbbList.add(new NBB__c(Name = 'NBB - ' + opportunity.Account.Name + ' - ' + opportunity.Program_Acronym__c + ' - ' + UserInfo.getLastName(), Opportunity__c = opportunity.Id, Program__c = opportunity.Program__c, Marketer__c = opportunity.Marketer__c));
        }
    }
    
    /**
     *  @description    :   Method to perform logic of addNewNBB Button on page.
     *
     *  @args           :   
     *
     *  @return         :   void
     *
     **/
    public void addNewNBB() {
        
        //Add a new NBB
        nbbList.add(new NBB__c(Name = 'NBB - ' + opportunity.Account.Name + ' - ' + opportunity.Program_Acronym__c + ' - ' + UserInfo.getLastName(), Opportunity__c = opportunity.Id, Program__c = opportunity.Program__c, Marketer__c = opportunity.Marketer__c, Unit__c = 1, Binder_Date__c = Date.today(), NA_Date__c = Date.today(), ATL_Date__c = Date.today(), SA_EA_Date__c = Date.today()));
    }
    
    /**
     *  @description    :   Usert the NBB records
     *
     *  @args           :   
     *
     *  @return         :   void
     *
     **/
    public Pagereference doSave() {
        
        //Savepoint
        Savepoint sp = database.setSavepoint();
        
        //Exception handling
        try {
            
            //Create a list if records to be upserted
            List<NBB__c> upsertNBBList = new List<NBB__c>();
            
            //Error row count
            Integer i = 1;
            
            //Loop through the nbbList
            for(NBB__c nbb : nbbList){
                System.debug('##########' +opportunity.Marketer__c + nbb.Marketer__c);
                System.debug('##########' +opportunity.Program__c + nbb.Program__c);
                //Check if any of the row is incomplete
                //After clicking on the Save button, check if any of the required field is missing in any row but any other data is populated, 
                //throw the error message on screen with the row# and error message. 
                //Skip the row where no data is populated. Once data is corrected and upsert(insert/update) the remaining NBB records. 
                //Stamp the same opportunity on NBB where it came from. 
                //User requiredMark css from Salesforce to display the required mark on page instead of required attribute. 
                //So it doesn?t fire validation from each row.
                if((String.isNotBlank(nbb.Name) 
                        && nbb.Unit__c != null 
                        && nbb.NBB__c != null 
                        && nbb.Binder_Date__c != null 
                        && nbb.NA_Date__c != null)){
                    
                    //Add in list to be upserted
                    upsertNBBList.add(nbb);
                }
                else if((nbb.NBB__c != null
                            || nbb.Marketer__c != opportunity.Marketer__c //Changed from default value
                            || nbb.Program__c != opportunity.Program__c //Changed from default value
                            || nbb.Unit__c != 1 //Changed from default value
                            || String.isNotBlank(nbb.NBB_Type__c) || String.isNotBlank(nbb.Comments__c) 
                            || String.isNotBlank(nbb.Sales_Role__c) || nbb.Upsell__c == true 
                            || String.isNotBlank(nbb.Shadow_Credit_Type__c)
                            || nbb.Binder_Date__c != Date.today() //Changed from default value
                            || nbb.NA_Date__c != Date.today() //Changed from default value
                            || nbb.ATL_Date__c != Date.today() //Changed from default value
                            || nbb.SA_EA_Date__c != Date.today()
                            || nbb.Id != null) //Changed from default value
                        && (String.isBlank(nbb.Name) || nbb.Unit__c == null || nbb.NBB__c == null 
                            || nbb.Binder_Date__c == null || nbb.NA_Date__c == null)
                        ){
                    //Error
                    ApexPages.Message msg = new Apexpages.Message(ApexPages.Severity.ERROR,'Require field(s) missing on Row# ' + i);
                    Apexpages.addMessage(msg);
                }
                i++;
            }
            
            //Check for the errors
            if(ApexPages.hasMessages(ApexPages.Severity.ERROR))
                return null;
            
            //check if there are records to process
            if(upsertNBBList.size() > 0)
                upsert upsertNBBList;
           
           return new PageReference('/' + opportunity.Id);
        
        } catch (Exception e) {
            
            //Rollback teh entire transaction in case of exception
            database.rollback(sp);  
            
            //Add error on page
            ApexPages.addMessages(e);
        }
       return null;
    }
    
     /**
     *  @description    :   Cancel
     *
     *  @args           :   
     *
     *  @return         :   void
     *
     **/
    public PageReference doCancel() {
        
        //Redirect to opporutnity page
        return new PageReference('/' + opportunity.Id);
    }
}