objects/Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <formula>Relationship_Interaction__r.Institution__r.Name</formula>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <formula>Relationship_Interaction__r.Primary_Contact__r.FirstName + &quot; &quot; + Relationship_Interaction__r.Primary_Contact__r.LastName</formula>
        <label>Primary Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>Relationship_Interaction__r.Status__c</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Outcome</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Outcome Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outcomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Outcome_WarmLead__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The Outcome_WarmLead custom setting will be used to define the values used when a Warm Lead is created as an Outcome.  These fields are used by a workflow rule, based on two prerequisites – the Source Interaction field is populated with a value, and the Outcome Type field is set to ‘Product Lead (OAB).</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Event__c</fullName>
        <label>Lead Event</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Origin__c</fullName>
        <label>Lead Origin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketer_Assignment__c</fullName>
        <label>Marketer Assignment</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Associate_Assignment__c</fullName>
        <label>Marketing Associate Assignment</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qualification_Status__c</fullName>
        <label>Qualification Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <label>RecordType</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <label>Source Object</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Outcome WarmLead</label>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Relationship_Interaction__c.object
<CustomObject>
    <description>A Relationship Interaction record will be used to capture the detail and link the results of a relationship-building meeting scheduled with an existing member and/or prospect.</description>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Interactions</relationshipLabel>
        <relationshipName>Relationship_Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <label>Interaction Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>Status_Flag__c + &quot; &quot; + Status_Text__c</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Relationship Interaction</label>
    <nameField>
        <label>Relationship Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warm_Lead__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CR-3485-This field is used in an integration with Eloqua. Please research with the appropriate stakeholders/liaisons before altering it&apos;s meaning, usage, field type or other field characteristics. Do not delete or change the current API name.</description>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Warm Leads</relationshipLabel>
        <relationshipName>Warm_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CR-3485-This field is used in an integration with Eloqua. Please research with the appropriate stakeholders/liaisons before altering it&apos;s meaning, usage, field type or other field characteristics. Do not delete or change the current API name.</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Warm Leads</relationshipLabel>
        <relationshipName>Warm_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <description>CR-3485-This field is used in an integration with Eloqua. Please research with the appropriate stakeholders/liaisons before altering it&apos;s meaning, usage, field type or other field characteristics. Do not delete or change the current API name.</description>
        <label>Grade</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Origin__c</fullName>
        <description>CR-1961</description>
        <label>Lead Origin</label>
        <picklist>
            <picklistValues>
                <fullName>Advisory.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eloqua-Daily Briefing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eloqua-Direct Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eloqua-Internal Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eloqua-MA Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eloqua-MKTG Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eloqua-MKTG Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eloqua-Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eloqua-Product Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eloqua-Pure Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email/Voicemail Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HSPI Summit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Offer (Event/Webinar)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OAB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Approach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy Retreat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turnover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Intelligence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Marketer_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CR-3485-This field is used in an integration with Eloqua. Please research with the appropriate stakeholders/liaisons before altering it&apos;s meaning, usage, field type or other field characteristics. Do not delete or change the current API name.</description>
        <label>Marketer Assignment</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Warm_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Associate_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CR-3485-This field is used in an integration with Eloqua. Please research with the appropriate stakeholders/liaisons before altering it&apos;s meaning, usage, field type or other field characteristics. Do not delete or change the current API name.</description>
        <label>Marketing Associate Assignment</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Warm_Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qualification_Status__c</fullName>
        <description>CR-3485-This field is used in an integration with Eloqua. Please research with the appropriate stakeholders/liaisons before altering it&apos;s meaning, usage, field type or other field characteristics. Do not delete or change the current API name.</description>
        <label>Qualification Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unqualified</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>CR-3485-This field is used in an integration with Eloqua. Please research with the appropriate stakeholders/liaisons before altering it&apos;s meaning, usage, field type or other field characteristics. Do not delete or change the current API name.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Already a Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Timing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined/No Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified - Bad Timing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified - Competitor in Place</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified - Contact Too Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified - No Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified - Non-Viable Org</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NP - Not Viable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Identified (Moved to Opportunity)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - Contact Under Protocol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - Restriction Clearance Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted - Permission Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retained by Strategic Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warming - Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warming - Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Marketer Assigned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Warm Lead</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warm Leads</pluralLabel>
    <recordTypes>
        <fullName>OAB</fullName>
        <active>true</active>
        <label>OAB</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_OutcomeExtension.cls
@isTest
public class Test_OutcomeExtension {
	
    /**
     * 
     * @description: create the outcome_warmlead__c custom setting
     * 
     **/
    public static void createOutcomeWarmLeadSetting() {
        //create warm lead custom setting
        Outcome_WarmLead__c leadSettings = new Outcome_WarmLead__c(Name = label.OutcomesProductLeadOAB,
                                                                  Lead_Origin__c = 'OAB',
                                                                  Qualification_Status__c = 'Unqualified',
                                                                  Grade__c = 'N/A',
                                                                  Marketing_Associate_Assignment__c = userinfo.getUserId(),
                                                                  Marketer_Assignment__c = userinfo.getUserId(),
                                                                  Status__c = 'Retained by Strategic Marketing',
                                                                  RecordType__c = Schema.SObjectType.Warm_Lead__c.getRecordTypeInfosByName().get('OAB').getRecordTypeId(),
                                                                  Lead_Event__c = 'Interaction_Type__c',
                                                                  Source_Object__c = 'Relationship Interaction',
                                                                  Account__c = 'Institution__c',
                                                                  Contact__c = 'Primary_Contact__c');
        insert leadSettings;
    }
    
    /**
     * 
     * @description: test setup that will be performed once and the data will be accessible to all test methods in this class
     * 
     **/
    @testSetup static void setup() {
        //create picklist custom settings
        Test_DynamicPicklist.createOutcomePicklist();
        //create outcome warm lead setting
        createOutcomeWarmLeadSetting();
    }
    
    /**
     * 
     * @description: Add outcome of the 'Other Outcome' record type.  Verify the user is redirected to the proper edit page.
     * 
     **/
    static testMethod void testRedirect_OtherOutcome() {
        //create relationship interaction
        Relationship_Interaction__c interaction = Test_RelationshipInteractionExtension.createRelationshipInteraction(null, null);
        
        //create a sample outcome
        Outcome__c outcome = new Outcome__c();
        
        // set the page reference and recordType = Other Outcome
        PageReference pageRef = Page.Outcome_Redirect;
        pageRef.getParameters().put('RecordType', OutcomeExtension.RECORD_TYPE_ID_OUTCOME_OTHER);
        test.setCurrentPage(pageRef);
        
        // instantiate the controller and set the page
        ApexPages.standardController standardController = new ApexPages.standardController(outcome);
        OutcomeExtension controller = new OutcomeExtension(standardController);
        
        //verify redirect
        system.assertEquals(true, controller.redirect().getURL().containsIgnoreCase('outcome_edit'));
    }
    
    /**
     * 
     * @description: Add outcome of the 'Relationship Interaction' record type.  Verify the user is redirected to the proper page.
     * 
     **/
    static testMethod void testRedirect_RelationshipInteraction() {
        //create relationship interaction
        Relationship_Interaction__c interaction = Test_RelationshipInteractionExtension.createRelationshipInteraction(null, null);
        
        //create a sample outcome
        Outcome__c outcome = new Outcome__c();
        
        // set the page reference and recordType = Other Outcome
        PageReference pageRef = Page.Outcome_Redirect;
        pageRef.getParameters().put('RecordType', OutcomeExtension.RECORD_TYPE_ID_OUTCOME_RELATIONSHIP_INTERACTION);
        test.setCurrentPage(pageRef);
        
        // instantiate the controller and set the page
        ApexPages.standardController standardController = new ApexPages.standardController(outcome);
        OutcomeExtension controller = new OutcomeExtension(standardController);
        
        //verify redirect
        system.assertEquals(true, controller.redirect().getURL().containsIgnoreCase('Interaction_Basic_Edit'));
    }
    
    /**
     * 
     * @description: 
     * 
     **/
    static testMethod void testRedirect_CreateOtherOutcome() {
        //create relationship interaction
        Relationship_Interaction__c interaction = Test_RelationshipInteractionExtension.createRelationshipInteraction(null, null);
        
        //create a sample outcome
        Outcome__c outcome = new Outcome__c();
        
        // set the page reference and recordType = Other Outcome
        PageReference pageRef = Page.Outcome_Edit;
        pageRef.getParameters().put('RecordType', OutcomeExtension.RECORD_TYPE_ID_OUTCOME_OTHER);
        pageRef.getParameters().put('previousInteraction', interaction.Id);
        test.setCurrentPage(pageRef);
        
        // instantiate the controller and set the page
        ApexPages.standardController standardController = new ApexPages.standardController(outcome);
        OutcomeExtension controller = new OutcomeExtension(standardController);
        
        //verify the outcome types dynamic picklist is populated with values
        system.assertEquals(true, controller.outcomeTypes.size() > 0, 'There should be at least one outcome type in the dynamic picklist.  Verify createOutcomePicklist() is being called in setup.');
        
        //populate required fields
        controller.outcome.Outcome_Type__c = 'Meeting Recruitment';
        controller.save();
        
        //get the outcome record that was generated
        list<Outcome__c> outcomes = [SELECT Id, Outcome_Type__c, Relationship_Interaction__c FROM Outcome__c WHERE Relationship_Interaction__c = :interaction.Id];
        system.assertEquals(1, outcomes.size());
    }
    
    /**
     * 
     * @description: 
     * 
     **/
    static testMethod void testPopulateWarmLeadDefaults() {
        //create a program
        Program__c program = TestUtilities.CreateNewProgram(true);
        
        //create relationship interaction
        Relationship_Interaction__c interaction = Test_RelationshipInteractionExtension.createRelationshipInteraction(null, null);
        
        //create a sample outcome
        Outcome__c outcome = new Outcome__c();
        
        // set the page reference and recordType = Product Lead (OAB)
        PageReference pageRef = Page.Outcome_Edit;
        pageRef.getParameters().put('RecordType', OutcomeExtension.RECORD_TYPE_ID_OUTCOME_PRODUCT_LEAD_OAB);
        pageRef.getParameters().put('previousInteraction', interaction.Id);
        test.setCurrentPage(pageRef);
        
        // instantiate the controller and set the page
        ApexPages.standardController standardController = new ApexPages.standardController(outcome);
        OutcomeExtension controller = new OutcomeExtension(standardController);
        
        //verify that one lead is populated by default
        system.assertEquals(interaction.Primary_Contact__c, controller.warmLeads[0].Contact__c, 'The first lead should be populated with the related interaction\'s primary contact.');
        system.assertEquals(2, controller.warmLeads.size(), 'Two leads should be present by default - one for primary contact from interaction and a blank record.');
        
        //set deafult values on the warm lead record
        controller.warmLeads[0].Contact_level__c = 'CXO';
        controller.warmLeads[0].Primary_Program__c = program.Id;
        
        //save
        controller.save();
        
        //verify no errors occurred
        system.assertEquals(new list<ApexPages.Message>(), apexPages.getMessages());
        
        //get the outcome record that was generated
        list<Outcome__c> outcomes = [SELECT Id, Outcome_Type__c, Relationship_Interaction__c FROM Outcome__c WHERE Relationship_Interaction__c = :interaction.Id];
        system.assertEquals(1, outcomes.size());
        
        //get the warm leads that were generated
        list<Warm_Lead__c> warmLeads = [SELECT Id, Grade__c, Lead_Date__c, Lead_Origin__c, Lead_Channel__c, Contact__c, Outcome_Type__c, Qualification_Status__c 
                                        FROM Warm_Lead__c WHERE Source_Interaction__c = :interaction.Id];
        Outcome_WarmLead__c defaults = Outcome_WarmLead__c.getInstance(label.OutcomesProductLeadOAB);
        system.assertEquals(1, warmLeads.size());
        system.assertEquals(defaults.Grade__c, warmLeads[0].Grade__c);
        system.assertEquals(defaults.Qualification_Status__c, warmLeads[0].Qualification_Status__c);
        system.assertEquals(defaults.Lead_Origin__c, warmLeads[0].Lead_Origin__c);
        system.assertEquals(interaction.Interaction_Type__c, warmLeads[0].Lead_Channel__c);
    }
    
    /**
     * 
     * @description: 
     * 
     **/
    static testMethod void testPopulateWarmLeadDefaults_Error() {
        //create a program
        Program__c program = TestUtilities.CreateNewProgram(true);
        
        //create relationship interaction
        Relationship_Interaction__c interaction = Test_RelationshipInteractionExtension.createRelationshipInteraction(null, null);
        
        //create a sample outcome
        Outcome__c outcome = new Outcome__c();
        
        // set the page reference and recordType = Product Lead (OAB)
        PageReference pageRef = Page.Outcome_Edit;
        pageRef.getParameters().put('RecordType', OutcomeExtension.RECORD_TYPE_ID_OUTCOME_PRODUCT_LEAD_OAB);
        pageRef.getParameters().put('previousInteraction', interaction.Id);
        test.setCurrentPage(pageRef);
        
        // instantiate the controller and set the page
        ApexPages.standardController standardController = new ApexPages.standardController(outcome);
        OutcomeExtension controller = new OutcomeExtension(standardController);
        
        //verify that one lead is populated by default
        system.assertEquals(interaction.Primary_Contact__c, controller.warmLeads[0].Contact__c, 'The first lead should be populated with the related interaction\'s primary contact.');
        system.assertEquals(2, controller.warmLeads.size(), 'Two leads should be present by default - one for primary contact from interaction and a blank record.');
        
        //set deafult values on the warm lead record
        controller.warmLeads[0].Contact_level__c = 'CXO';
        controller.warmLeads[0].Primary_Program__c = program.Id;
        
        //add a new lead
        controller.addLead();
        
        //save (should throw error)
        controller.save();
        
        //verify 1 error occurred
        system.assertEquals(1, apexPages.getMessages().size(), 'One error should have been returned because the lead details are not populated.');
        
        //remove the blank lead
        pageRef.getParameters().put('index', '2');
        system.assertEquals(2, controller.indexVal, 'index value should have been 2.');
        controller.removeLead();
        
        //save (should complete successfully)
        controller.save();
        //system.assertEquals(0, apexPages.getMessages().size());
        //get the warm leads that were generated
        list<Warm_Lead__c> warmLeads = [SELECT Id, Grade__c, Lead_Date__c, Lead_Origin__c, Lead_Channel__c, Contact__c, Outcome_Type__c, Qualification_Status__c 
                                        FROM Warm_Lead__c WHERE Source_Interaction__c = :interaction.Id];
        Outcome_WarmLead__c defaults = Outcome_WarmLead__c.getInstance(label.OutcomesProductLeadOAB);
    }
    
    
}