objects/Perspective__c.object
<CustomObject>
    <description>This object holds the Perspective definitions.
Within the context of a Program Collection, given consumers may interpret the contents of that Program Collection differently: what one consumer takes as a collection of five Programs, for example, another may interpret as having only three Programs. Since both consumers will use the same terminology to describe the collection, the Perspective allows for a differentiation of the definition of that Program Collection by the intended use or consumer.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Drives availability for selection in Program Relationship only</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Perspective</label>
    <nameField>
        <label>Perspective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Perspectives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Program_Group__c.object
<CustomObject>
    <description>This object holds the Program Collection definitions.Program Collections are organizing records for broadly recognized collections of Programs. This is an augmentation to the extant concepts of a “Program hierarchy” based on the attributes (Market, Business Line, Vertical, Reporting Group) of specific Programs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Drives availability for selection in Program Relationship only</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_End__c</fullName>
        <label>Effective End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start__c</fullName>
        <label>Effective Start</label>
        <type>Date</type>
    </fields>
    <label>Program Collection</label>
    <nameField>
        <label>Program Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Collections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Program_Perspective__c.object
<CustomObject>
    <description>This object holds the unique association of a Program Collection and a Perspective. 
When establishing a relationship between a Program or Program Collection and any other Program Collection, that relationship must be typified by a Perspective. Rather than require users to identify both the Perspective and Program Collectionwith each association, the association is instead drawn between the child record (Program or Program Collection) and the Collection Perspective, which encapsulates the unique collection for a particular consumption purpose.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Drives availability for selection in Program Relationship only</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_End__c</fullName>
        <label>Effective End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Effective Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Perspective__c</fullName>
        <label>Perspective</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Perspective__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Perspective__c</referenceTo>
        <relationshipLabel>Collection Perspectives</relationshipLabel>
        <relationshipName>Program_Perspectives</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Group__c</fullName>
        <label>Program Collection</label>
        <referenceTo>Program_Group__c</referenceTo>
        <relationshipLabel>Collection Perspectives</relationshipLabel>
        <relationshipName>Program_Perspectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Collection Perspective</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Perspectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Role_Program_Perspective__c.object
<CustomObject>
    <description>Each Staff Assignment may relate to zero or many Program Perspectives. Each of these records has its own effective dating, and these records are aggregated into a viewable list on its parent Staff Assignment for presentation on related lists and simple reports.</description>
    <fields>
        <fullName>Effective_End__c</fullName>
        <label>Effective End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start__c</fullName>
        <label>Effective Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Perspective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Perspective</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program_Perspective__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Perspective__c</referenceTo>
        <relationshipLabel>Role Program Perspectives</relationshipLabel>
        <relationshipName>Role_Program_Perspectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_Assignment__c</fullName>
        <label>Staff Assignment</label>
        <referenceTo>Team_Membership__c</referenceTo>
        <relationshipLabel>Role Program Perspectives</relationshipLabel>
        <relationshipName>Role_Program_Perspectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Role Program Perspective</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Role Program Perspectives</pluralLabel>
    <recordTypes>
        <fullName>Assigned</fullName>
        <active>true</active>
        <label>Assigned</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Membership__c.object
<CustomObject>
    <description>This object holds the relationship between the Staff member, Institution, and Assignment Role, as well as defining the effective dates associated with the SA.</description>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_date__c</fullName>
        <label>Role End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Staff Assignments</relationshipLabel>
        <relationshipName>Team_Memberships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Role</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5) OR ((6 OR 10) AND 7) OR (8 AND 9))</booleanFilter>
            <filterItems>
                <field>Team_Role__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Opportunity</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Opportunity__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Membership</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Membership__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Assigned</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Institution__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Project__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Default</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team_Role__c</referenceTo>
        <relationshipLabel>Staff Assignments</relationshipLabel>
        <relationshipName>Team_Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Staff Assignments</relationshipLabel>
        <relationshipName>Staff_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Role Start</label>
        <type>Date</type>
    </fields>
    <label>Staff Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Assignments</pluralLabel>
    <recordTypes>
        <fullName>Assigned</fullName>
        <active>true</active>
        <description>Automatically assigned upon save</description>
        <label>Assigned</label>
    </recordTypes>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <description>Relates to a Membership for a given Institution</description>
        <label>Membership</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Role__c.object
<CustomObject>
    <description>This object holds the Role definitions. Each Role is associated with a business owner largely considered responsible for assigning and analyzing the use of that Role in SAs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for CR-20150908-9224.</description>
        <label>Institution</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_EditClarification.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */

@isTest(seeAllData=false)
private class Test_EditClarification {
/**
 *  Purpose         :   Test class for EditClarificationController.
 * 
 *  Created By      :   Padmesh Soni
 * 
 *  Created Date    :   07/06/2015 
 *
 *  Revision Logs   :   V_1.0 - Created
 * 
**/
    //Test method of test class name myUnitTest that check some assert statement to gain coverage of test class.
    static testMethod void myUnitTest() {
        
        //Bypassing all triggers
        Util.byPassAllTriggers = true;
        Util.IsTest(true);
        
        //Account List
        List<Account> account = new List<Account>();
        
        //Add values in list of account
        account.add(new Account(Name = 'Test1'));
        account.add(new Account(Name = 'Test2'));
        account.add(new Account(Name = 'Test3'));
        
        //Insert list of accounts
        insert account;
        
        //Create contact
        List<Contact> contacts = new List<Contact>();
        
        //Add contacts in List
        contacts.add(new Contact(FirstName = 'Test1', LastName = 'Contact1', Email = 'test@test.com', 
                                Employee_User_Record__c = UserInfo.getUserId(), AccountId = account[0].Id, Active_PSS__c = true));
        contacts.add(new Contact(FirstName = 'Test2', LastName = 'Contact2', Email = 'test1@test.com', 
                                Employee_User_Record__c = UserInfo.getUserId(), AccountId = account[0].Id, Active_PSS__c = true));
    
        //Insert contact list
        insert contacts;
          
        //Create team roles
        List<Team_Role__c> staffRoles = new List<Team_Role__c>();
        
        //Add values in list
        staffRoles.add(new Team_Role__c(Name = 'Testing1',Active__c = true, Institution__c = true));
        staffRoles.add(new Team_Role__c(Name = 'Testing2',Active__c = true, Institution__c = true));
        
        //Insert
        insert staffRoles;
        
        //Object initilization of Team membership in list
        List<Team_Membership__c> staffAssignments = new List<Team_Membership__c>();
        
        //Record Types
        List<RecordType> recordTypes = [SELECT ID FROM RecordType WHERE sObjectType = 'Team_Membership__c' AND IsActive = true 
                       						AND DeveloperName = 'Assigned'];
        System.assert(recordTypes != null);
        
        //Add values in list of Team membership
        staffAssignments.add(new Team_Membership__c(Name = 'Test As 1', Start_date__c = System.today().addDays(-3), 
                                                    End_date__c = System.today().addDays(+5), 
                                                    Institution__c =  account[0].Id, Employee__c = UserInfo.getUserId(), 
                                                    Role__c = staffRoles[0].Id, Staff_member__c = contacts[0].Id, 
                                                    RecordTypeId = recordTypes[0].Id));
        staffAssignments.add(new Team_Membership__c(Name = 'Test As 2', Start_date__c = System.today().addDays(4), 
                                                    End_date__c = System.today().addDays(5), 
                                                    Institution__c =  account[1].Id, Employee__c = UserInfo.getUserId(), 
                                                    Role__c = staffRoles[1].Id, 
                                                    Staff_member__c = contacts[0].Id, RecordTypeId = recordTypes[0].Id));
        staffAssignments.add(new Team_Membership__c(Name = 'Test As 3', Start_date__c = System.today().addDays(-5), 
                                                    End_date__c = System.today().addDays(+5), 
                                                    Institution__c =  account[2].Id, Employee__c = UserInfo.getUserId(), 
                                                    Role__c = staffRoles[1].Id, RecordTypeId = recordTypes[0].Id,
                                                    Staff_member__c = contacts[1].Id));
        
        //Insert
        insert staffAssignments;
        
        //Create Perspective 
        List<Perspective__c> perspectives = new List<Perspective__c>();
        
        //Add new recrods in list
        perspectives.add(new Perspective__c(Name = 'perspective 1'));
        perspectives.add(new Perspective__c(Name = 'perspective '));
        
        //Insert
        insert perspectives;
        
        //Create Program Groups
        List<Program_Group__c> programCollections = new List<Program_Group__c>();
        
        //Add new recrods in list
        programCollections.add(new Program_Group__c(Name = 'PC 1'));
        programCollections.add(new Program_Group__c(Name = 'PC 2'));
        
        //Insert
        insert programCollections;
        
        //Create program Perspective
        List<Program_Perspective__c> programPerspectives = new List<Program_Perspective__c>();
        
        //Add new recrods in list
        programPerspectives.add(new Program_Perspective__c(Name = 'pp1' , Active__c = true,Perspective__c = perspectives[0].Id, Program_Group__c = programCollections[0].Id));
        programPerspectives.add(new Program_Perspective__c(Name = 'pp2' , Active__c = true,Perspective__c = perspectives[1].Id, Program_Group__c = programCollections[0].Id));
        
        //Insert Program Pespective
        insert programPerspectives;
        
        //Create Role Program Perspective
        List<Role_Program_Perspective__c> roleProgramPerspectives = new List<Role_Program_Perspective__c>(); 
        
        //Add new records in list
        roleProgramPerspectives.add(new Role_Program_Perspective__c(Name = 'Test Rpp 1',Staff_Assignment__c = staffAssignments[0].Id, Program_Perspective__c = programPerspectives[0].Id, 
                                    Effective_Start__c = System.today(), Effective_End__c = System.today().addDays(3)));
        roleProgramPerspectives.add(new Role_Program_Perspective__c(Name = 'Test Rpp 2',Staff_Assignment__c = staffAssignments[0].Id, Program_Perspective__c = programPerspectives[1].Id, 
                                    Effective_Start__c = System.today().addDays(-2),Effective_End__c = System.today().addDays(3)));
        
        //Insert
        insert roleProgramPerspectives;
        
        // Apex page standard controller object initializaation
        ApexPages.StandardController sc = new ApexPages.standardController(staffAssignments[0]);
    
        //Test start from here
        Test.startTest();
        
        //Enabling trigger again
        Util.BypassAllTriggers = false;
        
        //Instance of controller name EditClarificationController
        EditClarificationController controller = new EditClarificationController(sc);
        
        //Set value of option that is equal to new
        controller.sldOption = 'New';
        
        //Call Controller method
        controller.redirectUser();
        
        //Assert for result
        System.assertEquals(false, controller.isEdit);
        
        //Call controller method
        PageReference redirectPage = controller.doNew();
        
        //Assert for result
        System.assert(redirectPage.getUrl().contains('/apex/RedirectWithVariables?redirect=Object--Team_Membership__c'));
        
        //Set value of option that is equal to Edit
        controller.sldOption = 'Cancel';
        
        //Call controller method
        controller.redirectUser();
        
        //Call controller method
        controller.doNew();
        
        //Set value of option that is equal to Edit
        controller.sldOption = 'Edit';
        
        //Call controller method
        controller.redirectUser();
        
        //Assert for result
        System.assertEquals(true, controller.isEdit);
        
        //Call controller method
        controller.doNew();
        
        //Assert for result
        System.assertEquals(true, controller.isEdit);
        
        //Get option value in list
        List<SelectOption> selectOption = controller.options;
        
        //Update Staff Assignment
        staffAssignments[0].Start_date__c = System.today();
        staffAssignments[0].End_date__c = System.today().addDays(4);
        
        system.debug('redirectPage @@@@@' + redirectPage);
        
        //Call Controller method
        controller.doSave();
        
        //Query through Staff Assignment
        List<Team_Membership__c> teamMemberships = [Select Id, Start_date__c, End_date__c From Team_Membership__c Where Id =: staffAssignments[0].Id];
        
        
        System.assertEquals(1, teamMemberships.size());
        
        //Assert for result
        System.assertEquals(System.today(), teamMemberships[0].Start_date__c);
        System.assertEquals(System.today().addDays(4), teamMemberships[0].End_date__c);
        
        //Pass Parameters in URL
        Apexpages.currentPage().getParameters().put('sourceId', staffAssignments[0].Id +'-' + 'false');
        Apexpages.currentPage().getParameters().put('newId', staffAssignments[1].Id);
        
        //Instance of controller for UpdateSourceStaffAssignmentController
        UpdateSourceStaffAssignmentController controllerUpdate = new UpdateSourceStaffAssignmentController();
        
        //Redirect method of UpdateSourceStaffAssignmentController called
        controllerUpdate.redirect();
        
        //Query through Staff Assignment
        teamMemberships = [Select Id, Start_date__c, End_date__c From Team_Membership__c Where Id =: staffAssignments[0].Id];
        
        //Assert for result
        System.assertEquals(System.today().addDays(3), teamMemberships[0].End_date__c);
        
        //
        //Pass Parameters in URL
        Apexpages.currentPage().getParameters().put('sourceId', staffAssignments[0].Id +'-' + 'true');
        Apexpages.currentPage().getParameters().put('newId', staffAssignments[1].Id);
        
        //Instance of controller for UpdateSourceStaffAssignmentController
        UpdateSourceStaffAssignmentController controllerUpdate1 = new UpdateSourceStaffAssignmentController();
        
        //Redirect method of UpdateSourceStaffAssignmentController called
        controllerUpdate1.redirect();
        
        //Query through Role Program Perspetive
        List<Role_Program_Perspective__c> rPPList = [select Id,Effective_Start__c, Effective_End__c From Role_Program_Perspective__c Where Staff_Assignment__c =: staffAssignments[1].Id];
        
        //Assert for result
        System.assertEquals(2, rPPList.size());

  
        //Test end here
        Test.stopTest();
    }
}