objects/Perspective__c.object
<CustomObject>
    <description>This object holds the Perspective definitions.
Within the context of a Program Collection, given consumers may interpret the contents of that Program Collection differently: what one consumer takes as a collection of five Programs, for example, another may interpret as having only three Programs. Since both consumers will use the same terminology to describe the collection, the Perspective allows for a differentiation of the definition of that Program Collection by the intended use or consumer.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Drives availability for selection in Program Relationship only</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Perspectives</relationshipLabel>
        <relationshipName>Group_Purposes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Perspective</label>
    <nameField>
        <label>Perspective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Perspectives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Program__c.object
<CustomObject>
    <description>CONTROLLED SOX FIELD. CHANGES TO FIELDS REQUIRE PRIOR APPROVAL FROM FINANCE OPS.</description>
    <fields>
        <fullName>Effective_End__c</fullName>
        <label>Effective End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start__c</fullName>
        <label>Effective Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program_Group__c.object
<CustomObject>
    <description>This object holds the Program Collection definitions.Program Collections are organizing records for broadly recognized collections of Programs. This is an augmentation to the extant concepts of a “Program hierarchy” based on the attributes (Market, Business Line, Vertical, Reporting Group) of specific Programs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Drives availability for selection in Program Relationship only</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Collections</relationshipLabel>
        <relationshipName>Program_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_End__c</fullName>
        <label>Effective End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start__c</fullName>
        <label>Effective Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program Collection</label>
    <nameField>
        <label>Program Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Collections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Program_Perspective__c.object
<CustomObject>
    <description>This object holds the unique association of a Program Collection and a Perspective. 
When establishing a relationship between a Program or Program Collection and any other Program Collection, that relationship must be typified by a Perspective. Rather than require users to identify both the Perspective and Program Collectionwith each association, the association is instead drawn between the child record (Program or Program Collection) and the Collection Perspective, which encapsulates the unique collection for a particular consumption purpose.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Drives availability for selection in Program Relationship only</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Collection Perspectives</relationshipLabel>
        <relationshipName>Program_Perspectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_End__c</fullName>
        <label>Effective End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Effective Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_use_Plans_Direct__c</fullName>
        <label>In use – Plans - Direct</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_use_Plans_Indirect__c</fullName>
        <label>In use – Plans – Indirect</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Perspective__c</fullName>
        <label>Perspective</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Perspective__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Perspective__c</referenceTo>
        <relationshipLabel>Collection Perspectives</relationshipLabel>
        <relationshipName>Program_Perspectives</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Group__c</fullName>
        <label>Program Collection</label>
        <referenceTo>Program_Group__c</referenceTo>
        <relationshipLabel>Collection Perspectives</relationshipLabel>
        <relationshipName>Program_Perspectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Collection Perspective</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Perspectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program_Relationship__c.object
<CustomObject>
    <description>This object holds the Collection Perspective Child definitions.
Any given Program or Program Collection can be related to a Program Collection to express a relationship. That relationship is further defined by its effective dates.</description>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Collection Perspective Children</relationshipLabel>
        <relationshipName>Program_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_End__c</fullName>
        <label>Effective End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start__c</fullName>
        <label>Effective Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Perspective__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; +  Program_Perspective__r.Perspective__c, Program_Perspective__r.Perspective__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Perspective</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must supply a Program OR a Program Group</inlineHelpText>
        <label>Program Collection</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Program Collection you have selected is inactive.</errorMessage>
            <filterItems>
                <field>Program_Group__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Group__c</referenceTo>
        <relationshipLabel>Collection Perspective Children</relationshipLabel>
        <relationshipName>Program_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Perspective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection Perspective</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Collection Perspective you have selected is inactive.</errorMessage>
            <filterItems>
                <field>Program_Perspective__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program_Perspective__c</referenceTo>
        <relationshipLabel>Collection Perspective Children</relationshipLabel>
        <relationshipName>Program_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>You must supply a Program OR a Program Group</inlineHelpText>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Collection Perspective Parent</relationshipLabel>
        <relationshipName>Program_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collection Perspective Child</label>
    <nameField>
        <label>Collection Perspective Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collection Perspective Children</pluralLabel>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <label>Program</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_OverrideCPCNewButtonController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAlldata = false)
private class Test_OverrideCPCNewButtonController {
/**
 *  Purpose         :   Test class for OverrideCPCNewButtonController .
 * 
 *  Created By      :   Subhash Garhwal
 * 
 *  Created Date    :   07/24/2015 
 *
 *  Revision Logs   :   V_1.0 - Created CR-20150618-9013
 *
 *  Coverage        :   100% 
 * 
**/
    
    //Test method of test class name testRedirect that check some assert statement to gain coverage of test class.
    static testMethod void testRedirect() {
    
        //Create an institution
        Account account = TestUtilities.CreateNewAccount(false);
        
        //Insert
        insert account;
        
        //Create a Contact
        Contact contact = new Contact(FirstName = 'Test', LastName = 'Contact', Email = 'test@test.com', AccountId = account.Id, Employee_User_Record__c = Userinfo.getUserId());
        
        //Insert
        insert contact;
        
        //Program instance
        Program__c programs = new Program__c(Name = 'TestProgram1', Status__c = 'Active');
        
        //Insert
        insert programs;
          
        //Program Groups instance
        Program_Group__c programGroups = new Program_Group__c(Name = 'TestPG1', Effective_Start__c = System.today().addDays(-3), Effective_End__c = System.today(),
                                                              Business_Owner__c = contact.Id, Short_Name__c = 'test1211', Active__c = true);
        
        //Insert
        insert programGroups;
        
        //Perspective instance
        Perspective__c perspectives = new Perspective__c(Name = 'TestPerspective1', Business_Owner__c = contact.Id, Short_Name__c = '1232Test230', Active__c = true);
        
        //Insert
        insert perspectives;
        
        //Program Perspective instance
        Program_Perspective__c programPerspectives = new Program_Perspective__c(Name = 'TestPP1', Program_Group__c = programGroups.Id, Perspective__c = perspectives.Id,
                                                                                Business_Owner__c = contact.Id, Effective_Start__c = System.today(), Effective_End__c = System.today().addDays(4), 
                                                                                Active__c = true, In_use_Plans_Direct__c = 2, In_use_Plans_Indirect__c = 2);
     
        //Insert
        insert programPerspectives;
        
        //Query to fetch record type ID
        List<RecordType> recordID = [SELECT Id FROM RecordType WHERE sObjectType = 'Program_Relationship__c'];
        
        //Program Relationship Instance
        Program_Relationship__c programRelationships = new Program_Relationship__c(Name = 'TestPR', Program_Perspective__c = programPerspectives.Id, 
                                                                                   RecordTypeId = recordID[0].id);
        
        //Test start here 
        Test.startTest();
        
        //Standard controller instance passing collection perspective child  
        ApexPages.StandardController sc = new ApexPages.standardController(programRelationships); 
        
        //Controller instance 
        OverrideCPCNewButtonController controller= new OverrideCPCNewButtonController(sc);
        
        //Method calling
        Pagereference pageRef = controller.redirect();
        
        //Assert for result
        System.assert(pageRef.getUrl().contains('Program_Perspective__c'));
      
        //Program Relationship Instance
        programRelationships = new Program_Relationship__c(Name = 'TestPR1', Program_Perspective__c = null ,Business_Owner__c = contact.Id, RecordTypeId = recordID[0].ID);
       
        //Standard controller instance passing collection perspective child  
        sc = new ApexPages.standardController(programRelationships); 
        
        //Controller instance 
        controller = new OverrideCPCNewButtonController(sc);
        
        //Method calling
        pageRef = controller.redirect();
        
        //Assert for result
        System.assert(pageRef.getUrl().contains('Business_Owner__c'));
       
        //Program Relationship Instance
        programRelationships = new Program_Relationship__c(Name = 'TestPR2', Effective_Start__c = System.today() , Program_Perspective__c = programPerspectives.Id,
                                                           RecordTypeId = recordID[0].ID);
       
        //Standard controller instance passing collection perspective child  
        sc = new ApexPages.standardController(programRelationships); 
        
        //Controller instance 
        controller= new OverrideCPCNewButtonController(sc);
        
        //Method calling
        pageRef = controller.redirect();
        
        //Assert for result
        System.assert(pageRef.getUrl().contains('Effective_Start__c'));
      
        //Program Relationship Instance
        programRelationships = new Program_Relationship__c(Name = 'TestPR3', Program_Group__c = programGroups.Id, RecordTypeId = recordID[0].ID);
       
        //Standard controller instance passing collection perspective child  
        sc = new ApexPages.standardController(programRelationships); 
        
        //Controller instance 
        controller= new OverrideCPCNewButtonController(sc);
        
        //Method calling
        pageRef = controller.redirect();
        
        //Assert for result
        System.assert(pageRef.getUrl().contains('Program_Group__c'));
      
        //Program Relationship Instance
        programRelationships = new Program_Relationship__c(Name = 'TestPR4', Program__c = programs.Id, RecordTypeId = recordID[0].ID);
        
        //Standard controller instance passing collection perspective child  
        sc = new ApexPages.standardController(programRelationships); 
        
        //Controller instance 
        controller= new OverrideCPCNewButtonController(sc);
        
        //Method calling
        pageRef = controller.redirect();
        
        //Assert for result
        System.assert(pageRef.getUrl().contains('Program__c'));
        
        //Program Relationship Instance
        programRelationships = new Program_Relationship__c(Name = 'TestPR2', Business_Owner__c = contact.Id, RecordTypeId = recordID[0].ID);
        
        //Standard controller instance passing collection perspective child  
        sc = new ApexPages.standardController(programRelationships); 
        
        //Controller instance 
        controller= new OverrideCPCNewButtonController(sc);
        
        //Method calling
        pageRef = controller.redirect();
        
        //Assert for result
        System.assert(pageRef.getUrl().contains('Business_Owner__c'));
      
        //Program Relationship Instance
        programRelationships = new Program_Relationship__c();
        
        //Standard controller instance passing collection perspective child  
        sc = new ApexPages.standardController(programRelationships); 
        
        //Controller instance 
        controller= new OverrideCPCNewButtonController(sc);
        
        //Method calling
        pageRef = controller.redirect();
        
        //Assert for result
        System.assert(pageRef == null);
      
        //Test end here
        Test.stopTest();
    }
}