objects/Personal_Goal__c.object
<CustomObject>
    <description>Personal Goals represent the individual targets that each Payee must achieve. Some targets are simply a reframing of another target. For example, the “Career Committee Grade” Personal Goal may simply represent a first half/second half interpretation of the normal “Incentive” Personal Goal (which is itself quarterly).</description>
    <fields>
        <fullName>Personal_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Personal Plan</label>
        <referenceTo>Personal_Plan__c</referenceTo>
        <relationshipLabel>Personal Goals</relationshipLabel>
        <relationshipName>Personal_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Snapshot</label>
        <referenceTo>Personal_Goal__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Personal_Goals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Personal Goal</label>
    <nameField>
        <label>Personal Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Personal_Goal_Measurement_Period__c.object
<CustomObject>
    <fields>
        <fullName>Measurement_Date__c</fullName>
        <label>Measurement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Personal_Goal__c</fullName>
        <label>Personal Goal</label>
        <referenceTo>Personal_Goal__c</referenceTo>
        <relationshipLabel>Personal Goal Measurement Periods</relationshipLabel>
        <relationshipName>Personal_Goal_Measurement_Periods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Goal Measurement Period</label>
    <nameField>
        <label>Personal Goal Measurement Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Goal Measurement Periods</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Personal_Plan__c.object
<CustomObject>
    <description>This is the organizing/summarizing object that incorporates Personal Goals. The determination as to when a given Payee may have overlapping or simultaneously active Personal Plans ultimately is a decision made by a member of the Incentives Team. As a result, there are no controls in place to identify or prevent duplicate Personal Plans. 
If an Personal Plan represents the next iteration of a prior Personal Plan, the latest revision will identify the Personal Plan whose place is being taken.</description>
    <label>Personal Plan</label>
    <nameField>
        <label>Personal Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Plans</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/GoalsToPlanAssignmentWrapper.cls
/**
 *  Purpose            :   This class is used to draw Goals table on "Assign New Goals to Plans" page's tab 2 (Confirm Plan Assignment).
 *
 *  Created By         :   Subhash Garhwal
 *
 *  Created Date       :   11/17/2015
 *
 *  Current Version    :   V_1.0
 *
 *  Revision Log       :   V_1.0 - Created - CR-20150729-9114 - Goal Management System
 *
 **/
public with sharing class GoalsToPlanAssignmentWrapper implements Comparable {
    
    //Properties
    public String payeeId {get;set;}
    public String payeeName {get;set;}
    public String selectedPP {get;set;}
    public List<SelectOption> personalPlans {get;set;}
    public Personal_Plan__c personalPlan {get;set;}
    public Decimal currentWeight {get;set;}
    public Decimal newWeight {get;set;}
    public List<PersonalGoalWrapper> personalGoals {get;set;}
    
    //Behviour Picklist, populates when if user select any value in Plan Picklist(List<SelectOption> personalPlans) on the page, Default it will be blank
    public List<SelectOption> behaviourOptions{get;set;}
    public String selectedBehaviourOption{get;set;}
    
    //Constructor
    public GoalsToPlanAssignmentWrapper(String payeeId, String payeeName, Decimal newWeight, List<SelectOption> personalPlans, List<PersonalGoalWrapper> personalGoals,
                                        Personal_Plan__c personalPlan) {
        
        //Set values
        this.payeeId = payeeId;
        this.payeeName = payeeName;
        this.newWeight = newWeight;
        this.personalPlans = personalPlans;
        this.personalGoals = personalGoals;
        this.personalPlan = personalPlan;
        
        //Set Defaults
        personalPlan = new Personal_Plan__c();
        selectedPP = '';
        currentWeight = null;
        behaviourOptions = new List<SelectOption>();
        selectedBehaviourOption = '';
    }
    
    // Implement the compareTo() method
    public Integer compareTo(Object compareTo) {
    
        
        GoalsToPlanAssignmentWrapper compareToEmp = (GoalsToPlanAssignmentWrapper)compareTo;
        
        if (payeeName == compareToEmp.payeeName) return 0;
        if (payeeName > compareToEmp.payeeName) return 1;
        return -1;        
    }
    
    //Wrapper class to hold the Personal Plan Properties
    public class PersonalGoalWrapper {
        
        //Properties
        public Personal_Goal__c personalGoal {get;set;}
        public String rateTemplate {get;set;}
        public String payeeName {get;set;}
        public List<PGMeasurementPeriod> pGMPeriods {get;set;}
        
        /** Decide color of the personal goal based on its Related Goal (Primary_Goal__c) properties
			1 - Green	:	If related goal's persoanl plan lookup is blank
			2 - Yellow	:	If related goal's Status is 'Pending'
			3 - Red		:	If related goal's Status is 'Payee Approved'
		**/
		public String pgColor{get;set;}
		
		//Map to hold the Proposed Goal's PGMP Id with the Parent Snapshot's PGMP Id if dates are same
        public Map<Id, Id> mapPGPGMPWithSSPGMP;
		
        //Constructor
        public PersonalGoalWrapper(Personal_Goal__c personalGoal,String payeeName, List<PGMeasurementPeriod> pGMPeriods, Map<Id, Id> mapPGPGMPWithSSPGMP, String pgColor) {
            
            //Set Values
            this.personalGoal = personalGoal;
            this.payeeName = payeeName;
            this.pGMPeriods = pGMPeriods;
            this.mapPGPGMPWithSSPGMP = mapPGPGMPWithSSPGMP;
            this.pgColor = pgColor;
        }
    }
    
    //Wrapper to hold the Personal Goal Measurement Period dates
    public class PGMeasurementPeriod implements Comparable {
    	
    	//Properties
		public Personal_Goal_Measurement_Period__c pGMP {get;set;}
		public Boolean selected {set;get;}
		
		//Constructor
		public PGMeasurementPeriod(Personal_Goal_Measurement_Period__c pGMP) {
			
			//Set values
			this.pGMP = pGMP;
			
			//Set defaults
			selected = false;
		}
		
		// Implement the compareTo() method
	    public Integer compareTo(Object compareTo) {
	    
	        PGMeasurementPeriod compareToEmp = (PGMeasurementPeriod)compareTo;
	        
	        if (pGMP.Measurement_Date__c == compareToEmp.pGMP.Measurement_Date__c) return 0;
	        if (pGMP.Measurement_Date__c > compareToEmp.pGMP.Measurement_Date__c) return 1;
	        return -1;        
	    }
    }
}