objects/Picklist__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The Picklist custom setting will contain the list of available dynamic picklists.  The Alpha Sort attribute is TRUE if the items are sorted alphabetically.  When FALSE, the sort order must be specified in the PicklistEntry custom setting.</description>
    <fields>
        <fullName>Alpha_Sort__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Are the picklist values sorted alphabetically?</inlineHelpText>
        <label>Alpha Sort</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <inlineHelpText>Picklist display name</inlineHelpText>
        <label>Label</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Picklist</label>
</CustomObject>

objects/PicklistEntry__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the actual picklist values that will be available for selection.  The Sort Order field is used to set the order when the Alpha Sort option on the Picklist is FALSE.  The Active field can be used to hide a picklist value and keep it in the list if needed for historical reasons.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Set as FALSE to hide the item everywhere this is used</inlineHelpText>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <inlineHelpText>Picklist item display value</inlineHelpText>
        <label>Label</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist__c</fullName>
        <inlineHelpText>Picklist to which this selection item belongs</inlineHelpText>
        <label>Picklist</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <inlineHelpText>Items are sorted in ascending order with 1 as the top item.  Used when Alpha Sort is False</inlineHelpText>
        <label>Sort Order</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PicklistEntry</label>
</CustomObject>

objects/PicklistUsage__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lists the objects and fields where a Picklist is used.  This allows for the flexibility of assigning the actual Picklist in the custom setting instead of in the code.  The code only needs to know that a Dynamic Picklist is used, and can look up the specific list from the custom setting object.</description>
    <fields>
        <fullName>Field__c</fullName>
        <inlineHelpText>API Name of the field on the referenced object where the picklist is used</inlineHelpText>
        <label>Field</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <inlineHelpText>API Name of the object where the picklist is used</inlineHelpText>
        <label>Object</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist__c</fullName>
        <inlineHelpText>Name of referenced picklist custom setting</inlineHelpText>
        <label>Picklist</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>PicklistUsage</label>
</CustomObject>

classes/DynamicPicklist.cls
public class DynamicPicklist {
    
    //object and field api name
    public string objAPIName { get; set; }
    public string fldAPIName { get; set; }
    private list<PicklistWrapper> pWrappers { get; set; }
    
    public DynamicPicklist(string objAPIName, string fldAPIName) {
        this.objAPIName = objAPIName;
        this.fldAPIName = fldAPIName;
    }
    
    /**
     * 
     * @description: get picklist values for the specified object/field and sort them.
     * 
     * @return: list<SelectOption> sorted picklist values
     * 
     **/
    public list<SelectOption> getPicklistValues() {
        //create picklist wrapper
        pWrappers = new list<PicklistWrapper>();
        list<SelectOption> picklistValues = new list<SelectOption>();
        
        //create a selectOption for each entry
        for (PicklistEntry__c pe : picklistEntries) {
            pWrappers.add(new PicklistWrapper(new SelectOption(pe.Label__c, pe.Label__c), pe.Sort_Order__c, picklist.Alpha_Sort__c));
        }
        
        //sort picklist options
        pWrappers.sort();
        
        //add the sorted values to the list
        for (PicklistWrapper wrapper : pWrappers) picklistValues.add(wrapper.option);
        
        return picklistValues;
    }
    
    /**
     * 
     * @description: returns all picklist usage
     * 
     **/
    public PicklistUsage__c picklistUsage {
        get {
            if (PicklistUsage == null) {
                for (PicklistUsage__c usage : PicklistUsage__c.getAll().values()) {
                    if (usage.Object__c != null && usage.Object__c.equalsIgnoreCase(objAPIName) &&
                        usage.Field__c != null && usage.Field__c.equalsIgnoreCase(fldAPIName)) {
                        picklistUsage = usage;
                        break;
                    }
                }
            }
            return picklistUsage;
        }
        set;
    } 
    
    /**
     * 
     * @description: returns picklist based on picklistUsage
     * 
     **/
    public Picklist__c picklist {
        get {
            if (picklist == null && picklistUsage != null) {
                picklist = Picklist__c.getInstance(picklistUsage.Picklist__c);
            }
            return picklist;
        }
        set;
    }
    
    /**
     * 
     * @description: returns all picklist entries
     * 
     **/
    public list<PicklistEntry__c> picklistEntries {
        get {
            if (picklistEntries == null && picklist != null) {
                picklistEntries = new list<PicklistEntry__c>();
                for (PicklistEntry__c entry : PicklistEntry__c.getAll().values()) {
                    if (entry.IsActive__c && 
                        entry.Picklist__c != null && 
                        entry.Picklist__c.equalsIgnoreCase(picklist.Name)) 
                    {
                        picklistEntries.add(entry);
                    }
                }
            }
            return picklistEntries;
        }
        set;
    }
    
    /**
     * 
     * @description: wrapper class to hold selectOption for dynamic picklist.
     * 
     **/
    public class PicklistWrapper implements Comparable{
        
        public SelectOption option { get; set; }
        public boolean alphaSort { get; set; }
        public decimal customSortOrder { get; set; }
        
        public PicklistWrapper(SelectOption option, decimal customSortOrder, boolean alphaSort) {
            this.option = option;
            this.alphaSort = alphaSort;
            this.customSortOrder = customSortOrder;
        }
        
        public Integer compareTo(Object compareTo) {
            PicklistWrapper wrapper = (PicklistWrapper) compareTo;
            if (wrapper.alphaSort) { //sort by the picklist alpha sort
                if (option.getLabel() == wrapper.option.getLabel()) return 0;
                if (option.getLabel() > wrapper.option.getLabel()) return 1;
            }
            else {//sort by the picklistEntry sort order
                if (customSortOrder == wrapper.customSortOrder) return 0;
                if (customSortOrder > wrapper.customSortOrder) return 1;
            }
            return -1;        
        }
    }
}