objects/Program_Package__c.object
<CustomObject>
    <description>Used to track the programs that are packaged an offered to a client.  There should only be one program package offered to each client each fiscal year.</description>
    <fields>
        <fullName>Client_Status_New__c</fullName>
        <label>(R) Engagement Status</label>
        <picklist>
            <picklistValues>
                <fullName>Secured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Play</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program Package (Royall)</label>
    <nameField>
        <label>Program Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Packages (Royall)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Royall_Program__c.object
<CustomObject>
    <description>Used to track the programs that can be offered to a client.</description>
    <fields>
        <fullName>Lock_the_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lock the Record</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Package__c</fullName>
        <label>Program Package</label>
        <referenceTo>Program_Package__c</referenceTo>
        <relationshipLabel>Programs (Royall)</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>•	Contracted – We have a signed contract for the core program.  For upsells, we have either email or verbal approval.

•	Pending Signature – We have sent a contract to the client and are awaiting signature.

•	Proposed – The program has been proposed to the client and will likely be approved; however, a contract has not yet been drafted.

•	Forecasted (Probability Adjusted) – The program has been discussed and/or proposed to the client; however, we are not 100% confident that it will be approved at this level.  A probability of less than 100% has been assigned to this program.

•	Declined – We discussed and/or proposed a program that the client declined.</description>
        <inlineHelpText>Where does the conversation stand for this program?</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program (Royall)</label>
    <nameField>
        <label>Job Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs (Royall)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProgramPackageRoyallTriggerHelper.cls
/*
 *  Purpose         :   Helper class of Trigger_Program_Package_Royall, manually merged code from Royall Enviournment to Corporate Instance.
 * 						- Moved code from shift_mass_update_programs trigger to this class
 *
 *  Create By       :   Rajeev Jain
 *
 *  Created Date    :   06/24/2016
 *
 *  Revision Log    :   V_1.0 Created
 *
 **/
public without sharing class ProgramPackageRoyallTriggerHelper {
	
    /**
     *  @description    :   Merged code from shift_mass_update_programs trigger from Royall Enviournment
     *
     *  @args           :   List of old Account records
     *
     *  @return         :   void
     *
     **/
    public static void massUpdatePrograms(List<Program_Package__c> newProgramPackage, map<Id, Program_Package__c> oldProgramPackage) {
    	
        Map <Id,Program_Package__c> theUpdatedProgramsMap= new Map <Id,Program_Package__c > ();
        
        //Loop over each new program Package record
        for(Program_Package__c pckg : newProgramPackage){
            if(pckg.Client_Status_New__c != oldProgramPackage.get(pckg.Id).Client_Status_New__c && pckg.Client_Status_New__c == 'Lost'){
            	theUpdatedProgramsMap.put(pckg.Id, pckg);    
            }
        }
        
        if(theUpdatedProgramsMap.size() > 0){
            
            Set<Id> lockedPrgPkgIdSet = new Set<Id> ();
            
            List<Royall_Program__c> theProgramList = [select Id, Status__c, Program_Package__c, Lock_the_Record__c  
                                                                       from Royall_Program__c 
                                                                       where Program_Package__c in : theUpdatedProgramsMap.KeySet()];
            
            for( Royall_Program__c theProg: theProgramList ){
                theProg.Status__c = 'Declined';
                if(theProg.Lock_the_Record__c == True)
                    lockedPrgPkgIdSet.add(theProg.Program_Package__c);
            }
            
            //Update Program List
            List <Database.SaveResult> srList = Database.update(theProgramList,false);
            
            Set <Id> UpdatedProg = new Set<Id> (); 
            
            // Iterate through each returned result
            for (Database.SaveResult sr : srList) {
                if (sr.isSuccess()) {
                    UpdatedProg.add(sr.getId());
                }
            }
            
            Set<Id> failedProg = new Set<Id>();
            
            for( Royall_Program__c prog : theProgramList){
                if(!UpdatedProg.contains(prog.Id))
                    failedProg.add(prog.Program_Package__c);
            }
            
            // Add error to the program Package that were not updated
            if(failedProg.size() > 0){
                for( Program_Package__c theProPkg: theUpdatedProgramsMap.values()){
                    if(failedProg.contains(theProPkg.Id)){
                        if(lockedPrgPkgIdSet.contains(theProPkg.Id)) theProPkg.addError(System.Label.Error_Msg_Locked_Prog_Pck_update);
                        else theProPkg.addError(System.Label.Error_Msg_Prog_Pck_update);
                    }
                }
            }
        }
    }
}