objects/Reference__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>Reference_Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dedicated_Advisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dedicated Advisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NASA_Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NASA Principal</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reference_Modules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Module__c</fullName>
        <label>Reference Module</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Reference</label>
    <nameField>
        <displayFormat>Ref-{000000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Reference_Request_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Reference Request Contacts</relationshipLabel>
        <relationshipName>Reference_Request_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference Contact</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contact.Reference_Program_Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reference Request Contacts</relationshipLabel>
        <relationshipName>Reference_Request_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Modules__c</fullName>
        <label>Reference Modules</label>
        <type>TextArea</type>
    </fields>
    <label>Reference Request Contact</label>
    <nameField>
        <displayFormat>RRC-{0000}</displayFormat>
        <label>Reference Request Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference Request Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ReferenceRequestContactHelper.cls
public class ReferenceRequestContactHelper {
    
    /**
     * @description: Submit all Reference Request Contacts for approval
     * 
     *  
     **/
    public static void submitForApproval(set<Id> referenceRequestContactIds) {
        for (Id rrcId : referenceRequestContactIds) {
            
            Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
            app.setObjectId(rrcId);
            Approval.ProcessResult result = Approval.process(app);
        }
    }
    
    /**
     * @description: populate the Approver field on all Reference Request Contacts
     * 
     * 
     **/
    public static void populateApprover(list<Reference_Request_Contact__c> refReqContacts) {
        //set of contact ids
        set<Id> contactIds = new set<Id>();
        set<string> applicableModules = new set<string>();
        for (Reference_Request_Contact__c rrc : refReqContacts) {
            contactIds.add(rrc.Reference_Contact__c);
            if (rrc.Reference_Modules__c != null) {
                list<string> modules = rrc.Reference_Modules__c.split('\r\n');
                applicableModules.addAll(modules);
            }
        }
        
        //get all contacts with applicable references
        map<Id, Contact> contactMap = new map<Id, Contact>([SELECT Id, Name, (SELECT Id, Dedicated_Advisor__c, NASA_Principal__c, Reference_Module__c FROM Reference_Modules__r 
                                                                        WHERE Reference_Module__c IN :applicableModules AND Reference_Module__c != null)
                                                            FROM Contact 
                                                            WHERE Id IN :contactIds]);// AND Id IN (SELECT Contact_Name__c FROM Reference__c) [vh commented out 2/2/16]
        
        //match the reference request contact to the related reference
        for (Reference_Request_Contact__c rrc : refReqContacts) {
            Contact c;
            if (contactMap != null)
                c = contactMap.get(rrc.Reference_Contact__c);
            //throw an error if the reference request contac does not have any applicable references
            if (c == null || c.Reference_Modules__r.size() == 0) {
                string name;
                if (c != null && c.Name != null) name = string.escapeSingleQuotes(c.Name);
                rrc.addError('The Contact \'' + name + '\' does not have any applicable references');
            }
            else {
                rrc.Approver__c = c.Reference_Modules__r[0].Dedicated_Advisor__c;
            }
        }
    }
}