objects/Reference__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>Reference_Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <formula>IF( ISPICKVAL( Reference_Status__c, &quot;Vetted&quot;), true, false)</formula>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference_Level__c</fullName>
        <label>Reference Level</label>
        <picklist>
            <picklistValues>
                <fullName>Pipeline</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambassador</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reference_Module__c</fullName>
        <label>Reference Module</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Reference</label>
    <nameField>
        <displayFormat>Ref-{000000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <recordTypes>
        <fullName>PT</fullName>
        <active>true</active>
        <description>References for the Performance Technology group of products</description>
        <label>PT</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Reference_Perk__c.object
<CustomObject>
    <description>A Reference Perk is offered to an Ambassador Institution.  Any contact at the Institution may take advantage of the perk.</description>
    <fields>
        <fullName>Applicable_Reference_Module__c</fullName>
        <label>Applicable Reference Module</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reference Perks</relationshipLabel>
        <relationshipName>Reference_Perks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Perk_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Perk Template</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or the Record Type is not Perk Template</errorMessage>
            <filterItems>
                <field>Reference_Perk__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Perk Template</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Reference_Perk__c</referenceTo>
        <relationshipLabel>Reference Perks</relationshipLabel>
        <relationshipName>Reference_Perks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference_Perk__c</fullName>
        <label>Reference Perk</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reference</label>
        <referenceTo>Reference__c</referenceTo>
        <relationshipLabel>Reference Perks</relationshipLabel>
        <relationshipName>Reference_Perks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(TODAY() &gt;= Perk_Available_Date__c,
  IF(TODAY() &gt; Perk_Expiration_Date__c,
    &quot;Expired&quot;,
    IF(NOT( ISBLANK( Acceptance_Date__c ) ),
      &quot;Accepted&quot;,
      &quot;Available&quot;
	)
  ),
  &quot;Unavailable&quot;
)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Reference Perk</label>
    <nameField>
        <label>Reference Perk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference Perks</pluralLabel>
    <recordTypes>
        <fullName>PT</fullName>
        <active>true</active>
        <description>Reference Perks related to the PT Reference Program</description>
        <label>PT</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReferencePerkTriggerHelper.cls
/** 
  * Description     :   Helper class for Trigger_ReferencePerk 
  *
  * Created By      :   Rajeev Jain(Simplyforce)
  *
  * Created Date    :   12/15/2015
  *
  * Version         :   V1.0 Created
  **/ 
public without sharing class ReferencePerkTriggerHelper {
    
    //Static Variables
    public static Map<Id, RecordType> mapReferencePerkRecordTypes{
        
        get{
            if(mapReferencePerkRecordTypes == null)
            
                mapReferencePerkRecordTypes = new Map<Id, RecordType>([select Id, DeveloperName from RecordType 
                                                                        where sObjectType = 'Reference_Perk__c' 
                                                                        AND IsActive = true]);  
            
            return mapReferencePerkRecordTypes;
        }
    } 
    
    /**
     *  @description    :   Method to populate Eligible Reference Perk fields. Eligibiliy criteria are as follow
     *                      Record Type = 'Performance Technology'
     *                      •   Reference.IsActive__c = true
     *                      •   Reference.Reference_Level__c = “Ambassador”
     *                      •   Perk Template.Status__c = “Available”
     *                      •   Reference.Reference_Module__c = Perk Template.Applicable_Reference_Module__c
     *
     *  @args           :   List of new Reference Perk, Map of old Reference Perk
     *
     *  @return         :   void
     *
    **/
    public static void populateFieldsOfEligibleReferencePerk(List<Reference_Perk__c> newMemberSupports, Map<Id, Reference_Perk__c> mapOldMemberSupports){
        
        //Checkk for Insert and Update Case
        if(newMemberSupports != null){
            
            //Map to hold the Reference Records corrosponding to its each record Id
            Map<Id, Reference__c> mapReferenceRecords = new Map<Id, Reference__c>();
            
            //Map to hold Perk Templates Records Corrosponding to its each record Id
            Map<Id, Reference_Perk__c> mapPerkTemplates = new Map<Id, Reference_Perk__c>();
            
            //Set to Hold Refernece id
            Set<Id> setReferenceIds = new Set<Id>();
            
            //Set to Hold ids of the Perk Template
            Set<Id> serPerkTemplateIds = new Set<Id>();
            
            //Loop over eahc Refernece Perk
            for(Reference_Perk__c perk : newMemberSupports){
                
                //Check for Reference Perk eligibility Criteria
                if(mapReferencePerkRecordTypes.get(perk.RecordTypeId).DeveloperName == Label.PT && 
                        perk.Reference__c != null && perk.Perk_Template__c != null){
                    
                    if(mapOldMemberSupports == null || perk.Reference__c != mapOldMemberSupports.get(perk.Id).Reference__c)
                        setReferenceIds.add(perk.Reference__c);
                    
                    if(mapOldMemberSupports == null || perk.Perk_Template__c != mapOldMemberSupports.get(perk.Id).Perk_Template__c)
                        serPerkTemplateIds.add(perk.Perk_Template__c);
                }
            }
            
            //Check size of SetReferneceIds
            if(setReferenceIds.size() > 0){
                mapReferenceRecords = new Map<Id, Reference__c>([select Id, IsActive__c, Reference_Level__c, Reference_Module__c, Contact_Name__c from Reference__c where Id IN :setReferenceIds]); 
            }
            
            //Check size of serPerkTemplateIds
            if(serPerkTemplateIds.size() > 0){
                mapPerkTemplates = new Map<Id, Reference_Perk__c>([select Id, Status__c, Applicable_Reference_Module__c from Reference_Perk__c where Id IN :serPerkTemplateIds]);
            }
            
            //Reloop over on the New Reference Perks Records and Populated its Contact field based on criteria
            for(Reference_Perk__c perk : newMemberSupports){
                
                //Check if all above mentioned conditions matched 
                Reference__c ref = mapReferenceRecords.containsKey(perk.Reference__c) ? mapReferenceRecords.get(perk.Reference__c) : new Reference__c();
                Reference_Perk__c perkTemp = mapPerkTemplates.containsKey(perk.Perk_Template__c) ? mapPerkTemplates.get(perk.Perk_Template__c) : new Reference_Perk__c();
                
                //Check if all condition meets criteira as mentioned on the method description then populate contact field on refernece perk
                if(ref.IsActive__c && ref.Reference_Level__c.equalsIgnoreCase('Ambassador') && 
                    ref.Reference_Module__c == perkTemp.Applicable_Reference_Module__c &&
                    perkTemp.Status__c.equalsIgnoreCase('Available')){
                    perk.Contact__c = ref.Contact_Name__c;          
                }
            }
        }   
    }
}