objects/Restriction_Clearance_Request__c.object
<CustomObject>
    <fields>
        <fullName>Warm_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warm Lead</label>
        <referenceTo>Warm_Lead__c</referenceTo>
        <relationshipLabel>Restriction Clearance Requests</relationshipLabel>
        <relationshipName>Restriction_Clearance_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Restriction Clearance Request</label>
    <nameField>
        <label>Restriction Clearance Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restriction Clearance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Warm_Lead__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>CR-3485-This field is used in an integration with Eloqua. Please research with the appropriate stakeholders/liaisons before altering it&apos;s meaning, usage, field type or other field characteristics. Do not delete or change the current API name.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Already a Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Timing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined/No Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified - Bad Timing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified - Competitor in Place</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified - Contact Too Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified - No Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified - Non-Viable Org</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NP - Not Viable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Identified (Moved to Opportunity)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - Contact Under Protocol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - Restriction Clearance Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restricted - Permission Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retained by Strategic Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warming - Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warming - Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong Marketer Assigned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Warm Lead</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warm Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RestrictionClearanceRequestHelper.cls
/*
    Purpose         :   This class is helper class for trigger on Restriction Clearance Requests object.
                
    Create By       :   Simplyforce Technology
    
    Created Date    :   11/07/2012
    
    Current Version :   v1.0
    
    Revision Log    :   V_1.0 Created - CR-20120924-1526
*/
public without sharing class RestrictionClearanceRequestHelper {
	
	//This method is to update the Warm Lead status when restriction Clearance Request is getting created
	public static void updateWarmLeads(List<Restriction_Clearance_Request__c> rCRequests) {
		
		//Create a set to hold the warm lead Ids and maintian the uniqueness
		Set<Id> warmLeadsIds = new Set<Id>();
		
		//Create a list of the Warm Lead records to be updated
		List<Warm_Lead__c> warmLeads = new List<Warm_Lead__c>();
		
		//Loop through the requests
		for(Restriction_Clearance_Request__c rCR : rCRequests) {
			
			//Check if Warm_Lead__c is not null and add in set
			if(rCR.Warm_Lead__c != null)
				warmLeadsIds.add(rCR.Warm_Lead__c);
		}
		
		//Query all the Warm leads which are not having status = 'Pending Restriction Clearance'
		for(Warm_Lead__c warmLead : [Select Status__c from Warm_Lead__c where Status__c !=: Constants.STATUS_WARM_LEAD_PENDING_RESTRICTION_CLEARANCE
										AND ID IN: warmLeadsIds]) {
			
			//Set the status and add recotrds in the list to be updated
			warmLead.Status__c = Constants.STATUS_WARM_LEAD_PENDING_RESTRICTION_CLEARANCE;
			warmLeads.add(warmLead);
		}
		
		//check for the size and update the records
		if(warmLeads.size() > 0)
			update warmLeads;
	}
}