objects/Role_Program_Perspective__c.object
<CustomObject>
    <description>Each Staff Assignment may relate to zero or many Program Perspectives. Each of these records has its own effective dating, and these records are aggregated into a viewable list on its parent Staff Assignment for presentation on related lists and simple reports.</description>
    <fields>
        <fullName>Effective_End__c</fullName>
        <label>Effective End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Staff_Assignment__c</fullName>
        <label>Staff Assignment</label>
        <referenceTo>Team_Membership__c</referenceTo>
        <relationshipLabel>Role Program Perspectives</relationshipLabel>
        <relationshipName>Role_Program_Perspectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Role Program Perspective</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Role Program Perspectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Membership__c.object
<CustomObject>
    <description>This object holds the relationship between the Staff member, Institution, and Assignment Role, as well as defining the effective dates associated with the SA.</description>
    <fields>
        <fullName>Program_Perspectives__c</fullName>
        <label>Current Program Responsibilities</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Staff Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Sched_RecalculateProgramPerspective.cls
/**
 * 	Purpose			:	Scheduler class to validate Program Perspective on Staff Assignment.
 * 
 * 	Created By		:	Subhash Garhwal
 * 
 *	Created Date	:	06/30/2015 
 * 
 * 	Revision Logs	:	V_1.0 - Created - CR-20150618-9014
 * 
 **/ 
global class Sched_RecalculateProgramPerspective implements Schedulable {
	
	//Execute method
	global void execute(SchedulableContext sc) {
		
		//Set to hold Staff Assignment Ids
		Set<Id> setSAIds = new Set<Id>();
		
		//Query through Role Program Perspective
		for(Role_Program_Perspective__c rPP : [Select Id, Staff_Assignment__c, Effective_End__c From Role_Program_Perspective__c Where Staff_Assignment__c != null AND Effective_End__c = YESTERDAY])
			setSAIds.add(rPP.Staff_Assignment__c);
		
		//Check for set size
		if(setSAIds.size() > 0) {
			
			//Call TeamMembershipTriggerHelper class method to populate correct Program Perspectives on Staff Assignment
			TeamMembershipTriggerHelper.recalculateProgramPerspectives([Select Id, Program_Perspectives__c From Team_Membership__c Where Id IN : setSAIds]);
		}
	}
}