objects/Site_Profile__c.object
<CustomObject>
    <description>Determines the site(s) that a Contact has access to.</description>
    <fields>
        <fullName>Institution__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Contact__r.AccountId,  Contact__r.Account.Name,  &quot;_self&quot;)</formula>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Use the Activate/Deactivate buttons above to update the Status as needed.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>EAB.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advisory.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Royall.com</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <formula>IF(NOT(ISBLANK( User_Id_Override__c )), TEXT( User_Id_Override__c ) , User_Id_Autonumber__c )</formula>
        <label>User Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <externalId>true</externalId>
        <label>Username</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Site Profile</label>
    <nameField>
        <displayFormat>SP-{0000000}</displayFormat>
        <label>Site Profile Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Web_Service_Log__c.object
<CustomObject>
    <description>Log of all requests and corresponding responses with an external web service</description>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Web Service Logs</relationshipLabel>
        <relationshipName>Web_Service_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Message_Log__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <label>Request Message Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Sent__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <label>Request Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requested_By__c</fullName>
        <description>Created for the EAB / Advisory project.  Used for tracking the user that submitted a request.  In some cases, the request is sent through the Site page but was initiated by an internal user (ie: user with chatter plus profile).</description>
        <label>Requested By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Message_Log__c</fullName>
        <label>Response Message Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Message__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <label>Response Message</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Site_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Profile</label>
        <referenceTo>Site_Profile__c</referenceTo>
        <relationshipLabel>Web Service Logs</relationshipLabel>
        <relationshipName>Web_Service_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Web_Service_Method__c</fullName>
        <description>Origin: CR-2089 - CreditCardAdmin</description>
        <label>Web Service Method</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Web Service Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Web Service Logs</pluralLabel>
    <recordTypes>
        <fullName>Institution</fullName>
        <active>true</active>
        <label>Institution</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site_Profile</fullName>
        <active>true</active>
        <description>Transaction Log with Site Profile callout details.</description>
        <label>Site Profile</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SiteProfileLogger.cls
/**
 *	Purpose			:	Site Profile Logging functionlity
 *
 *	Created By		:	Victor Hanson
 *
 *	Created Date	:	08/25/2014
 *
 *	Current Version	:	V1.0 - Created
 **/
public class SiteProfileLogger {
	
    private static final integer MAX_REQUEST_RESPONSE_LOG_LENGTH = 32768;
    private static final integer MAX_RESPONSE_MESSAGE_LENGTH = 5000;
    
    //get the Web Service Log's Site Profile record type id
    public static Id wsLogSiteProfileRTId {
        get {
            if (wsLogSiteProfileRTId == null)
                wsLogSiteProfileRTId = Schema.SObjectType.Web_Service_Log__c.RecordTypeInfosByName.get('Site Profile').RecordTypeId;
            return wsLogSiteProfileRTId;
        }
        set;
    }
    
    //get the Web Service Log's Institution record type id
    public static Id wsLogInstitutionRTId {
        get {
            if (wsLogInstitutionRTId == null)
                wsLogInstitutionRTId = Schema.SObjectType.Web_Service_Log__c.RecordTypeInfosByName.get('Institution').RecordTypeId;
            return wsLogInstitutionRTId;
        }
        set;
    }
	
    //holds the original siteUser prior to processing
    public static SiteUser originalSiteUser {
        get {
            if (originalSiteUser == null) originalSiteUser = new SiteUser();
            return originalSiteUser;
        }
        set;
    }
    
    /**
	 * 	@description	:	This method is to create a Log record for Site Profile requests
	 *
	 *	@param			:	SiteUser
	 *
	 *	@return			:	void
	 *
	 **/
	public static void Log(SiteUser sUser){
        Site_Profile__c sProfile = sUser.Site_Profile;
        if (sProfile == null) {
		    	
		    string userId = string.valueOf(sUser.User_Id);
		    if (userId == null && sUser.Attendee != null) userId = string.valueOf(sUser.Attendee.User_Id);
		    
		    if (userId != null) {
        		list<Site_Profile__c> siteProfiles = [SELECT Id, Type__c, Status__c, Username__c FROM Site_Profile__c WHERE User_Id__c = :userId LIMIT 1];
                if (siteProfiles.size() > 0) sProfile = siteProfiles[0];
		    }
        }
        
        if (sProfile != null) { 
            //Create a webservice log record
            Web_Service_Log__c webServiceLog = new Web_Service_Log__c(RecordTypeId = wsLogSiteProfileRTId,
                                                                      Site_Profile__c = sProfile.Id,
                                                                      Web_Service_Method__c = originalSiteUser.Command,
                                                                      Request_Sent__c = system.now(),
                                                                      Response_Message_Log__c = JSON.serializePretty(sUser),
                                                                      Response_Message__c = sUser.Response,
                                                                      Requested_By__c = sUser.Modified_By,
                                                                      Request_Message_Log__c = JSON.serializePretty(originalSiteUser));
            //trim field excess+3 and add elipse (...) to show that the log value had to be trimmed
            if (webServiceLog.Response_Message_Log__c != null && webServiceLog.Response_Message_Log__c.length() > MAX_REQUEST_RESPONSE_LOG_LENGTH) {
                webServiceLog.Response_Message_Log__c = webServiceLog.Response_Message_Log__c.subString(0, (MAX_REQUEST_RESPONSE_LOG_LENGTH-3)) + '...';
            }
            
            if (webServiceLog.Request_Message_Log__c != null && webServiceLog.Request_Message_Log__c.length() > MAX_REQUEST_RESPONSE_LOG_LENGTH) {
                webServiceLog.Request_Message_Log__c = webServiceLog.Request_Message_Log__c.subString(0, (MAX_REQUEST_RESPONSE_LOG_LENGTH-3)) + '...';
            }
            
            if (webServiceLog.Response_Message__c != null && webServiceLog.Response_Message__c.length() > MAX_RESPONSE_MESSAGE_LENGTH) {
                webServiceLog.Response_Message__c = webServiceLog.Response_Message__c.subString(0, (MAX_RESPONSE_MESSAGE_LENGTH-3)) + '...';
            }
            
            //insert log
            insert webServiceLog;
        }
	}
    
    /**
	 * 	@description	:	This method is to create a Log record for Site Profile requests
	 *
	 *	@param			:	SiteUser
	 *
	 *	@return			:	void
	 *
	 **/
    public static void Log(string institutionId, string institutionJSON, string command, string result, string response){
        
        //Create a webservice log record
        Web_Service_Log__c webServiceLog = new Web_Service_Log__c(RecordTypeId = wsLogInstitutionRTId,
                                                                  Institution__c = institutionId,
                                                                  Web_Service_Method__c = command,
                                                                  Request_Sent__c = system.now(),
                                                                  Response_Message_Log__c = response,
                                                                  Response_Message__c = result,
                                                                  Request_Message_Log__c = JSON.serializePretty(JSON.deserializeUntyped(institutionJSON)));
        
        //insert log
        insert webServiceLog;
    }
}