objects/Staff_History__c.object
<CustomObject>
    <description>Each value instance (the application of a given attribute to a given Contact for a given period) will be tracked in this object. Many of the contents will be maintained exclusively in WD, and many will be maintained in SFDC.
Each record is typified by the Value Type of the attribute. 
Whether S&amp;O or the integration user may modify a given attribute is flagged in each record.</description>
    <fields>
        <fullName>Checkbox_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checkbox Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Value__c</fullName>
        <label>Date Value</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lookup_Value__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lookup Value</label>
        <referenceTo>Program_Perspective__c</referenceTo>
        <relationshipName>Staff_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_Value__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percent_Value__c</fullName>
        <label>Percent Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Value Type</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Value Type you have selected is inactive.</errorMessage>
            <filterItems>
                <field>Value_Type__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Value_Type__c</referenceTo>
        <relationshipLabel>Staff Attributes</relationshipLabel>
        <relationshipName>Staff_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff Attribute</label>
    <nameField>
        <label>Staff Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Attributes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Value_Type__c.object
<CustomObject>
    <description>This object holds the definitions of the different attributes that can be assigned to a Contact via Staff Attribute.</description>
    <fields>
        <fullName>Use_As_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Name is used as the assigned value for any associated Staff Attribute.</description>
        <inlineHelpText>When checked, the Name is used as the assigned value for any associated Staff Attribute.</inlineHelpText>
        <label>Use As Value</label>
        <type>Checkbox</type>
    </fields>
    <label>Value Type</label>
    <nameField>
        <label>Value Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Value Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ValueTypeTriggerHelper.cls
/**
 *  Description     :   Helper class for Trigger_ValueType trigger.
 *
 *  Created By      :   Subhash Garhwal 
 *
 *  Created Date    :   09/10/2015
 *
 *  Revision Logs   :   V_1.0 - Created - CR-20150825-9182
 *						
 **/
public without sharing class ValueTypeTriggerHelper {

	/**
     *	@description	:	This method is used to set all fields to blank when use as value is true or changed
     *
     *	@args			:	List<Value_Type__c> , Map<Id, Value_Type__c> 
     *
     *	@return			:	void
     *
     **/
	public static void reNameStaffHistory(List<Value_Type__c> valueTypes, Map<Id, Value_Type__c> mapValueTypes)	{

		//Set of value type ids
		Set<Id> setVTypeIds = new Set<Id>();			

		//Loop through value type
		for(Value_Type__c vT : valueTypes) {
		
			//Check when use as value field is true and field is changed
			if(vT.Use_As_Value__c && (vT.Use_As_Value__c != mapValueTypes.get(vT.Id).Use_As_Value__c || vT.Name != mapValueTypes.get(vT.Id).Name))
				//Add Id in sets
				setVTypeIds.add(vT.Id);
		}
		
		//Check for set size
		if(setVTypeIds.size()> 0) {
		
			//Loop Through staff History.
    		List<Staff_History__c> staffAttributes = [Select Id, Name, Text_Value__c, Checkbox_Value__c, Number_Value__c, Percent_Value__c, Date_Value__c, Lookup_Value__c,
    								   	              Value_Type__c, Value_Type__r.Name From Staff_History__c Where Value_Type__c IN : setVTypeIds];
    	
			//Check list size
			if(staffAttributes.size() > 0)
				update staffAttributes;
		}
	}
}