objects/Team_Membership__c.object
<CustomObject>
    <description>This object holds the relationship between the Staff member, Institution, and Assignment Role, as well as defining the effective dates associated with the SA.</description>
    <fields>
        <fullName>End_date__c</fullName>
        <label>Role End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Staff Assignments</relationshipLabel>
        <relationshipName>Team_Memberships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Role</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5) OR ((6 OR 10) AND 7) OR (8 AND 9))</booleanFilter>
            <filterItems>
                <field>Team_Role__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Opportunity</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Opportunity__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Membership</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Membership__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Assigned</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Institution__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Project__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Default</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team_Role__c</referenceTo>
        <relationshipLabel>Staff Assignments</relationshipLabel>
        <relationshipName>Team_Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Staff Assignments</relationshipLabel>
        <relationshipName>Staff_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Role Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( 
	AND( 
		Start_date__c &lt;= TODAY(),
		OR(
			ISNULL(End_date__c),
			End_date__c &gt;= TODAY() 
		)
	), 
	&apos;Active&apos;, 
	&apos;Inactive&apos; 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Staff Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Role__c.object
<CustomObject>
    <description>This object holds the Role definitions. Each Role is associated with a business owner largely considered responsible for assigning and analyzing the use of that Role in SAs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for CR-20150908-9224.</description>
        <label>Institution</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created for CR-20150908-9224.</description>
        <label>Solutions</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Batch_UpdateSolutionRelatedDataOnAccount.cls
/**
 *  Purpose         :   This Batch is to replicate the solution data on the Account from the solution Staff Assignment 
 * 
 *  Created By      :   Mahendra Swarnkar
 * 
 *  Created Date    :   03/22/2016  
 * 
 *  Revision Logs   :   V_1.0 - Created - CR-20150908-9224
 *                      
 **/ 
global class Batch_UpdateSolutionRelatedDataOnAccount implements Database.Batchable<SObject>, Database.Stateful {

    //Variable to store dynamic soql query
    public String query;
    
    //String variable to hold the entire log message string value
    global String debugLogStr; 

    //Batch Constructor
    global Batch_UpdateSolutionRelatedDataOnAccount() {
        debugLogStr = '';
    }

    //Start Method
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        //Checking query variable for null value
        if (query == null)
            query = 'SELECT Id, Institution__c ' +  
            		'FROM Team_Membership__c '+  
                    'WHERE Role__c != null ' +
            		'AND Institution__c != null ' +
            		'AND Role__r.Solution__c != null ' + 
                    'AND Role__r.Solution__c = true ' + 
                    'AND Role__r.Active__c != null ' + 
                    'AND Role__r.Active__c = true ' +
            		'AND Status__c != null ' +
            		'AND Status__c != ' + '\'\'' +
            		'AND Status__c = ' + '\'Inactive\'  ';
        
        return Database.getQueryLocator(query);
    }
    
    //Execute method
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
    
        //Set to hold the institution Ids
        Set<Id> setInstitutionIds = new Set<Id>();
        
        //Loop through staff assignment records in current context
        for(Team_Membership__c tm : (List<Team_Membership__c>)scope) {
            if(tm.Institution__c != null)
            	setInstitutionIds.add(tm.Institution__c);
        }
        
        //Checking set for size value
        if(setInstitutionIds.size() > 0) {
            
            //Map having account Id key as
        	Map<Id, Integer> mapAccountIdWithActiveSACount = new Map<Id, Integer>();
            Map<Id, Date> mapAcountIdwithInactiveSALatestRoleStart = new Map<Id, Date>();
            Map<Id, Date> mapAcountIdwithSALatestRoleEnd = new Map<Id, Date>();
            
            //Map of accounts
            Map<Id, Account> mapAccounts = new Map<Id, Account>();
            
            //Loop through staff assignment records
            for(Team_Membership__c tm : [SELECT Id, Start_date__c, End_date__c, Staff_member__c, Institution__c, Status__c,
                                         Role__c, Role__r.Solution__c, Role__r.Active__c, Role__r.Name, 
                                         Institution__r.Solution_Adopted__c, Institution__r.Solution_Ended__c,
                                         Institution__r.Solution_Partner__c, Institution__r.Solution_Status__c ,Institution__r.Solution_Partner_Role__c
                                         FROM Team_Membership__c 
                                         WHERE Institution__c != null 
                                         AND Institution__c IN : setInstitutionIds
                                         AND Role__c != null
                                         AND Role__r.Solution__c != null
                                         AND Role__r.Solution__c = true
                                         AND Role__r.Active__c != null
                                         AND Role__r.Active__c = true
                                         ORDER BY LastModifiedDate ASC]) {	
                
                //Populating account map with fields values                             
                mapAccounts.put(tm.Institution__c, new Account(Id = tm.Institution__c, 
                                                               Solution_Partner__c = tm.Institution__r.Solution_Partner__c,
                                                               Solution_Ended__c = tm.Institution__r.Solution_Ended__c,
                                                               Solution_Status__c = tm.Institution__r.Solution_Status__c ,
                                                               Solution_Partner_Role__c = tm.Institution__r.Solution_Partner_Role__c
                                                              ));	                             
                
                //Checking for the Inactive status
                if(tm.Status__c != null && tm.Status__c != '' && tm.Status__c == 'Inactive') {                         
                     
                    //Checking for key presence in map and populating it with latest End date value for Active SA records
                    if(!mapAcountIdwithSALatestRoleEnd.containsKey(tm.Institution__c))
                        mapAcountIdwithSALatestRoleEnd.put(tm.Institution__c, tm.End_Date__c);
                    else {
                        if((mapAcountIdwithSALatestRoleEnd.get(tm.Institution__c) == null 
                            || (tm.End_Date__c > mapAcountIdwithSALatestRoleEnd.get(tm.Institution__c))))
                            mapAcountIdwithSALatestRoleEnd.put(tm.Institution__c, tm.End_Date__c);
                    }
                    
                    //Checking for key presence in map and populating it with latest start date value
                    if(!mapAcountIdwithInactiveSALatestRoleStart.containsKey(tm.Institution__c))
                        mapAcountIdwithInactiveSALatestRoleStart.put(tm.Institution__c, tm.Start_date__c);
                    else {
                        if((mapAcountIdwithInactiveSALatestRoleStart.get(tm.Institution__c) == null 
                            || (tm.Start_date__c > mapAcountIdwithInactiveSALatestRoleStart.get(tm.Institution__c))))
                            mapAcountIdwithInactiveSALatestRoleStart.put(tm.Institution__c, tm.Start_date__c);
                    }
                }
                    
                //Checking for the active status                             
                if(tm.Status__c != null && tm.Status__c != '' && tm.Status__c == 'Active') {
            		
                    //Populating map with appropriate key and value pair
                	if(!mapAccountIdWithActiveSACount.containsKey(tm.Institution__c))
                		mapAccountIdWithActiveSACount.put(tm.Institution__c, 1);
               		else
                		mapAccountIdWithActiveSACount.put(tm.Institution__c, (mapAccountIdWithActiveSACount.get(tm.Institution__c) + 1));
                }                             
    		}
            
            //Map of accounts
            Map<Id, Account> mapAccountsToUpdate = new Map<Id, Account>();
            
            //Loop through staff assignment records in current context
        	for(Team_Membership__c tm : (List<Team_Membership__c>)scope) {
                
                if(tm.Institution__c != null && !mapAccountIdWithActiveSACount.containsKey(tm.Institution__c)) {
                    
               		//Populating account instance with fields values and then adding it to map of records
               		Account acc = new Account(Id = tm.Institution__c);
                    
                    if(mapAccounts.containsKey(tm.Institution__c) 
                    	&& mapAccounts.get(tm.Institution__c) != null) {
                    	
                        //Checking for SA record Id on which RoleStart date is grater that today and 
                        //blank out the  solution status field value on the institution.  
                        if(mapAcountIdwithInactiveSALatestRoleStart.containsKey(tm.Institution__c) 
                        	&& mapAcountIdwithInactiveSALatestRoleStart.get(tm.Institution__c) > System.today() )
                            acc.Solution_Status__c = null;
                        else{
                        	if(mapAccounts.get(tm.Institution__c).Solution_Status__c != System.label.SOLUTION_PARTNER_STATUS_FORMER)
                        		acc.Solution_Status__c = System.label.SOLUTION_PARTNER_STATUS_FORMER;        
                        }
                        
                        if(mapAccounts.get(tm.Institution__c).Solution_Partner__c != null)
                       		acc.Solution_Partner__c = null;    
                        
                        if(mapAccounts.get(tm.Institution__c).Solution_Partner_Role__c != null)
                       		acc.Solution_Partner_Role__c = '';    
                            
                        if(mapAcountIdwithSALatestRoleEnd.containsKey(tm.Institution__c))
                    		acc.Solution_Ended__c = mapAcountIdwithSALatestRoleEnd.get(tm.Institution__c);
                    
                       	mapAccountsToUpdate.put(tm.Institution__c, acc);    
                	}
                }
            } 
            
            //String variable to hold the error message string in case of any failure
        	String logMessage = '';
        
            //Check for size 
        	if(mapAccountsToUpdate.values().size() > 0) {
            
                //disable the all the triggers
                Util.BypassAllTriggers = true;
            
                //Making a try to update the list of records and recording error messages will be emailed to the SFAdmin 
                logMessage = Util.createLog(Database.update(mapAccountsToUpdate.values(), false));
                
                //Enable the all the triggers
                Util.BypassAllTriggers = false;
        	}
            
            //Checking errors log messages string for blank value and append it to final error message string only and only if it have proper value with it
        	if(logMessage != '') 
            	debugLogStr += logMessage;
        }    
    }
    
    //Finish method
    global void finish(Database.BatchableContext BC) {
        
        //Checking error string for blank value but if it does not have blank value with it then emailed it to SFAdmin.
        if(debugLogStr != '')
            Util.sendBatchStatus(BC.getJobId(), 'Batch_UpdateSolutionRelatedDataOnAccount', debugLogStr, Label.Salesforce_Admin_Email);
    }
}