objects/Team_Membership__c.object
<CustomObject>
    <description>This object holds the relationship between the Staff member, Institution, and Assignment Role, as well as defining the effective dates associated with the SA.</description>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Role</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND ((2 AND 3) OR (4 AND 5) OR ((6 OR 10) AND 7) OR (8 AND 9))</booleanFilter>
            <filterItems>
                <field>Team_Role__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Opportunity</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Opportunity__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Membership</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Membership__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Assigned</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Institution__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project</value>
            </filterItems>
            <filterItems>
                <field>Team_Role__c.Project__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Default</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team_Role__c</referenceTo>
        <relationshipLabel>Staff Assignments</relationshipLabel>
        <relationshipName>Team_Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Employee_User_Record__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Contact.Employee_User_Record__r.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Staff Assignments</relationshipLabel>
        <relationshipName>Staff_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staff Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Role__c.object
<CustomObject>
    <description>This object holds the Role definitions. Each Role is associated with a business owner largely considered responsible for assigning and analyzing the use of that Role in SAs.</description>
    <label>Assignment Role</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TeamRoleTriggerHelper.cls
/**
 * 	Purpose			:	This class is to work as helper class for Team Role Trigger
 * 
 * 	Created By		:	Bhavi Sharma
 * 
 *	Created Date	:	03/31/2015 
 * 
 * 	Revision Logs	:	V_1.0 - Created
 *						V_1.1 - Modified By - Subhash Garhwal - 07/02/2015 - CR-20150618-9014 - New method added - validateDelete
 * 
 **/ 
public with sharing class TeamRoleTriggerHelper {
	
	/**
	 *	@description	:	This methiod is to validate the data before inserting into database. If there is any error, display error message to user.
	 *
	 *	@args			:	List of Team Roles
	 *
	 *	@return			:	void
	 *
	 **/
	public static void validateTeamRoles(List<Team_Role__c> teamRoles) {
		
		//Create a set to  hold the name of roles
		Set<String> rolesNames = new Set<String>();
		
		//Loop through the roles
		for(Team_Role__c teamRole : teamRoles) {
			
			//Check team Role in set
			if(rolesNames.contains(teamRole.Name))
				throw new CustomException(Label.ERROR_UNIQUENESS_ROLE_NAME);
				
			//Add Role name
			rolesNames.add(teamRole.Name);
		}
			
		//Query database to check if there is already a record with the same name
		Integer existingCount = [Select count() from Team_Role__c where Name IN: rolesNames AND ID NOT IN: teamRoles];
		
		//If there is any existing user, throww an error message to user
		if(existingCount > 0)
			throw new CustomException(Label.ERROR_UNIQUENESS_ROLE_NAME);
	}
	
	/**
	 *	@description	:	This method is to check if Assignment Role (Staff Role) is used on any Staff Assignment than don't allow user to delete it.
	 *
	 *	@args			:	List<Team_Role__c>
	 *
	 *	@return			:	void 
	 *
	 **/ 
	public static void validateDelete(List<Team_Role__c> teamRoles) {
		
		//Query through Staff Assignment
		List<Team_Membership__c> teamMemberships = [Select Id From Team_Membership__c Where Role__c IN : teamRoles];
		
		//If there is any Staff Assignment which is using Assignment Role (Staff Role), throw an eror message to user
		if(teamMemberships.size() > 0)
			throw new CustomException(Label.ASSIGNMENT_ROLE_IN_USE);	
	}
	
	/**
     *	@decription	:	This method is used to update all the related Staff Assignments name, if Team Role name is changed.
     *					For this we will blank update all the related Staff Assignments, do to this Renaming workflow will execute and update SA names according	
     *
     *	@args		:	List<Contact>, Map<Id, Contact>
     *
     *	@return		:	void
     *
     **/
	public static void updateStaffAssignment(List<Team_Role__c> teamRoles, Map<Id, Team_Role__c> mapOldTeamRoles) {
		
		//Set to hold Team Roles Ids
		Set<Id> setTMIds = new Set<Id>();
		
		//Loop through Team_Role__c
		for(Team_Role__c tR : teamRoles) {
			
			//Check for appropriate condition
			if(tR.Name != mapOldTeamRoles.get(tR.Id).Name)
				setTMIds.add(tR.Id);
		}
		
		//Check for set size
		if(setTMIds.size() > 0) {
			
			//List of Staff Assignment
			List<Team_Membership__c> teamMemberships = [Select Id, Staff_member__r.FirstName, Staff_member__r.LastName, Role__c,
															   Role__r.Name From Team_Membership__c Where Role__c IN : setTMIds];
			
			//Loop through Staff Assignment
			for(Team_Membership__c tM : teamMemberships)
				tM.Name = Util.parseNull(tM.Staff_member__r.FirstName) + ' ' + Util.parseNull(tM.Staff_member__r.LastName) + '-' + Util.parseNull(tM.Role__r.Name);
			
			//Check for list size
			if(teamMemberships.size() > 0)
				update teamMemberships;
		}
	}
}